import {supabase} from "../../../lib/supabase";
function db(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}

export type HsNotice={id:string;title:string;body?:string|null;noticeType:string;pinned:boolean;expiresAt?:string|null;createdAt:string;createdBy?:string|null};
export type HsComplaint={id:string;unitEntityId?:string|null;unitLabel?:string|null;category:string;title:string;description?:string|null;priority:string;status:string;slaDueAt?:string|null;assignedTo?:string|null;assignedVendorId?:string|null;resolutionNote?:string|null;createdAt:string;updatedAt:string;createdBy?:string|null;comments?:Array<{id:string;body:string;createdAt:string;authorLabel:string}>};
export type HsVendor={id:string;name:string;category:string;contactName?:string|null;phone?:string|null;email?:string|null;status:string;contractCount?:number};
export type HsAmenity={id:string;name:string;description?:string|null;location?:string|null;capacity?:number|null;bookingMode:string;status:string};
export type HsBooking={id:string;amenityId:string;amenityName:string;unitEntityId?:string|null;startsAt:string;endsAt:string;status:string;purpose?:string|null;createdBy?:string|null};
export type HsOpsSnapshot={notices:HsNotice[];complaints:HsComplaint[];vendors:HsVendor[];amenities:HsAmenity[];bookings:HsBooking[]};

export async function fetchHsOpsSnapshot(){const {data,error}=await db().rpc("hs2_get_operations_snapshot");if(error)throw error;return (data||{notices:[],complaints:[],vendors:[],amenities:[],bookings:[]}) as HsOpsSnapshot}
export async function createHsNotice(input:{title:string;body?:string;noticeType?:string;pinned?:boolean;expiresAt?:string|null}){const {data,error}=await db().rpc("hs2_create_notice",{p_title:input.title,p_body:input.body||null,p_notice_type:input.noticeType||"general",p_pinned:!!input.pinned,p_expires_at:input.expiresAt||null});if(error)throw error;return String(data)}
export async function createHsComplaint(input:{unitEntityId?:string|null;category:string;title:string;description?:string;priority?:string;photoUrl?:string}){const {data,error}=await db().rpc("hs2_create_complaint",{p_unit_entity_id:input.unitEntityId||null,p_category:input.category,p_title:input.title,p_description:input.description||null,p_priority:input.priority||"normal",p_photo_url:input.photoUrl||null});if(error)throw error;return String(data)}
export async function updateHsComplaint(input:{id:string;status?:string;assignedTo?:string|null;assignedVendorId?:string|null;slaDueAt?:string|null;resolutionNote?:string|null}){const {error}=await db().rpc("hs2_update_complaint",{p_complaint_id:input.id,p_status:input.status||null,p_assigned_to:input.assignedTo||null,p_assigned_vendor_id:input.assignedVendorId||null,p_sla_due_at:input.slaDueAt||null,p_resolution_note:input.resolutionNote||null});if(error)throw error}
export async function addHsComplaintComment(id:string,body:string){const {data,error}=await db().rpc("hs2_add_complaint_comment",{p_complaint_id:id,p_body:body});if(error)throw error;return String(data)}
export async function upsertHsVendor(input:{id?:string;name:string;category:string;contactName?:string;phone?:string;email?:string;status?:string}){const {data,error}=await db().rpc("hs2_upsert_vendor",{p_id:input.id||null,p_name:input.name,p_category:input.category,p_contact_name:input.contactName||null,p_phone:input.phone||null,p_email:input.email||null,p_status:input.status||"active"});if(error)throw error;return String(data)}
export async function createHsVendorContract(input:{vendorId:string;title:string;startsOn?:string|null;endsOn?:string|null;sla?:string|null;amount?:number|null}){const {data,error}=await db().rpc("hs2_create_vendor_contract",{p_vendor_id:input.vendorId,p_title:input.title,p_starts_on:input.startsOn||null,p_ends_on:input.endsOn||null,p_sla:input.sla||null,p_amount:input.amount??null});if(error)throw error;return String(data)}
export async function upsertHsAmenity(input:{id?:string;name:string;description?:string;location?:string;capacity?:number|null;bookingMode?:string;status?:string}){const {data,error}=await db().rpc("hs2_upsert_amenity",{p_id:input.id||null,p_name:input.name,p_description:input.description||null,p_location:input.location||null,p_capacity:input.capacity??null,p_booking_mode:input.bookingMode||"approval",p_status:input.status||"active"});if(error)throw error;return String(data)}
export async function createHsAmenityBooking(input:{amenityId:string;unitEntityId?:string|null;startsAt:string;endsAt:string;purpose?:string}){const {data,error}=await db().rpc("hs2_create_amenity_booking",{p_amenity_id:input.amenityId,p_unit_entity_id:input.unitEntityId||null,p_starts_at:input.startsAt,p_ends_at:input.endsAt,p_purpose:input.purpose||null});if(error)throw error;return String(data)}
export async function reviewHsAmenityBooking(id:string,status:"approved"|"rejected"|"cancelled"){const {error}=await db().rpc("hs2_review_amenity_booking",{p_booking_id:id,p_status:status});if(error)throw error}
