"use client";
import {Building2,GitFork,Link2,MapPin,MessageCircleQuestion,Pencil,Route,Sparkles,X} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../../core/network-os/contracts";
import type {NetworkEntityRelationship} from "../../capabilities/template-product/remote";
import type {VerticalTemplateDefinition} from "../../core/templates/contracts";
import {InitialsAvatar} from "./NetworkUi";

export default function NetworkEntityDetail({item,template,relationships,onClose,onEdit,onViewStructure,onExploreConnection,onUpdateConnection,onAskNetwork,actionCopy}:{item:NetworkAffiliatedEntity;template:VerticalTemplateDefinition;relationships:readonly NetworkEntityRelationship[];onClose:()=>void;onEdit?:()=>void;onViewStructure?:()=>void;onExploreConnection?:()=>void;onUpdateConnection?:()=>void;onAskNetwork?:()=>void;actionCopy?:{structure?:string;connection?:string;updateConnection?:string;ask?:string}}){
 const related=relationships.filter(r=>r.fromEntityId===item.entity.id||r.toEntityId===item.entity.id);
 const m=item.entity.metadata||{};
 const metadataValues=[m.city,m.website,m.email,m.code].filter((value):value is string|number=>typeof value==="string"||typeof value==="number");
 return <div className="modal-backdrop entity-detail-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal network-entity-detail" role="dialog" aria-modal="true" aria-label={`${item.entity.label} network details`}><button className="modal-x" onClick={onClose}><X/></button><div className="entity-detail-hero"><InitialsAvatar name={item.entity.label}/><div><span className="entity-kind-pill">{item.entity.kind.replaceAll("_"," ")}</span><h2>{item.entity.label}</h2><p>{String(m.role||m.contact||m.description||m.manager||"")}</p></div>{onEdit&&<button className="btn small" onClick={onEdit}><Pencil size={14}/> Edit</button>}</div><div className="entity-action-strip">{onViewStructure&&<button onClick={onViewStructure}><GitFork/><span><b>{actionCopy?.structure||"View in structure"}</b><small>See where this entity sits</small></span></button>}{onExploreConnection&&<button onClick={onExploreConnection}><Route/><span><b>{actionCopy?.connection||"How are we connected?"}</b><small>Trace known network paths</small></span></button>}{onUpdateConnection&&<button onClick={onUpdateConnection}><Link2/><span><b>{actionCopy?.updateConnection||"Update connection"}</b><small>Add or correct a relationship</small></span></button>}{onAskNetwork&&<button onClick={onAskNetwork}><MessageCircleQuestion/><span><b>{actionCopy?.ask||"Ask the network"}</b><small>Request help or context</small></span></button>}</div><div className="entity-detail-grid"><section><h3><Building2/> Network context</h3>{template.dimensions.filter(d=>(item.affiliations[d.key]||[]).length).map(d=><div className="entity-detail-row" key={d.key}><small>{d.label}</small><b>{item.affiliations[d.key].join(", ")}</b></div>)}</section><section><h3><Link2/> Relationships</h3>{related.slice(0,8).map(r=><div className="entity-detail-row" key={r.id}><small>{r.label}</small><b>{r.fromEntityId===item.entity.id?r.toLabel:r.fromLabel}</b></div>)}{!related.length&&<p className="muted">No typed relationships yet.</p>}</section></div>{metadataValues.length>0&&<div className="entity-detail-meta"><MapPin size={14}/>{metadataValues.map((v,i)=><span key={i}>{String(v)}</span>)}</div>}<div className="entity-detail-insight"><Sparkles size={14}/><span>This profile becomes more useful as relationships, activity and verified context accumulate around it.</span></div></section></div>
}
