'use client';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { supabase } from '../../../lib/supabase';
import { acceptInvitation, fetchInvitationPreview } from '../../../lib/remote';

export default function InvitePage() {
  const params = useParams<{token:string}>(); const router = useRouter();
  const token=String(params.token);
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<any>(null),[existing,setExisting]=useState(false);
  useEffect(()=>{(async()=>{if(!supabase)return;try{const p=await fetchInvitationPreview(token);setPreview(p);if(!p||p.status!=='active')throw new Error(p?.status==='revoked'?'This invitation was revoked. Ask for a fresh link.':'This invitation is expired or already used.');setName(p.member_name||'');const {data:{session}}=await supabase.auth.getSession();if(session){await acceptInvitation(token);setMessage('Profile claimed. Welcome!');setTimeout(()=>router.push('/'),900)}}catch(e:any){setMessage(e.message||'This invitation is invalid or expired.')}})()},[token,router]);
  const submit=async(e:any)=>{e.preventDefault();setBusy(true);setMessage('');try{if(!supabase)throw new Error('Shared mode is required for invitations.');if(existing){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}else{const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;if(!data.session){setMessage('Confirm your email, then open this same invitation link to finish claiming your profile.');return}}await acceptInvitation(token);setMessage('Profile claimed. Welcome!');setTimeout(()=>router.push('/'),900)}catch(x:any){setMessage(x.message||'Could not claim this profile.')}finally{setBusy(false)}};
  const active=preview?.status==='active';
  return <main className="landing"><form className="landing-card invite-journey" onSubmit={submit}><h1>{active?`Join as ${preview.member_name}`:'Private invitation'}</h1><p className="page-subtitle">This single-use link connects your account to the matching family profile. Joining does not make it public.</p>{active&&<><div className="segmented activation-toggle"><button type="button" className={!existing?'active':''} onClick={()=>setExisting(false)}>I’m new</button><button type="button" className={existing?'active':''} onClick={()=>setExisting(true)}>I have an account</button></div>{!existing&&<div className="field" style={{marginTop:12}}><label>Your name</label><input className="text-input" value={name} onChange={e=>setName(e.target.value)} required/></div>}<div className="field" style={{marginTop:12}}><label>Email</label><input className="text-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field" style={{marginTop:12}}><label>Password</label><input className="text-input" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></div></>}{message&&<div className="notice" style={{marginTop:14}}>{message}</div>}<div className="form-actions"><button className="btn" type="button" onClick={()=>router.push('/')}>Back</button>{active&&<button className="btn primary" disabled={busy}>{busy?'Joining…':existing?'Sign in & claim':'Create account & join'}</button>}</div></form></main>;
}
