"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {Building2,CheckCircle2,ShieldCheck} from "lucide-react";
import {supabase} from "../../../lib/supabase";
import {acceptHsInvitation,fetchHsInvitationPreview} from "../../../verticals/housing-society/runtime/remote";
export default function SocietyInvitePage(){
 const {token}=useParams<{token:string}>(),router=useRouter();const [preview,setPreview]=useState<any>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[existing,setExisting]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[joined,setJoined]=useState(false);
 useEffect(()=>{fetchHsInvitationPreview(String(token)).then(p=>{setPreview(p);setEmail(p?.email||"")}).catch(e=>setMessage(e.message||"Could not open invitation."))},[token]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setMessage("");try{if(existing){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}else{const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:preview?.resident_name}}});if(error)throw error;if(!data.session){setMessage("Confirm your email, then reopen this invitation to complete claiming.");return}}await acceptHsInvitation(String(token));setJoined(true)}catch(e:any){setMessage(e.message||"Could not join this society.")}finally{setBusy(false)}};
 if(joined)return <main className="invite-friendly-page"><section className="invite-friendly-card invite-success"><CheckCircle2/><span className="warm-kicker">Resident profile claimed</span><h1>Welcome to {preview?.society_name}</h1><p>Your account is connected to {preview?.resident_name}{preview?.unit_label?` · ${preview.unit_label}`:""}. Property ownership remains committee-governed.</p><button className="btn primary invite-main-action" onClick={()=>router.push("/")}>Open society</button></section></main>;
 if(!preview)return <main className="invite-friendly-page"><section className="invite-friendly-card"><Building2/><h1>Housing Society invitation</h1><p>{message||"Opening your invitation…"}</p></section></main>;
 if(preview.status!=="active")return <main className="invite-friendly-page"><section className="invite-friendly-card"><Building2/><h1>This invitation is {preview.status}</h1><p>Ask the society committee for a fresh invitation.</p></section></main>;
 return <main className="invite-friendly-page"><section className="invite-friendly-card"><Building2/><span className="warm-kicker">{preview.society_name}</span><h1>Claim {preview.resident_name}</h1><p>{preview.unit_label?`Resident record for ${preview.unit_label}. `:""}Use the invited email <b>{preview.email}</b>.</p><div className="segmented activation-toggle"><button type="button" className={!existing?"active":""} onClick={()=>setExisting(false)}>Create account</button><button type="button" className={existing?"active":""} onClick={()=>setExisting(true)}>I have an account</button></div><form onSubmit={submit}><label className="field"><span>Email</span><input className="text-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="field"><span>Password</span><input className="text-input" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="notice invite-message">{message}</div>}<button className="btn primary invite-main-action" disabled={busy}>{busy?"Connecting…":"Join & claim resident profile"}</button></form><div className="invite-privacy"><ShieldCheck size={17}/><span>Single-resident claiming does not grant permission to change official owner/tenant history.</span></div></section></main>;
}
