"use client";
import {useState} from "react";
import {AlertTriangle,CheckCircle2,Download,FileSpreadsheet,ShieldCheck,UploadCloud,XCircle} from "lucide-react";
import type {NetworkVerticalKind} from "../../core/verticals/contracts";
import {getImportSchema} from "../../core/import/registry";
import {downloadImportWorkbook} from "../../core/import/workbook";
import {parseImportWorkbook} from "../../core/import/parser";
import type {ImportCommitResult,ImportReview} from "../../core/import/contracts";
import {NetworkSectionHead} from "./NetworkUi";

export default function GuidedWorkbookImport({kind,onCommit,onCommitted,title}:{kind:NetworkVerticalKind;onCommit:(review:ImportReview)=>Promise<ImportCommitResult>;onCommitted?:(result:ImportCommitResult)=>Promise<void>|void;title?:string}){
 const schema=getImportSchema(kind);const [review,setReview]=useState<ImportReview|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const read=async(file:File)=>{setBusy(true);setMessage("");try{setReview(await parseImportWorkbook(await file.arrayBuffer(),file.name,schema))}catch(e:any){setReview(null);setMessage(e.message||"Could not read workbook.")}finally{setBusy(false)}};
 const commit=async()=>{if(!review?.canCommit)return;setBusy(true);setMessage("");try{const result=await onCommit(review);setMessage(result.message);setReview(null);await onCommitted?.(result)}catch(e:any){setMessage(e.message||"Import failed.")}finally{setBusy(false)}};
 return <section className="card xp1-guided-import"><NetworkSectionHead kicker={<><FileSpreadsheet size={12}/> Guided workbook</>} title={title||schema.title} description="Download → fill → upload → validate → preview → confirm. No database work is required."/><div className="product-import-card"><div><FileSpreadsheet/><span><h3>Start with the generated template</h3><p>{schema.description} · schema {schema.version}</p></span></div><button className="btn" onClick={()=>downloadImportWorkbook(schema)}><Download size={15}/> Download XLSX</button><label className="btn primary"><UploadCloud size={15}/> {busy?"Reading…":"Choose completed file"}<input hidden disabled={busy} type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&void read(e.target.files[0])}/></label></div><div className="import-assurance"><ShieldCheck/><span><b>Privacy-aware template.</b> {schema.privacyNotes[0]} Stable IDs are workbook references, not government IDs.</span></div>
 {review&&<div className="xp1-review"><div className={`review-hero ${review.canCommit?"ready":"needs-help"}`}>{review.canCommit?<CheckCircle2/>:<AlertTriangle/>}<div><h3>{review.canCommit?"Ready to confirm import":"Fix rejected rows before import"}</h3><p>{review.fileName} · {review.validRows} valid · {review.warningRows} warnings · {review.rejectedRows} rejected</p></div></div><div className="network-metric-grid">{review.sheets.map(s=><div className="network-metric" key={s.schema.key}><b>{s.rows.length}</b><span>{s.schema.name}</span><small>{s.rejectedRows?`${s.rejectedRows} rejected`:"validated"}</small></div>)}</div>{review.issues.length>0&&<div className="friendly-issues">{review.issues.slice(0,20).map((i,n)=><div className={`issue-row ${i.severity==="error"?"error":"warning"}`} key={n}>{i.severity==="error"?<XCircle/>:<AlertTriangle/>}<span><b>{i.sheet}{i.row?` · row ${i.row}`:""}{i.column?` · ${i.column}`:""}</b>{i.message}</span></div>)}</div>}<div className="table-wrap"><table><thead><tr><th>Sheet</th><th>Row</th><th>Status</th><th>Preview</th></tr></thead><tbody>{review.sheets.flatMap(s=>s.rows.slice(0,8)).slice(0,30).map(r=><tr key={`${r.sheetKey}-${r.rowNumber}`}><td>{r.sheetName}</td><td>{r.rowNumber}</td><td>{r.status}</td><td>{Object.values(r.values).filter(Boolean).slice(0,4).map(String).join(" · ")||"—"}</td></tr>)}</tbody></table></div><div className="form-actions"><button className="btn" onClick={()=>setReview(null)}>Discard</button><button className="btn primary" disabled={busy||!review.canCommit} onClick={()=>void commit()}>{busy?"Importing…":"Confirm import"}</button></div></div>}
 {message&&<div className="notice">{message}</div>}</section>;
}
