"use client";
import {useMemo,useState} from "react";
import {CalendarDays,Heart,MapPin,MessageSquareText,Plus,Sparkles,UsersRound} from "lucide-react";
import type {NetworkActivity,NetworkActivityType} from "../../core/network-os/contracts";
import type {NetworkGroup} from "../../capabilities/activity/remote";
import {NetworkEmpty,NetworkSectionHead} from "./NetworkUi";

const defaultTypeLabel:Record<NetworkActivityType,string>={event:"Meetups & events",memory:"Memories",milestone:"Milestones",announcement:"Updates"};
export default function NetworkActivityHub({activities,groups=[],isAdmin=false,readOnly=false,onCreate,onRsvp,onCreateGroup,onToggleGroup,copy}:{activities:readonly NetworkActivity[];groups?:readonly NetworkGroup[];isAdmin?:boolean;readOnly?:boolean;onCreate?:(input:{type:NetworkActivityType;title:string;body?:string;startsAt?:string;place?:string})=>Promise<void>|void;onRsvp?:(id:string,response:"going"|"maybe"|"declined")=>Promise<void>|void;onCreateGroup?:(input:{name:string;groupType?:string;description?:string})=>Promise<void>|void;onToggleGroup?:(group:NetworkGroup)=>Promise<void>|void;copy?:{title?:string;description?:string;eventLabel?:string;memoryLabel?:string;milestoneLabel?:string;announcementLabel?:string;groupTitle?:string;groupDescription?:string}}){
 const typeLabel:Record<NetworkActivityType,string>={event:copy?.eventLabel||defaultTypeLabel.event,memory:copy?.memoryLabel||defaultTypeLabel.memory,milestone:copy?.milestoneLabel||defaultTypeLabel.milestone,announcement:copy?.announcementLabel||defaultTypeLabel.announcement};
 const [type,setType]=useState<NetworkActivityType>("event"),[composer,setComposer]=useState(false),[title,setTitle]=useState(""),[body,setBody]=useState(""),[place,setPlace]=useState(""),[startsAt,setStartsAt]=useState("");
 const filtered=useMemo(()=>activities.filter(a=>a.type===type),[activities,type]);
 const submit=async()=>{if(!title.trim())return;await onCreate?.({type,title:title.trim(),body:body.trim()||undefined,place:place.trim()||undefined,startsAt:startsAt||undefined});setComposer(false);setTitle("");setBody("");setPlace("");setStartsAt("")};
 return <div className="network-activity-hub"><NetworkSectionHead kicker={<><Sparkles size={12}/> Shared network life</>} title={copy?.title||"Community, events & memories"} description={copy?.description||"The same activity engine can power family gatherings, alumni reunions, organizational workshops and franchise training — with vertical-specific language and policies."} action={!readOnly?<button className="btn primary small" onClick={()=>setComposer(v=>!v)}><Plus size={14}/> Add</button>:undefined}/>
  <div className="activity-tabs">{(["event","memory","milestone","announcement"] as NetworkActivityType[]).map(k=><button key={k} className={type===k?"active":""} onClick={()=>setType(k)}>{k==="event"?<CalendarDays/>:k==="memory"?<Heart/>:k==="milestone"?<Sparkles/>:<MessageSquareText/>}{typeLabel[k]}</button>)}</div>
  {composer&&<section className="card activity-composer"><div className="form-grid"><label className="field full"><span>Type</span><select className="select" value={type} onChange={e=>setType(e.target.value as NetworkActivityType)}>{Object.entries(typeLabel).filter(([k])=>isAdmin||k==="memory"||k==="milestone").map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field full"><span>Title</span><input className="text-input" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field full"><span>Story / details</span><textarea className="text-input" value={body} onChange={e=>setBody(e.target.value)} rows={3}/></label>{type==="event"&&<><label className="field"><span>Date & time</span><input className="text-input" type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label className="field"><span>Place</span><input className="text-input" value={place} onChange={e=>setPlace(e.target.value)}/></label></>}<div className="form-actions full"><button className="btn" onClick={()=>setComposer(false)}>Cancel</button><button className="btn primary" onClick={submit}>Publish</button></div></div></section>}
  <div className="activity-grid">{filtered.map(a=><article className="card activity-card" key={a.id}><span className={`activity-type ${a.type}`}>{typeLabel[a.type]}</span><h3>{a.title}</h3>{a.body&&<p>{a.body}</p>}<div className="activity-meta">{a.startsAt&&<span><CalendarDays size={13}/>{new Date(a.startsAt).toLocaleString()}</span>}{a.place&&<span><MapPin size={13}/>{a.place}</span>}{a.type==="event"&&<span><UsersRound size={13}/>{a.goingCount||0} going</span>}</div>{a.type==="event"&&!readOnly&&<div className="activity-rsvp"><button className={a.myRsvp==="going"?"active":""} onClick={()=>onRsvp?.(a.id,"going")}>Going</button><button className={a.myRsvp==="maybe"?"active":""} onClick={()=>onRsvp?.(a.id,"maybe")}>Maybe</button><button className={a.myRsvp==="declined"?"active":""} onClick={()=>onRsvp?.(a.id,"declined")}>Can't go</button></div>}</article>)}{filtered.length===0&&<NetworkEmpty icon={type==="event"?<CalendarDays/>:<Heart/>} title={`No ${typeLabel[type].toLowerCase()} yet`} description="This space will grow as the network starts sharing activity."/>}</div>
  <section className="groups-strip card"><div><span className="warm-kicker"><UsersRound size={12}/> Groups & chapters</span><h3>{copy?.groupTitle||"Smaller circles inside the network"}</h3><p>{copy?.groupDescription||"Chapters, guilds, committees or interest groups can use the same shared group foundation."}</p></div><div className="group-chip-list">{groups.map(g=><button className={`group-chip ${g.myMember?"joined":""}`} key={g.id} onClick={()=>!readOnly&&onToggleGroup?.(g)}><b>{g.name}</b><small>{g.groupType} · {g.memberCount} member{g.memberCount===1?"":"s"}{g.myMember?" · Joined":""}</small></button>)}{groups.length===0&&<span className="muted-chip">No groups yet</span>}</div>{isAdmin&&!readOnly&&onCreateGroup&&<button className="btn small" onClick={()=>{const name=window.prompt("Group or chapter name");if(name)onCreateGroup({name,groupType:"chapter"})}}>Create group</button>}</section>
 </div>
}
