"use client";
import {useLanguage} from "../../lib/i18n";
import {useMemo,useState} from "react";
import {CalendarDays,Heart,MapPin,MessageSquareText,Plus,Share2,Sparkles,UsersRound} from "lucide-react";
import type {NetworkActivity,NetworkActivityType} from "../../core/network-os/contracts";
import type {NetworkGroup} from "../../capabilities/activity/remote";
import {NetworkEmpty,NetworkSectionHead} from "./NetworkUi";

const defaultTypeLabel:Record<NetworkActivityType,string>={event:"Meetups & events",memory:"Memories",milestone:"Milestones",announcement:"Updates"};
export default function NetworkActivityHub({activities,groups=[],isAdmin=false,readOnly=false,onCreate,onRsvp,onCreateGroup,onToggleGroup,onLike,onComment,copy}:{activities:readonly NetworkActivity[];groups?:readonly NetworkGroup[];isAdmin?:boolean;readOnly?:boolean;onCreate?:(input:{type:NetworkActivityType;title:string;body?:string;startsAt?:string;place?:string})=>Promise<void>|void;onRsvp?:(id:string,response:"going"|"maybe"|"declined")=>Promise<void>|void;onCreateGroup?:(input:{name:string;groupType?:string;description?:string})=>Promise<void>|void;onToggleGroup?:(group:NetworkGroup)=>Promise<void>|void;onLike?:(id:string)=>Promise<void>|void;onComment?:(id:string,body:string)=>Promise<void>|void;copy?:{title?:string;description?:string;eventLabel?:string;memoryLabel?:string;milestoneLabel?:string;announcementLabel?:string;groupTitle?:string;groupDescription?:string}}){
 const {t:tr}=useLanguage();
 const typeLabel:Record<NetworkActivityType,string>={event:copy?.eventLabel||defaultTypeLabel.event,memory:copy?.memoryLabel||defaultTypeLabel.memory,milestone:copy?.milestoneLabel||defaultTypeLabel.milestone,announcement:copy?.announcementLabel||defaultTypeLabel.announcement};
 const [type,setType]=useState<NetworkActivityType>("event"),[composer,setComposer]=useState(false),[title,setTitle]=useState(""),[body,setBody]=useState(""),[place,setPlace]=useState(""),[startsAt,setStartsAt]=useState("");
 const filtered=useMemo(()=>activities.filter(a=>a.type===type),[activities,type]);
 const submit=async()=>{if(!title.trim())return;await onCreate?.({type,title:title.trim(),body:body.trim()||undefined,place:place.trim()||undefined,startsAt:startsAt||undefined});setComposer(false);setTitle("");setBody("");setPlace("");setStartsAt("")};
 return <div className="network-activity-hub"><NetworkSectionHead kicker={<><Sparkles size={12}/> {tr("SharedNetworkLifeTxt")}</>} title={copy?.title||tr("CommunityEventsAndMemoriesTxt")} description={copy?.description||tr("TheSameActivityEngineCanPowerFamilyTxt")} action={!readOnly?<button className="btn primary small" onClick={()=>setComposer(v=>!v)}><Plus size={14}/> {tr("AddTxt")}</button>:undefined}/>
  <div className="activity-tabs">{(["event","memory","milestone","announcement"] as NetworkActivityType[]).map(k=><button key={k} className={type===k?"active":""} onClick={()=>setType(k)}>{k==="event"?<CalendarDays/>:k==="memory"?<Heart/>:k==="milestone"?<Sparkles/>:<MessageSquareText/>}{typeLabel[k]}</button>)}</div>
  {composer&&<section className="card activity-composer"><div className="form-grid"><label className="field full"><span>{tr("TypeTxt")}</span><select className="select" value={type} onChange={e=>setType(e.target.value as NetworkActivityType)}>{Object.entries(typeLabel).filter(([k])=>isAdmin||k===tr("MemoryTxt")||k===tr("Milestone2Txt")).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field full"><span>{tr("TitleTxt")}</span><input className="text-input" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field full"><span>{tr("StoryDetailsTxt")}</span><textarea className="text-input" value={body} onChange={e=>setBody(e.target.value)} rows={3}/></label>{type==="event"&&<><label className="field"><span>{tr("DateAndTimeTxt")}</span><input className="text-input" type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label className="field"><span>{tr("PlaceTxt")}</span><input className="text-input" value={place} onChange={e=>setPlace(e.target.value)}/></label></>}<div className="form-actions full"><button className="btn" onClick={()=>setComposer(false)}>{tr("CancelTxt")}</button><button className="btn primary" onClick={submit}>{tr("PublishTxt")}</button></div></div></section>}
  <div className="activity-grid">{filtered.map(a=><article className="card activity-card" key={a.id}><span className={`activity-type ${a.type}`}>{typeLabel[a.type]}</span><h3>{a.title}</h3>{a.body&&<p>{a.body}</p>}<div className="activity-meta">{a.startsAt&&<span><CalendarDays size={13}/>{new Date(a.startsAt).toLocaleString()}</span>}{a.place&&<span><MapPin size={13}/>{a.place}</span>}{a.type==="event"&&<span><UsersRound size={13}/>{a.goingCount||0} {tr("Going3Txt")}</span>}</div>{a.type==="event"&&!readOnly&&<div className="activity-rsvp"><button className={a.myRsvp==="going"?"active":""} onClick={()=>onRsvp?.(a.id,"going")}>{tr("Going2Txt")}</button><button className={a.myRsvp==="maybe"?"active":""} onClick={()=>onRsvp?.(a.id,"maybe")}>{tr("MaybeTxt")}</button><button className={a.myRsvp==="declined"?"active":""} onClick={()=>onRsvp?.(a.id,"declined")}>{tr("CanTGoTxt")}</button></div>}{!readOnly&&<div className="activity-engagement"><button className={a.myLiked?"active":""} onClick={()=>onLike?.(a.id)}><Heart size={14}/>{a.likeCount||0}</button><button onClick={()=>{const body=window.prompt("Add a comment");if(body?.trim())onComment?.(a.id,body.trim())}}><MessageSquareText size={14}/>{a.commentCount||0}</button><button onClick={async()=>{const text=`${a.title}${a.body?` — ${a.body}`:""}`;try{if(navigator.share)await navigator.share({title:a.title,text});else await navigator.clipboard?.writeText(text)}catch{}}}><Share2 size={14}/> Share</button></div>}</article>)}{filtered.length===0&&<NetworkEmpty icon={type==="event"?<CalendarDays/>:<Heart/>} title={`No ${typeLabel[type].toLowerCase()} yet`} description={tr("ThisSpaceWillGrowAsTheNetworkTxt")}/>}</div>
  <section className="groups-strip card"><div><span className="warm-kicker"><UsersRound size={12}/> {tr("GroupsAndChaptersTxt")}</span><h3>{copy?.groupTitle||tr("SmallerCirclesInsideTheNetworkTxt")}</h3><p>{copy?.groupDescription||tr("ChaptersGuildsCommitteesOrInterestGroupsCanTxt")}</p></div><div className="group-chip-list">{groups.map(g=><button className={`group-chip ${g.myMember?"joined":""}`} key={g.id} onClick={()=>!readOnly&&onToggleGroup?.(g)}><b>{g.name}</b><small>{g.groupType} · {g.memberCount} {tr("Member2Txt")}{g.memberCount===1?"":"s"}{g.myMember?tr("JoinedTxt"):""}</small></button>)}{groups.length===0&&<span className="muted-chip">{tr("NoGroupsYetTxt")}</span>}</div>{isAdmin&&!readOnly&&onCreateGroup&&<button className="btn small" onClick={()=>{const name=window.prompt("Group or chapter name");if(name)onCreateGroup({name,groupType:"chapter"})}}>{tr("CreateGroupTxt")}</button>}</section>
 </div>
}
