"use client";
import {ArrowRight,BookHeart,Handshake,Lightbulb,MessageCircleQuestion,Sparkles,UsersRound} from "lucide-react";
import type {NetworkActivity} from "../../core/network-os/contracts";
import type {NetworkGroup} from "../../capabilities/activity/remote";
import {NetworkEmpty,NetworkSectionHead} from "./NetworkUi";

export type KnowledgeHelpCopy={knowledgeTitle:string;knowledgeDescription:string;knowledgeItemLabel:string;helpTitle:string;helpDescription:string;helpPrompts:readonly string[];communityValueTitle:string;communityValueDescription:string};
export default function NetworkKnowledgeHelpHub({activities,groups,copy,onOpenCommunity,onAskForHelp,onOpenKnowledge}:{activities:readonly NetworkActivity[];groups:readonly NetworkGroup[];copy:KnowledgeHelpCopy;onOpenCommunity:()=>void;onAskForHelp:(prompt:string)=>void;onOpenKnowledge:()=>void}){
 const knowledge=activities.filter(a=>a.type==="memory"||a.type==="milestone"||a.type==="announcement").slice(0,6);
 return <div className="knowledge-help-hub"><NetworkSectionHead kicker={<><Sparkles size={12}/> Living network value</>} title={copy.knowledgeTitle} description={copy.knowledgeDescription}/><div className="knowledge-help-grid"><section className="card knowledge-wall-preview"><div className="knowledge-panel-head"><BookHeart/><span><small>{copy.knowledgeItemLabel}</small><h3>What the network has learned</h3></span><button className="btn small" onClick={onOpenKnowledge}>Open all <ArrowRight size={13}/></button></div><div className="knowledge-story-list">{knowledge.map(item=><article key={item.id}><span>{item.type==="memory"?"Lesson":item.type==="milestone"?"Outcome":"Update"}</span><b>{item.title}</b>{item.body&&<p>{item.body}</p>}</article>)}{knowledge.length===0&&<NetworkEmpty icon={<Lightbulb/>} title="No shared learning yet" description="Capture useful outcomes, lessons and evidence so the next person can reuse them."/>}</div></section><section className="card network-help-panel"><div className="knowledge-panel-head"><MessageCircleQuestion/><span><small>Ask the network</small><h3>{copy.helpTitle}</h3></span></div><p>{copy.helpDescription}</p><div className="help-prompt-list">{copy.helpPrompts.map(prompt=><button key={prompt} onClick={()=>onAskForHelp(prompt)}><Handshake size={15}/><span>{prompt}</span><ArrowRight size={13}/></button>)}</div></section></div><section className="card community-value-panel"><UsersRound/><div><span className="warm-kicker">Focused communities</span><h3>{copy.communityValueTitle}</h3><p>{copy.communityValueDescription}</p><small>{groups.length} active circle{groups.length===1?"":"s"} in this network</small></div><button className="btn" onClick={onOpenCommunity}>Explore communities <ArrowRight size={14}/></button></section></div>
}
