import {fetchNetworkAffiliatedEntities} from "../affiliation/remote";
import {createNetworkEntityRelationship,fetchNetworkEntityRelationships,upsertNetworkEntity} from "../template-product/remote";
import type {ImportCommitResult,ImportReview,ImportSheetSchema,ParsedImportRow} from "../../core/import/contracts";

function value(row:ParsedImportRow,key:string){return row.values[key]}
function buildEntity(row:ParsedImportRow,sheet:ImportSheetSchema,schemaVersion:string){const metadata:Record<string,unknown>={},affiliations:Record<string,string|string[]>={};let label="",stableId="";for(const col of sheet.columns){const v=value(row,col.key);if(v===""||v==null)continue;if(col.target==="label")label=String(v);else if(col.target==="stableId")stableId=String(v);else if(col.target.startsWith("metadata."))metadata[col.target.slice(9)]=v;else if(col.target.startsWith("affiliation."))affiliations[col.target.slice(12)]=String(v)}if(stableId)metadata.importStableId=stableId;metadata.importSchemaVersion=schemaVersion;return {kind:sheet.entityKind||"custom",label,stableId,metadata,affiliations}}
export async function commitProductizedWorkbook(review:ImportReview):Promise<ImportCommitResult>{
 if(!review.canCommit)throw new Error("Resolve import validation errors before committing.");const existing=await fetchNetworkAffiliatedEntities();const stableMap=new Map<string,string>();for(const e of existing){const sid=String(e.entity.metadata?.importStableId||"").trim().toLowerCase();if(sid)stableMap.set(`${e.entity.kind}|${sid}`,e.entity.id)}const refMap=new Map<string,string>();let created=0,updated=0,relationships=0,skipped=0;
 for(const sheet of review.sheets.filter(s=>s.schema.recordType==="entity")){for(const row of sheet.rows.filter(r=>r.status!=="rejected")){const item=buildEntity(row,sheet.schema,review.schema.version);if(!item.label){skipped++;continue}const existingId=item.stableId?stableMap.get(`${item.kind}|${item.stableId.toLowerCase()}`):undefined;const id=await upsertNetworkEntity({id:existingId,kind:item.kind,label:item.label,metadata:item.metadata,affiliations:item.affiliations});if(existingId)updated++;else created++;if(item.stableId){refMap.set(item.stableId.toLowerCase(),id);stableMap.set(`${item.kind}|${item.stableId.toLowerCase()}`,id)}}}
 const existingRelationships=await fetchNetworkEntityRelationships();const edgeKeys=new Set(existingRelationships.map(r=>`${r.fromEntityId}|${r.toEntityId}|${r.relationshipType}`));for(const sheet of review.sheets.filter(s=>s.schema.recordType==="relationship")){for(const row of sheet.rows.filter(r=>r.status!=="rejected")){const from=refMap.get(String(row.values.from_id||"").toLowerCase())||refMap.get(String(row.values.fromRef||"").toLowerCase());const to=refMap.get(String(row.values.to_id||"").toLowerCase())||refMap.get(String(row.values.toRef||"").toLowerCase());const rel=String(row.values.relationship||row.values.relationship_type||"").trim();if(!from||!to||!rel){skipped++;continue}const key=`${from}|${to}|${rel}`;if(edgeKeys.has(key)){skipped++;continue}await createNetworkEntityRelationship(from,to,rel,{importSchemaVersion:review.schema.version});edgeKeys.add(key);relationships++}}
 return {created,updated,relationships,skipped,message:`Imported ${created} new, updated ${updated}, created ${relationships} relationships${skipped?` and skipped ${skipped} existing/incomplete rows`:""}.`};
}
