"use client";
import {useEffect,useMemo,useState,type ReactNode} from "react";
import * as XLSX from "xlsx";
import {ArrowRight,BookOpen,BriefcaseBusiness,Building2,CalendarDays,CheckCircle2,FileSpreadsheet,GraduationCap,HeartHandshake,Home,Layers3,LockKeyhole,LogOut,Map as MapIcon,MapPin,Search,ShieldCheck,Sparkles,UserRound,UsersRound} from "lucide-react";
import {getVerticalCapabilityRuntime} from "../app-shell/vertical-capabilities";
import {getVerticalAppComposition,localizedSurfaceLabel} from "../app-shell/vertical-runtime";
import {createFeatureRuntime} from "../core/features/runtime";
import type {EffectiveFeatureMap} from "../core/features/contracts";
import type {NetworkAffiliatedEntity,NetworkActivity,NetworkProjectionDefinition} from "../core/network-os/contracts";
import {fetchEffectivePlatformFeatures,fetchPlaygroundFeatures} from "../lib/remote";
import {ALUMNI_FEATURE_CATALOG,type AlumniExperienceLevel,type AlumniFeatureKey} from "../verticals/alumni/features/catalog";
import {fetchAlumniConnections,fetchAlumniDirectory,fetchAlumniNetworkOverview,saveMyAlumniProfile,createAlumniInvitation,connectAlumniProfile,type AlumniConnection,type AlumniNetworkOverview,type AlumniProfile,type AlumniImportRow} from "../verticals/alumni/data/remote";
import {fetchNetworkAffiliatedEntities,fetchNetworkProjections} from "../capabilities/affiliation/remote";
import {createNetworkActivity,createNetworkGroup,fetchNetworkActivities,fetchNetworkGroups,respondNetworkEvent,joinNetworkGroup,leaveNetworkGroup,type NetworkGroup} from "../capabilities/activity/remote";
import type {NetworkSettings} from "../lib/network";
import type {AuthUser} from "../lib/auth";
import NetworkTopbar from "./shared/NetworkTopbar";
import NetworkSwitcher from "./shared/NetworkSwitcher";
import NetworkProjectionExplorer from "./shared/NetworkProjectionExplorer";
import NetworkActivityHub from "./shared/NetworkActivityHub";
import {InitialsAvatar,NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";

type Tab="home"|"explorer"|"directory"|"community"|"places"|"connections"|"admin"|"guide";
const runtime=getVerticalCapabilityRuntime("alumni");
const composition=getVerticalAppComposition("alumni");
const featureRuntime=createFeatureRuntime(ALUMNI_FEATURE_CATALOG);

const sample:AlumniProfile[]=[
 {id:"a1",full_name:"Aditi Deshmukh",graduation_year:2011,program:"Computer Engineering",department:"Engineering",city:"Pune",company:"CloudWorks",job_title:"Engineering Director",visibility:"members",claimed:true,is_me:true},
 {id:"a2",full_name:"Rahul Mehta",graduation_year:2011,program:"Computer Engineering",department:"Engineering",city:"Bengaluru",company:"FinScale",job_title:"Principal Engineer",visibility:"members",claimed:true,is_me:false},
 {id:"a3",full_name:"Neha Kulkarni",graduation_year:2011,program:"MBA",department:"Management",city:"Mumbai",company:"Growth Labs",job_title:"Founder",visibility:"members",claimed:false,is_me:false},
 {id:"a4",full_name:"Sameer Shah",graduation_year:2012,program:"Mechanical Engineering",department:"Engineering",city:"Pune",company:"MobilityX",job_title:"Product Lead",visibility:"members",claimed:false,is_me:false},
 {id:"a5",full_name:"Meera Joshi",graduation_year:2012,program:"Computer Engineering",department:"Engineering",city:"Pune",company:"Open Systems",job_title:"VP Engineering",visibility:"members",claimed:true,is_me:false},
 {id:"a6",full_name:"Kunal Patil",graduation_year:2012,program:"MBA",department:"Management",city:"Nashik",company:"AutoNova",job_title:"Operations Head",visibility:"members",claimed:false,is_me:false},
];
const sampleOverview:AlumniNetworkOverview={institution_name:"MET",profile_count:sample.length,claimed_count:sample.filter(x=>x.claimed).length,batch_count:2,program_count:4};
const sampleProjections:NetworkProjectionDefinition[]=[
 {key:"institution-program-batch-stream",label:"Program → Batch → Stream",levels:["institution","department","batch","program"],default:true},
 {key:"institution-batch-program-stream",label:"Batch → Program → Stream",levels:["institution","batch","department","program"]},
 {key:"city-institution-batch",label:"City → Institution → Batch",levels:["city","institution","batch"]},
 {key:"company-institution-batch",label:"Company → Institution → Batch",levels:["company","institution","batch"]},
];
const sampleAffiliated:NetworkAffiliatedEntity[]=sample.map(p=>({entity:{id:p.id,networkId:"sample",kind:"person",label:p.full_name,externalRef:p.id},affiliations:{institution:["MET"],department:p.department?[p.department]:[],batch:p.graduation_year?[String(p.graduation_year)]:[],program:p.program?[p.program]:[],city:p.city?[p.city]:[],company:p.company?[p.company]:[]}}));
const sampleActivities:NetworkActivity[]=[
 {id:"e1",type:"event",title:"MET 2011 Reunion",body:"Reconnect with Engineering and MBA friends from the 2011 cohort.",startsAt:"2026-09-19T18:30:00",place:"Pune",visibility:"members",goingCount:18,myRsvp:null},
 {id:"m1",type:"memory",title:"Annual gathering memories",body:"Photos and stories from the campus annual gathering.",visibility:"members"},
 {id:"m2",type:"milestone",title:"15 years since graduation",body:"Class of 2011 reaches a shared milestone this year.",visibility:"members"},
 {id:"a1",type:"announcement",title:"Pune Alumni Chapter",body:"A city chapter is forming for nearby alumni and meetups.",visibility:"members"},
];
const sampleGroups:NetworkGroup[]=[{id:"g1",name:"Pune Chapter",groupType:"chapter",description:"Alumni in Pune",memberCount:3},{id:"g2",name:"Technology Circle",groupType:"interest",description:"Technology professionals",memberCount:4}];

function icon(token:string,size=17):ReactNode{if(token==="home")return <Home size={size}/>;if(token==="users")return <UsersRound size={size}/>;if(token==="layers")return <Layers3 size={size}/>;if(token==="calendar")return <CalendarDays size={size}/>;if(token==="map")return <MapIcon size={size}/>;if(token==="heart-handshake")return <HeartHandshake size={size}/>;if(token==="book-open")return <BookOpen size={size}/>;return <ShieldCheck size={size}/>}
function connectionReason(me:AlumniProfile|undefined,p:AlumniProfile){if(!me)return p.program||p.company||"Alumni connection";if(me.graduation_year&&me.graduation_year===p.graduation_year)return `Class of ${p.graduation_year}`;if(me.program&&me.program===p.program)return `Same stream · ${p.program}`;if(me.company&&me.company===p.company)return `Both at ${p.company}`;if(me.city&&me.city===p.city)return `Both in ${p.city}`;return p.program||p.company||"Across the alumni network"}

export default function AlumniNetworkApp({network,auth,demo=false,onNetworkChanged,onOpenNetworkLobby,onSignOut}:{network:NetworkSettings;auth:AuthUser|null;demo?:boolean;onNetworkChanged:()=>Promise<void>|void;onOpenNetworkLobby?:()=>Promise<void>|void;onSignOut:()=>Promise<void>|void}){
 const [tab,setTab]=useState<Tab>("home"),[profiles,setProfiles]=useState<AlumniProfile[]>(demo?sample:[]),[query,setQuery]=useState(""),[year,setYear]=useState<number|undefined>(),[program,setProgram]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [editing,setEditing]=useState<Partial<AlumniProfile>>({}),[importRows,setImportRows]=useState<AlumniImportRow[]>([]),[overview,setOverview]=useState<AlumniNetworkOverview>(demo?sampleOverview:{institution_name:network.name,profile_count:0,claimed_count:0,batch_count:0,program_count:0}),[connections,setConnections]=useState<AlumniConnection[]>([]);
 const [affiliated,setAffiliated]=useState<NetworkAffiliatedEntity[]>(demo?sampleAffiliated:[]),[projections,setProjections]=useState<NetworkProjectionDefinition[]>(demo?sampleProjections:[]),[activities,setActivities]=useState<NetworkActivity[]>(demo?sampleActivities:[]),[groups,setGroups]=useState<NetworkGroup[]>(demo?sampleGroups:[]);
 const isAdmin=auth?.membership_role==="owner"||auth?.membership_role==="admin";
 const experience:AlumniExperienceLevel=isAdmin?"admin":auth?"connected":"member";
 const [features,setFeatures]=useState<EffectiveFeatureMap<AlumniFeatureKey>>(()=>featureRuntime.defaultFeatureMap(demo));
 const loadFeatures=async()=>{try{const rows=demo?await fetchPlaygroundFeatures():await fetchEffectivePlatformFeatures();const map=featureRuntime.defaultFeatureMap(false);for(const row of rows){const key=row.feature_key as AlumniFeatureKey;if(map[key])map[key]={key,rollout_state:"rollout_state" in row?row.rollout_state:"released",enabled:row.enabled};}setFeatures(map)}catch{setFeatures(featureRuntime.defaultFeatureMap(demo))}};
 const hasFeature=(key:AlumniFeatureKey)=>featureRuntime.isFeatureAvailable(key,features,experience,isAdmin);
 const load=async()=>{if(demo){setProfiles(sample);setOverview(sampleOverview);setAffiliated(sampleAffiliated);setProjections(sampleProjections);setActivities(sampleActivities);setGroups(sampleGroups);return;}setBusy(true);try{const [directory,summary,linked,entities,projectionRows,activityRows,groupRows]=await Promise.all([fetchAlumniDirectory(query,year,program),fetchAlumniNetworkOverview(),fetchAlumniConnections(),fetchNetworkAffiliatedEntities(),fetchNetworkProjections(),fetchNetworkActivities(),fetchNetworkGroups()]);setProfiles(directory);setOverview(summary);setConnections(linked);setAffiliated(entities);setProjections(projectionRows);setActivities(activityRows);setGroups(groupRows);}catch(e:any){setMessage(e.message||"Could not load Alumni Network.");}finally{setBusy(false)}};
 useEffect(()=>{loadFeatures()},[demo,network.id]);
 useEffect(()=>{load()},[demo,query,year,program,network.id]);
 const allYears=useMemo(()=>Array.from(new Set(profiles.map(p=>p.graduation_year).filter(Boolean) as number[])).sort((a,b)=>b-a),[profiles]);
 const programs=useMemo(()=>Array.from(new Set(profiles.map(p=>p.program).filter(Boolean) as string[])).sort(),[profiles]);
 const me=profiles.find(p=>p.is_me);
 const visibleSurfaces=useMemo(()=>[...composition.primaryNavigation,...composition.mobileMoreNavigation].filter(surface=>{if(surface.adminOnly&&!isAdmin)return false;if(surface.featureKey&&!hasFeature(surface.featureKey as AlumniFeatureKey))return false;return true}),[features,isAdmin,experience]);
 const connectedIds=useMemo(()=>new Set(connections.map(c=>c.related_profile_id)),[connections]);
 const suggestions=useMemo(()=>profiles.filter(p=>!p.is_me).map(p=>({p,score:(me?.graduation_year&&me.graduation_year===p.graduation_year?5:0)+(me?.program&&me.program===p.program?4:0)+(me?.city&&me.city===p.city?2:0)+(me?.company&&me.company===p.company?3:0)})).sort((a,b)=>b.score-a.score||a.p.full_name.localeCompare(b.p.full_name)).slice(0,5),[profiles,me]);
 const duplicateImportRows=useMemo(()=>{const seen=new Set<string>(),dupes=new Set<number>();importRows.forEach((r,i)=>{const key=(r.email||`${r.full_name}|${r.graduation_year||""}|${r.program||""}`).trim().toLowerCase();if(key&&seen.has(key))dupes.add(i);if(key)seen.add(key)});return dupes},[importRows]);
 const places=useMemo(()=>{const counts=new Map<string,number>();for(const e of affiliated)for(const city of e.affiliations.city||[])counts.set(city,(counts.get(city)||0)+1);return [...counts.entries()].sort((a,b)=>b[1]-a[1])},[affiliated]);
 const completeness=Math.round((profiles.filter(p=>p.graduation_year&&p.program&&p.city).length/Math.max(1,profiles.length))*100);
 const navTo=(view:string)=>setTab(view as Tab);
 const connect=async(p:AlumniProfile)=>{if(demo){setMessage("Playground is read-only.");return;}try{await connectAlumniProfile(p.id);setMessage(`Connected with ${p.full_name}.`);await load();}catch(e:any){setMessage(e.message||"Could not connect.")}};
 const invite=async(p:AlumniProfile)=>{try{const token=await createAlumniInvitation(p.id,p.email||undefined);const url=`${window.location.origin}/?alumniInvite=${encodeURIComponent(token)}`;await navigator.clipboard?.writeText(url);setMessage(`Private invitation link copied for ${p.full_name}.`);}catch(e:any){setMessage(e.message||"Could not create invitation.")}};
 const handleFile=async(file:File)=>{const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:"array"});const rows=XLSX.utils.sheet_to_json<any>(wb.Sheets[wb.SheetNames[0]],{defval:""});const normalized:AlumniImportRow[]=rows.map((r:any)=>({full_name:String(r.full_name||r.name||r["Full Name"]||"").trim(),email:String(r.email||r.Email||"").trim(),graduation_year:Number(r.graduation_year||r.year||r["Graduation Year"]||0)||undefined,program:String(r.program||r.Program||"").trim(),department:String(r.department||r.Department||"").trim(),city:String(r.city||r.City||"").trim(),company:String(r.company||r.Company||"").trim(),job_title:String(r.job_title||r["Job Title"]||"").trim()})).filter(r=>r.full_name);setImportRows(normalized);setMessage(`${normalized.length} alumni rows staged. Review before import.`)};
 const commitImport=async()=>{if(duplicateImportRows.size){setMessage("Resolve duplicate rows before importing.");return;}setBusy(true);try{const submission={entities:importRows.map((r,i)=>({clientRef:`row-${i+1}`,displayName:r.full_name,attributes:{email:r.email,graduationYear:r.graduation_year,program:r.program,department:r.department,city:r.city,company:r.company,jobTitle:r.job_title}})),edges:[]};await runtime.construction.submit("alumni-local-import",submission as any);const plan=await runtime.construction.buildCommitPlan("alumni-local-import");if(!plan.validation.valid)throw new Error("Import preview has validation errors.");const result=await runtime.construction.commitAccess("alumni-local-import");setImportRows([]);setMessage(`Imported ${result.createdEntities} new and updated ${result.matchedEntities} existing alumni.`);await load();}catch(e:any){setMessage(e.message||"Import failed.");}finally{setBusy(false)}};
 return <div className="app-shell alumni-shell g7-network-os-shell">
  <NetworkTopbar className="alumni-topbar" icon={<GraduationCap size={18}/>} title={overview.institution_name||network.name} badges={[{label:"Alumni Network",tone:"shared"},{label:"Network OS",tone:"neutral"},...(demo?[{label:"Playground",tone:"demo" as const}]:[])]} middle={!demo?<NetworkSwitcher label="Active network" onSwitched={onNetworkChanged} onCreate={onOpenNetworkLobby?()=>void onOpenNetworkLobby():undefined}/>:undefined} actions={<><button className="icon-btn" title="Guide" onClick={()=>navTo("guide")}><BookOpen size={16}/></button>{!demo&&<button className="icon-btn danger" title="Sign out" onClick={()=>void onSignOut()}><LogOut size={16}/></button>}</>}/>
  <div className="layout alumni-layout"><aside className="sidebar alumni-sidebar"><nav>{visibleSurfaces.map(surface=><button key={surface.viewId} className={`nav-btn ${tab===surface.viewId?"active":""}`} onClick={()=>navTo(surface.viewId)}>{icon(surface.iconToken)}{localizedSurfaceLabel(surface,"en")}</button>)}</nav><div className="alumni-sidebar-note"><Layers3 size={17}/><span><b>One network, many views</b><small>Affiliations can be projected by program, batch, city or company without duplicating people.</small></span></div></aside>
   <main className="content alumni-content">{message&&<div className="notice alumni-notice"><span>{message}</span><button className="text-action" onClick={()=>setMessage("")}>Dismiss</button></div>}
    {tab==="home"&&<div className="alumni-home"><section className="alumni-hero"><div className="alumni-hero-copy"><span className="warm-kicker"><Sparkles size={12}/> Living institutional network</span><h1>{overview.institution_name}</h1><p>Discover people through batch, program, city and career — then keep the network alive through meetups, memories, chapters and trusted connections.</p><div className="hero-actions"><button className="btn primary" onClick={()=>navTo("explorer")}>Explore network <ArrowRight size={15}/></button><button className="btn warm" onClick={()=>navTo("community")}>Community life</button></div></div><div className="alumni-hero-community"><div className="alumni-face-stack">{profiles.slice(0,4).map(p=><InitialsAvatar key={p.id} name={p.full_name}/>)}</div><b>{overview.profile_count} alumni</b><small>{overview.claimed_count} claimed identities</small></div></section>
     <div className="network-metric-grid"><NetworkMetric value={overview.profile_count} label="Alumni" detail="Across the network" icon={<UsersRound/>}/><NetworkMetric value={overview.batch_count} label="Batches" detail="Graduation cohorts" icon={<CalendarDays/>}/><NetworkMetric value={overview.program_count} label="Streams" detail="Programs & courses" icon={<Building2/>}/><NetworkMetric value={`${completeness}%`} label="Profile coverage" detail="Batch + stream + city" icon={<CheckCircle2/>}/></div>
     <div className="alumni-dashboard-grid"><section className="card alumni-panel"><NetworkSectionHead kicker={<><Layers3 size={12}/> Network structure</>} title="Explore beyond a flat directory" description="Switch hierarchy order depending on what you want to discover."/><div className="g7-projection-preview">{projections.slice(0,3).map(p=><button key={p.key} onClick={()=>navTo("explorer")}><Layers3 size={16}/><span><b>{p.label}</b><small>{p.levels.join(" → ")}</small></span><ArrowRight size={14}/></button>)}</div></section><section className="card alumni-panel"><NetworkSectionHead kicker={<><CalendarDays size={12}/> Network life</>} title="What is happening" description="Events, memories and milestones now use a shared network capability."/><div className="alumni-people-list">{activities.slice(0,4).map(a=><button className="alumni-person-row" key={a.id} onClick={()=>navTo("community")}><span className="network-avatar sm">{a.type==="event"?"EV":a.type==="memory"?"ME":"UP"}</span><span><b>{a.title}</b><small>{a.startsAt?new Date(a.startsAt).toLocaleDateString():a.type}</small></span><ArrowRight size={14}/></button>)}</div></section></div>
     <section className="card alumni-privacy-strip"><ShieldCheck/><div><b>Shared mechanics, Alumni semantics</b><span>The platform reuses affiliation, activity, navigation and governance engines. Alumni identity remains separate from Family kinship and persistence.</span></div></section></div>}
    {tab==="explorer"&&<NetworkProjectionExplorer entities={affiliated} projections={projections} onEntityOpen={item=>{const profile=profiles.find(p=>p.id===item.entity.externalRef);if(profile){setQuery(profile.full_name);navTo("directory")}}}/>} 
    {tab==="directory"&&<><NetworkSectionHead kicker={<><UsersRound size={12}/> Discover</>} title="Alumni directory" description="Search people, then narrow by batch or stream."/><section className="card alumni-filter-card"><label className="alumni-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search alumni, company or city…"/></label><select className="select" value={year||""} onChange={e=>setYear(e.target.value?Number(e.target.value):undefined)}><option value="">All batches</option>{allYears.map(y=><option key={y}>{y}</option>)}</select><select className="select" value={program} onChange={e=>setProgram(e.target.value)}><option value="">All streams</option>{programs.map(p=><option key={p}>{p}</option>)}</select>{(query||year||program)&&<button className="btn small" onClick={()=>{setQuery("");setYear(undefined);setProgram("")}}>Clear</button>}</section>{busy?<NetworkEmpty title="Loading alumni…" description="Fetching the active network."/>:profiles.length===0?<NetworkEmpty icon={<Search/>} title="No alumni found" description="Try a broader filter."/>:<div className="alumni-profile-grid">{profiles.map(p=><article className="card alumni-profile-card" key={p.id}><div className="alumni-profile-head"><InitialsAvatar name={p.full_name}/><span className={`claim-state ${p.claimed?"claimed":"open"}`}>{p.claimed?<><CheckCircle2 size={11}/> Claimed</>:"Invite ready"}</span></div><h3>{p.full_name}</h3><p>{p.program||p.department||"Stream not added"}{p.graduation_year?` · ${p.graduation_year}`:""}</p><div className="profile-meta-line">{p.city&&<span><MapPin size={12}/>{p.city}</span>}{p.company&&<span><BriefcaseBusiness size={12}/>{p.company}</span>}</div><small>{p.job_title||"Professional role not added"}</small><div className="card-actions"><button className="btn small" disabled={p.is_me||connectedIds.has(p.id)} onClick={()=>connect(p)}>{connectedIds.has(p.id)?"Connected":p.is_me?"This is you":"Connect"}</button>{isAdmin&&!demo&&!p.claimed&&<button className="btn small" onClick={()=>invite(p)}>Copy invite</button>}</div></article>)}</div>}</>}
    {tab==="community"&&<NetworkActivityHub activities={activities} groups={groups} isAdmin={isAdmin} readOnly={demo} onCreate={async input=>{await createNetworkActivity(input);setMessage("Published to the network.");await load()}} onRsvp={async(id,response)=>{await respondNetworkEvent(id,response);await load()}} onCreateGroup={async input=>{await createNetworkGroup(input);setMessage("Group created.");await load()}} onToggleGroup={async group=>{if(group.myMember)await leaveNetworkGroup(group.id);else await joinNetworkGroup(group.id);await load()}}/>}
    {tab==="places"&&<><NetworkSectionHead kicker={<><MapPin size={12}/> Alumni geography</>} title="Where the network is today" description="A generic location dimension can power alumni geography now and franchise/store or supplier coverage later."/><div className="places-grid">{places.map(([city,count],i)=><button className="card place-card" key={city} onClick={()=>{setQuery(city);navTo("directory")}}><span><MapPin/></span><div><small>#{i+1} location</small><h3>{city}</h3><b>{count} alumni</b></div><ArrowRight size={15}/></button>)}{places.length===0&&<NetworkEmpty icon={<MapPin/>} title="No locations yet" description="Add city information to alumni profiles to build the geography view."/>}</div></>}
    {tab==="connections"&&<div className="alumni-connections-grid"><section className="card alumni-panel"><NetworkSectionHead kicker={<><UserRound size={12}/> My profile</>} title="Keep your network identity current" description="Your affiliations power Explorer, Places and connection suggestions."/>{demo?<div className="notice">Playground is read-only.</div>:<div className="form-grid alumni-profile-form"><label className="field"><span>Full name</span><input className="text-input" value={editing.full_name??me?.full_name??""} onChange={e=>setEditing(x=>({...x,full_name:e.target.value}))}/></label><label className="field"><span>Graduation year</span><input className="text-input" type="number" value={editing.graduation_year??me?.graduation_year??""} onChange={e=>setEditing(x=>({...x,graduation_year:Number(e.target.value)||undefined}))}/></label><label className="field"><span>Program / school</span><input className="text-input" value={editing.department??me?.department??""} onChange={e=>setEditing(x=>({...x,department:e.target.value}))}/></label><label className="field"><span>Stream / course</span><input className="text-input" value={editing.program??me?.program??""} onChange={e=>setEditing(x=>({...x,program:e.target.value}))}/></label><label className="field"><span>City</span><input className="text-input" value={editing.city??me?.city??""} onChange={e=>setEditing(x=>({...x,city:e.target.value}))}/></label><label className="field"><span>Company</span><input className="text-input" value={editing.company??me?.company??""} onChange={e=>setEditing(x=>({...x,company:e.target.value}))}/></label><button className="btn primary" disabled={busy||!(editing.full_name||me?.full_name)} onClick={async()=>{setBusy(true);try{await saveMyAlumniProfile({...me,...editing,full_name:String(editing.full_name||me?.full_name||"")});setEditing({});setMessage("Profile updated; network affiliations refreshed automatically.");await load();}catch(e:any){setMessage(e.message||"Could not update profile.")}finally{setBusy(false)}}}>Save profile</button></div>}</section><section className="card alumni-panel"><NetworkSectionHead kicker={<><HeartHandshake size={12}/> Trusted connections</>} title="People you may know" description="Suggested from shared batch, stream, city or professional context."/><div className="alumni-people-list">{suggestions.map(({p})=><div className="alumni-person-row static" key={p.id}><InitialsAvatar name={p.full_name} size="sm"/><span><b>{p.full_name}</b><small>{connectionReason(me,p)}</small></span><button className="btn small" disabled={connectedIds.has(p.id)} onClick={()=>connect(p)}>{connectedIds.has(p.id)?"Connected":"Connect"}</button></div>)}</div></section></div>}
    {tab==="admin"&&isAdmin&&!demo&&<><NetworkSectionHead kicker={<><ShieldCheck size={12}/> Alumni Admin</>} title="Grow the network safely" description="Import Alumni data; G7 automatically projects program, batch, stream, city and company affiliations."/><section className="card alumni-admin-upload"><div className="alumni-upload-icon"><FileSpreadsheet/></div><div><h3>Import Excel or CSV</h3><p>Columns: Full Name, Email, Graduation Year, Program, Department, City, Company and Job Title.</p></div><label className="btn primary"><FileSpreadsheet size={16}/> Choose file<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&handleFile(e.target.files[0])}/></label></section>{importRows.length>0&&<section className="card alumni-import-preview"><NetworkSectionHead title={`Import preview · ${importRows.length} rows`} description={duplicateImportRows.size?`${duplicateImportRows.size} duplicate rows detected.`:"No duplicate rows detected in this file."}/><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Year</th><th>Program</th><th>Stream</th><th>City</th></tr></thead><tbody>{importRows.slice(0,50).map((r,i)=><tr key={i} className={duplicateImportRows.has(i)?"duplicate-row":""}><td>{r.full_name}</td><td>{r.email||"—"}</td><td>{r.graduation_year||"—"}</td><td>{r.department||"—"}</td><td>{r.program||"—"}</td><td>{r.city||"—"}</td></tr>)}</tbody></table></div><div className="form-actions"><button className="btn" onClick={()=>setImportRows([])}>Discard</button><button className="btn primary" disabled={busy||duplicateImportRows.size>0} onClick={commitImport}>Confirm import</button></div></section>}</>}
    {tab==="guide"&&<><NetworkSectionHead kicker={<><BookOpen size={12}/> Alumni Guide</>} title="Understand the living network" description="G7 keeps the experience simple while the platform underneath becomes much more reusable."/><div className="alumni-guide-grid">{[["1","Add or import alumni","Start with clean identity and affiliation data."],["2","Explore different structures","Switch Program → Batch and Batch → Program without duplicating anyone."],["3","Bring the network alive","Use reunions, RSVP, memories, milestones and chapters."],["4","Discover useful people","Search by cohort, city or company and build trusted connections."]].map(([n,title,body])=><article className="card alumni-guide-card" key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div><section className="card alumni-guide-privacy"><LockKeyhole/><div><h3>Privacy stays vertical and tenant aware</h3><p>Generic affiliation/activity engines never remove Alumni identity controls or network isolation. Family kinship stays Family-owned.</p></div></section></>}
   </main></div>
  <nav className="mobile-bottom-nav alumni-mobile-nav">{visibleSurfaces.filter(s=>composition.mobileBottomViewIds.includes(s.viewId)).map(surface=><button key={surface.viewId} className={tab===surface.viewId?"active":""} onClick={()=>navTo(surface.viewId)}>{icon(surface.iconToken,18)}<span>{localizedSurfaceLabel(surface,"en")}</span></button>)}<button className={!["home","explorer","directory","community"].includes(tab)?"active":""} onClick={()=>navTo("guide")}><BookOpen size={18}/><span>More</span></button></nav>
 </div>;
}
