"use client";
import {useEffect,useMemo,useState} from "react";
import * as XLSX from "xlsx";
import {BookOpen,Building2,CalendarDays,FileSpreadsheet,GraduationCap,LogOut,Search,ShieldCheck,UsersRound} from "lucide-react";
import {getVerticalCapabilityRuntime} from "../app-shell/vertical-capabilities";
import {fetchAlumniDirectory,saveMyAlumniProfile,createAlumniInvitation,type AlumniProfile,type AlumniImportRow} from "../verticals/alumni/data/remote";
import type {NetworkSettings} from "../lib/network";
import type {AuthUser} from "../lib/auth";

type Tab="home"|"directory"|"cohorts"|"connections"|"admin"|"guide";
const runtime=getVerticalCapabilityRuntime("alumni");
const sample:AlumniProfile[]=[
 {id:"a1",full_name:"Aditi Deshmukh",graduation_year:2008,program:"Computer Engineering",department:"Engineering",city:"Pune",company:"CloudWorks",job_title:"Engineering Director",visibility:"members",claimed:true,is_me:false},
 {id:"a2",full_name:"Rahul Mehta",graduation_year:2008,program:"Computer Engineering",department:"Engineering",city:"Bengaluru",company:"FinScale",job_title:"Principal Engineer",visibility:"members",claimed:true,is_me:false},
 {id:"a3",full_name:"Neha Kulkarni",graduation_year:2012,program:"MBA",department:"Management",city:"Mumbai",company:"Growth Labs",job_title:"Founder",visibility:"members",claimed:false,is_me:false},
 {id:"a4",full_name:"Sameer Shah",graduation_year:2015,program:"Mechanical Engineering",department:"Engineering",city:"Pune",company:"MobilityX",job_title:"Product Lead",visibility:"members",claimed:false,is_me:false},
];

export default function AlumniNetworkApp({network,auth,demo=false,onSwitchNetwork,onSignOut}:{network:NetworkSettings;auth:AuthUser|null;demo?:boolean;onSwitchNetwork:()=>Promise<void>|void;onSignOut:()=>Promise<void>|void}){
 const [tab,setTab]=useState<Tab>("home"),[profiles,setProfiles]=useState<AlumniProfile[]>(demo?sample:[]),[query,setQuery]=useState(""),[year,setYear]=useState<number|undefined>(),[program,setProgram]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [editing,setEditing]=useState<Partial<AlumniProfile>>({full_name:""}),[importRows,setImportRows]=useState<AlumniImportRow[]>([]);
 const isAdmin=auth?.membership_role==="owner"||auth?.membership_role==="admin";
 const load=async()=>{if(demo)return;setBusy(true);try{setProfiles(await fetchAlumniDirectory(query,year,program));}catch(e:any){setMessage(e.message||"Could not load alumni directory.");}finally{setBusy(false)}};
 useEffect(()=>{load()},[demo,query,year,program]);
 const years=useMemo(()=>Array.from(new Set(profiles.map(p=>p.graduation_year).filter(Boolean) as number[])).sort((a,b)=>b-a),[profiles]);
 const programs=useMemo(()=>Array.from(new Set(profiles.map(p=>p.program).filter(Boolean) as string[])).sort(),[profiles]);
 const me=profiles.find(p=>p.is_me);
 const handleFile=async(file:File)=>{const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:"array"});const rows=XLSX.utils.sheet_to_json<any>(wb.Sheets[wb.SheetNames[0]],{defval:""});const normalized:AlumniImportRow[]=rows.map((r:any)=>({full_name:String(r.full_name||r.name||r["Full Name"]||"").trim(),email:String(r.email||r.Email||"").trim(),graduation_year:Number(r.graduation_year||r.year||r["Graduation Year"]||0)||undefined,program:String(r.program||r.Program||"").trim(),department:String(r.department||r.Department||"").trim(),city:String(r.city||r.City||"").trim(),company:String(r.company||r.Company||"").trim(),job_title:String(r.job_title||r["Job Title"]||"").trim()})).filter((r:any)=>r.full_name);setImportRows(normalized);setMessage(`${normalized.length} alumni rows staged. Review the preview before import.`)};
 const commitImport=async()=>{setBusy(true);try{const submission={entities:importRows.map((r,i)=>({clientRef:`row-${i+1}`,displayName:r.full_name,attributes:{email:r.email,graduationYear:r.graduation_year,program:r.program,department:r.department,city:r.city,company:r.company,jobTitle:r.job_title}})),edges:[]};await runtime.construction.submit("alumni-local-import",submission as any);const plan=await runtime.construction.buildCommitPlan("alumni-local-import");if(!plan.validation.valid)throw new Error("Import preview has validation errors.");const result=await runtime.construction.commitAccess("alumni-local-import");setImportRows([]);setMessage(`Imported ${result.createdEntities} new and updated ${result.matchedEntities} existing alumni.`);await load();}catch(e:any){setMessage(e.message||"Import failed.");}finally{setBusy(false)}};
 const invite=async(p:AlumniProfile)=>{try{const token=await createAlumniInvitation(p.id,p.email||undefined);const url=`${window.location.origin}/?alumniInvite=${encodeURIComponent(token)}`;await navigator.clipboard?.writeText(url);setMessage(`Invitation link copied for ${p.full_name}.`);}catch(e:any){setMessage(e.message||"Could not create invitation.")}};
 return <div className="app-shell alumni-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark"><GraduationCap size={20}/></span><span>{network.name}</span><span className="mode-pill shared">Alumni Network</span>{demo&&<span className="mode-pill demo">Playground</span>}</div><div className="top-actions"><button className="btn small" onClick={()=>onSwitchNetwork()}>Switch network</button><button className="btn small" onClick={()=>onSignOut()}><LogOut size={14}/> Sign out</button></div></header>
  <nav className="tabs alumni-tabs">{([['home','Home'],['directory','Directory'],['cohorts','Cohorts'],['connections','Connections'],['guide','Guide'],...(isAdmin&&!demo?[["admin","Admin"]]:[])] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  <main className="content alumni-content">
   {message&&<div className="notice">{message}</div>}
   {tab==="home"&&<><section className="hero-card"><span className="warm-kicker"><GraduationCap size={14}/> Alumni Network V1</span><h1>Reconnect through your institution, batch and journey.</h1><p>Find classmates and seniors, keep your alumni profile current, and help the network grow without mixing Alumni data with Family relationships.</p><div className="stats-grid"><div className="stat-card"><b>{profiles.length}</b><span>Alumni</span></div><div className="stat-card"><b>{years.length}</b><span>Batches</span></div><div className="stat-card"><b>{programs.length}</b><span>Programs</span></div><div className="stat-card"><b>{profiles.filter(p=>p.claimed).length}</b><span>Claimed</span></div></div></section>{me&&<section className="card"><h3>Your alumni identity</h3><p><b>{me.full_name}</b> · {me.program||"Program not added"} · {me.graduation_year||"Year not added"}</p><button className="btn" onClick={()=>{setEditing(me);setTab("connections")}}>Update my profile</button></section>}</>}
   {tab==="directory"&&<><section className="card"><div className="section-heading"><div><h2>Alumni directory</h2><p>Search by name, city or company. Filter by graduating year and program.</p></div></div><div className="filter-row"><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search alumni…"/></label><select value={year||""} onChange={e=>setYear(e.target.value?Number(e.target.value):undefined)}><option value="">All years</option>{years.map(y=><option key={y}>{y}</option>)}</select><select value={program} onChange={e=>setProgram(e.target.value)}><option value="">All programs</option>{programs.map(p=><option key={p}>{p}</option>)}</select></div></section><div className="card-grid">{profiles.map(p=><article className="card" key={p.id}><span className="warm-kicker">{p.graduation_year||"Year not added"}</span><h3>{p.full_name}</h3><p>{p.program||p.department||"Program not added"}</p><small>{[p.city,p.company,p.job_title].filter(Boolean).join(" · ")}</small>{isAdmin&&!demo&&<div className="card-actions"><button className="btn small" onClick={()=>invite(p)}>Invite</button></div>}</article>)}</div></>}
   {tab==="cohorts"&&<><section className="card"><h2>Batches & programs</h2><p>A lightweight view of where your alumni network is strongest today.</p></section><div className="card-grid">{years.map(y=><article className="card" key={y}><CalendarDays/><h3>Class of {y}</h3><p>{profiles.filter(p=>p.graduation_year===y).length} alumni</p><button className="btn small" onClick={()=>{setYear(y);setTab("directory")}}>View cohort</button></article>)}{programs.map(p=><article className="card" key={p}><Building2/><h3>{p}</h3><p>{profiles.filter(x=>x.program===p).length} alumni</p><button className="btn small" onClick={()=>{setProgram(p);setTab("directory")}}>View program</button></article>)}</div></>}
   {tab==="connections"&&<section className="card"><h2>My alumni profile</h2><p>Keep your institutional and professional identity current. Your email is not shown to ordinary members.</p>{demo?<div className="notice">Playground is read-only.</div>:<div className="form-grid"><label>Full name<input className="text-input" value={editing.full_name||me?.full_name||""} onChange={e=>setEditing(x=>({...x,full_name:e.target.value}))}/></label><label>Graduation year<input className="text-input" type="number" value={editing.graduation_year||me?.graduation_year||""} onChange={e=>setEditing(x=>({...x,graduation_year:Number(e.target.value)||undefined}))}/></label><label>Program<input className="text-input" value={editing.program||me?.program||""} onChange={e=>setEditing(x=>({...x,program:e.target.value}))}/></label><label>Department<input className="text-input" value={editing.department||me?.department||""} onChange={e=>setEditing(x=>({...x,department:e.target.value}))}/></label><label>City<input className="text-input" value={editing.city||me?.city||""} onChange={e=>setEditing(x=>({...x,city:e.target.value}))}/></label><label>Company<input className="text-input" value={editing.company||me?.company||""} onChange={e=>setEditing(x=>({...x,company:e.target.value}))}/></label><label>Role<input className="text-input" value={editing.job_title||me?.job_title||""} onChange={e=>setEditing(x=>({...x,job_title:e.target.value}))}/></label><button className="btn primary" disabled={busy||!(editing.full_name||me?.full_name)} onClick={async()=>{setBusy(true);try{await saveMyAlumniProfile({...me,...editing,full_name:String(editing.full_name||me?.full_name||"")});setMessage("Your alumni profile is updated.");setEditing({});await load();}catch(e:any){setMessage(e.message||"Could not update profile.")}finally{setBusy(false)}}}>Save profile</button></div>}</section>}
   {tab==="admin"&&isAdmin&&!demo&&<><section className="card"><span className="warm-kicker"><ShieldCheck size={14}/> Alumni Admin</span><h2>Grow the network safely</h2><p>Import Excel/CSV, review staged rows, then commit. Matching email addresses update existing profiles instead of creating duplicates.</p><label className="btn"><FileSpreadsheet size={16}/> Choose Excel / CSV<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&handleFile(e.target.files[0])}/></label></section>{importRows.length>0&&<section className="card"><h3>Import preview · {importRows.length} rows</h3><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Year</th><th>Program</th><th>City</th></tr></thead><tbody>{importRows.slice(0,50).map((r,i)=><tr key={i}><td>{r.full_name}</td><td>{r.email}</td><td>{r.graduation_year}</td><td>{r.program}</td><td>{r.city}</td></tr>)}</tbody></table></div><button className="btn primary" disabled={busy} onClick={commitImport}>Confirm import</button></section>}</>}
   {tab==="guide"&&<section className="card"><span className="warm-kicker"><BookOpen size={14}/> Alumni Guide</span><h2>Start in four steps</h2><ol><li>Create the Alumni Network for one institution/community.</li><li>Add or import alumni with full name, email, graduation year and program.</li><li>Invite alumni or let matching verified emails claim existing profiles.</li><li>Use Directory and Cohorts to discover classmates, seniors and professional connections.</li></ol><div className="notice"><b>Privacy:</b> ordinary alumni never receive directory email addresses. Alumni data is stored separately from Family members and relationships.</div></section>}
  </main>
 </div>;
}
