"use client";
import {useEffect,useState} from 'react';
import {Bell,Heart,ImagePlus,Check,Trash2,Search} from 'lucide-react';
import {Memory,Member,Notification} from '../lib/types';
import {getNetworkRepository} from '../lib/repository';
import {uploadCommunityPhoto} from '../lib/storage';
import {isSupabaseConfigured} from '../lib/supabase';

export default function CommunityHub({members,auth,onSelect,onNotify}:{members:Member[];auth:any;onSelect:(m:Member)=>void;onNotify:(x:string)=>void}){
 const repo=getNetworkRepository();
 const [memories,setMemories]=useState<Memory[]>([]),[notifications,setNotifications]=useState<Notification[]>([]),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const [form,setForm]=useState({member_id:auth?.member_id||'',title:'',story:'',visibility:'member' as const,photo_url:''});
 const load=async()=>{try{setMemories(await repo.fetchMemories());setNotifications(await repo.fetchNotifications())}catch(e:any){onNotify(e.message||'Could not load community updates.')}};
 useEffect(()=>{load()},[]);
 const create=async()=>{if(!form.title.trim())return;setBusy(true);try{let photo=form.photo_url;if((document.getElementById('community-photo') as HTMLInputElement)?.files?.[0]) photo=await uploadCommunityPhoto((document.getElementById('community-photo') as HTMLInputElement).files![0],auth?.id||'anonymous');await repo.createMemory({member_id:form.member_id||undefined,title:form.title.trim(),story:form.story||undefined,photo_url:photo||undefined,visibility:form.visibility});setForm({member_id:auth?.member_id||'',title:'',story:'',visibility:'member',photo_url:''});setShowForm(false);await load();onNotify('Memory shared with the community.')}catch(e:any){onNotify(e.message||'Could not create memory.')}finally{setBusy(false)}};
 const mark=async(n:Notification)=>{try{await repo.markNotificationRead(n.id);setNotifications(x=>x.map(v=>v.id===n.id?{...v,read_at:new Date().toISOString()}:v))}catch(e:any){onNotify(e.message||'Could not update notification.')}};
 const remove=async(id:string)=>{try{await repo.deleteMemory(id);setMemories(x=>x.filter(m=>m.id!==id));onNotify('Memory removed.')}catch(e:any){onNotify(e.message||'Could not remove memory.')}};
 const visible=memories.filter(m=>{const q=query.toLowerCase();if(!q)return true;const owner=m.member_id?members.find(x=>x.id===m.member_id):undefined;return `${m.title} ${m.story||''} ${owner?.full_name||''}`.toLowerCase().includes(q)});
 return <section><div className="page-head"><div><h1 className="page-title">Community</h1><p className="page-subtitle">Memories, stories and updates from the hierarchy.</p></div><div className="card-actions"><button className="btn primary" onClick={()=>setShowForm(true)}><Heart size={15}/> Share a Memory</button></div></div>
  <div className="community-grid">
   <div className="card community-main"><div className="profile-section-head"><div><h3 style={{margin:0}}>Community Memories</h3><p className="page-subtitle">Share a family moment, story or photo. Keep it simple and personal.</p></div></div><div className="search-bar" style={{marginTop:12}}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search memories…"/></div>{visible.length===0&&<div className="empty">No memories yet. Be the first to share one.</div>}<div className="memory-grid">{visible.map(m=>{const owner=m.member_id?members.find(x=>x.id===m.member_id):undefined;return <article className="memory-card" key={m.id}>{m.photo_url&&<img src={m.photo_url} alt=""/>}<div className="memory-body"><div className="memory-title">{m.title}</div>{m.story&&<div className="memory-story">{m.story}</div>}<div className="person-meta">{owner?<>About {owner.full_name} · </>:''}{new Date(m.created_at).toLocaleDateString()}</div>{(m.created_by===auth?.id||auth?.role==='admin')&&<button className="btn tiny danger" onClick={()=>remove(m.id)}><Trash2 size={12}/> Remove</button>}</div></article>})}</div></div>
   <div className="card community-side"><div className="profile-section-head"><div><h3 style={{margin:0}}>Updates</h3><p className="page-subtitle">Approvals and account activity.</p></div><Bell size={18}/></div>{notifications.length===0&&<div className="empty">No new updates.</div>}{notifications.map(n=><button key={n.id} className={`notification-row ${n.read_at?'read':''}`} onClick={()=>mark(n)}><span className="notification-dot">{n.read_at?<Check size={11}/>:''}</span><span><strong>{n.title}</strong><small>{n.body||''}</small><em>{new Date(n.created_at).toLocaleString()}</em></span></button>)}</div>
  </div>
  {showForm&&<div className="modal-overlay"><div className="modal" style={{maxWidth:600}}><div className="drawer-head"><h2 style={{margin:0}}>Share a Memory</h2><button className="btn small" onClick={()=>setShowForm(false)}>Close</button></div><p className="page-subtitle">A photo and a few words are enough. You can attach the memory to your own profile or, as an administrator, to another member.</p><div className="form-grid"><div className="field full"><label>About member</label><select className="select" value={form.member_id} onChange={e=>setForm({...form,member_id:e.target.value})} disabled={auth?.role!=='admin'}><option value="">Community memory</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></div><div className="field full"><label>Title</label><input className="text-input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Family reunion in Pune"/></div><div className="field full"><label>Story</label><textarea className="text-input" rows={5} value={form.story} onChange={e=>setForm({...form,story:e.target.value})} placeholder="What should the family remember?"/></div><div className="field"><label>Photo</label><input id="community-photo" className="text-input" type="file" accept="image/jpeg,image/png,image/webp" disabled={!isSupabaseConfigured}/></div><div className="field"><label>Visibility</label><select className="select" value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value as any})}><option value="public">Public</option><option value="member">Members</option>{auth?.role==='admin'&&<option value="admin">Admins</option>}</select></div></div><div className="form-actions"><button className="btn" onClick={()=>setShowForm(false)}>Cancel</button><button className="btn primary" disabled={busy||!form.title.trim()} onClick={create}>{busy?'Saving…':'Share Memory'}</button></div></div></div>}
 </section>
}
