"use client";
import {useEffect,useState} from 'react';
import {Bell,Heart,ImagePlus,Check,Trash2,Search} from 'lucide-react';
import {Memory,Member,Notification} from '../lib/types';
import {getNetworkRepository} from '../lib/repository';
import {uploadCommunityPhoto} from '../lib/storage';
import {isSupabaseConfigured} from '../lib/supabase';
import {useLanguage} from '../lib/i18n';

export default function CommunityHub({members,auth,onSelect,onNotify}:{members:Member[];auth:any;onSelect:(m:Member)=>void;onNotify:(x:string)=>void}){
 const {language}=useLanguage();
 const c=language==='hi'?{title:'परिवार की यादें',subtitle:'परिवार की तस्वीरें, कहानियाँ और नए पल।',share:'याद साझा करें',memories:'कहानियाँ और तस्वीरें',memoryHelp:'एक पारिवारिक पल, कहानी या तस्वीर साझा करें।',search:'यादों में खोजें…',empty:'अभी कोई याद नहीं। पहली याद आप साझा करें।',updates:'नई जानकारी',updatesHelp:'स्वीकृतियाँ और account गतिविधि।',noUpdates:'कोई नई जानकारी नहीं।',close:'बंद करें',about:'किस सदस्य के बारे में',familyMemory:'पूरे परिवार की याद',memoryTitle:'शीर्षक',story:'कहानी',photo:'तस्वीर',visibility:'कौन देख सकता है',cancel:'रद्द करें',save:'याद साझा करें',saving:'सहेज रहे हैं…'}:language==='mr'?{title:'कुटुंबाच्या आठवणी',subtitle:'कौटुंबिक छायाचित्रे, कथा आणि नवीन क्षण.',share:'आठवण सामायिक करा',memories:'कथा आणि छायाचित्रे',memoryHelp:'एक कौटुंबिक क्षण, कथा किंवा छायाचित्र सामायिक करा.',search:'आठवणींमध्ये शोधा…',empty:'अजून आठवणी नाहीत. पहिली आठवण आपण सामायिक करा.',updates:'नवीन माहिती',updatesHelp:'मंजुरी आणि account हालचाल.',noUpdates:'नवीन माहिती नाही.',close:'बंद करा',about:'कोणत्या सदस्याबद्दल',familyMemory:'संपूर्ण कुटुंबाची आठवण',memoryTitle:'शीर्षक',story:'कथा',photo:'छायाचित्र',visibility:'कोण पाहू शकते',cancel:'रद्द करा',save:'आठवण सामायिक करा',saving:'जतन करत आहोत…'}:{title:'Family memories',subtitle:'Photos, stories and new moments from your family.',share:'Share a memory',memories:'Stories and photos',memoryHelp:'Share a family moment, story or photo. Keep it simple and personal.',search:'Search memories…',empty:'No memories yet. Be the first to share one.',updates:'Updates',updatesHelp:'Approvals and account activity.',noUpdates:'No new updates.',close:'Close',about:'About member',familyMemory:'Whole-family memory',memoryTitle:'Title',story:'Story',photo:'Photo',visibility:'Who can see this',cancel:'Cancel',save:'Share memory',saving:'Saving…'};
 const repo=getNetworkRepository();
 const [memories,setMemories]=useState<Memory[]>([]),[notifications,setNotifications]=useState<Notification[]>([]),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const [form,setForm]=useState({member_id:auth?.member_id||'',title:'',story:'',visibility:'member' as const,photo_url:''});
 const load=async()=>{try{setMemories(await repo.fetchMemories());setNotifications(await repo.fetchNotifications())}catch(e:any){onNotify(e.message||'Could not load community updates.')}};
 useEffect(()=>{load()},[]);
 const create=async()=>{if(!form.title.trim())return;setBusy(true);try{let photo=form.photo_url;if((document.getElementById('community-photo') as HTMLInputElement)?.files?.[0]) photo=await uploadCommunityPhoto((document.getElementById('community-photo') as HTMLInputElement).files![0],auth?.id||'anonymous');await repo.createMemory({member_id:form.member_id||undefined,title:form.title.trim(),story:form.story||undefined,photo_url:photo||undefined,visibility:form.visibility});setForm({member_id:auth?.member_id||'',title:'',story:'',visibility:'member',photo_url:''});setShowForm(false);await load();onNotify('Memory shared with the community.')}catch(e:any){onNotify(e.message||'Could not create memory.')}finally{setBusy(false)}};
 const mark=async(n:Notification)=>{try{await repo.markNotificationRead(n.id);setNotifications(x=>x.map(v=>v.id===n.id?{...v,read_at:new Date().toISOString()}:v))}catch(e:any){onNotify(e.message||'Could not update notification.')}};
 const remove=async(id:string)=>{try{await repo.deleteMemory(id);setMemories(x=>x.filter(m=>m.id!==id));onNotify('Memory removed.')}catch(e:any){onNotify(e.message||'Could not remove memory.')}};
 const visible=memories.filter(m=>{const q=query.toLowerCase();if(!q)return true;const owner=m.member_id?members.find(x=>x.id===m.member_id):undefined;return `${m.title} ${m.story||''} ${owner?.full_name||''}`.toLowerCase().includes(q)});
 return <section><div className="page-head"><div><h1 className="page-title">{c.title}</h1><p className="page-subtitle">{c.subtitle}</p></div><div className="card-actions"><button className="btn primary" onClick={()=>setShowForm(true)}><Heart size={15}/> {c.share}</button></div></div>
  <div className="community-grid">
   <div className="card community-main"><div className="profile-section-head"><div><h3 style={{margin:0}}>{c.memories}</h3><p className="page-subtitle">{c.memoryHelp}</p></div></div><div className="search-bar" style={{marginTop:12}}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.search}/></div>{visible.length===0&&<div className="empty">{c.empty}</div>}<div className="memory-grid">{visible.map(m=>{const owner=m.member_id?members.find(x=>x.id===m.member_id):undefined;return <article className="memory-card" key={m.id}>{m.photo_url&&<img src={m.photo_url} alt=""/>}<div className="memory-body"><div className="memory-title">{m.title}</div>{m.story&&<div className="memory-story">{m.story}</div>}<div className="person-meta">{owner?<>{owner.full_name} · </>:''}{new Date(m.created_at).toLocaleDateString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN')}</div>{(m.created_by===auth?.id||auth?.role==='admin')&&<button className="btn tiny danger" onClick={()=>remove(m.id)}><Trash2 size={12}/></button>}</div></article>})}</div></div>
   <div className="card community-side"><div className="profile-section-head"><div><h3 style={{margin:0}}>{c.updates}</h3><p className="page-subtitle">{c.updatesHelp}</p></div><Bell size={18}/></div>{notifications.length===0&&<div className="empty">{c.noUpdates}</div>}{notifications.map(n=><button key={n.id} className={`notification-row ${n.read_at?'read':''}`} onClick={()=>mark(n)}><span className="notification-dot">{n.read_at?<Check size={11}/>:''}</span><span><strong>{n.title}</strong><small>{n.body||''}</small><em>{new Date(n.created_at).toLocaleString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN')}</em></span></button>)}</div>
  </div>
  {showForm&&<div className="modal-overlay"><div className="modal" role="dialog" aria-modal="true" style={{maxWidth:600}}><div className="drawer-head"><h2 style={{margin:0}}>{c.share}</h2><button className="btn small" onClick={()=>setShowForm(false)}>{c.close}</button></div><p className="page-subtitle">{c.memoryHelp}</p><div className="form-grid"><div className="field full"><label>{c.about}</label><select className="select" value={form.member_id} onChange={e=>setForm({...form,member_id:e.target.value})} disabled={auth?.role!=='admin'}><option value="">{c.familyMemory}</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></div><div className="field full"><label>{c.memoryTitle}</label><input className="text-input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="field full"><label>{c.story}</label><textarea className="text-input" rows={5} value={form.story} onChange={e=>setForm({...form,story:e.target.value})}/></div><div className="field"><label>{c.photo}</label><input id="community-photo" className="text-input" type="file" accept="image/jpeg,image/png,image/webp" disabled={!isSupabaseConfigured}/></div><div className="field"><label>{c.visibility}</label><select className="select" value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value as any})}><option value="public">Public</option><option value="member">Members</option>{auth?.role==='admin'&&<option value="admin">Admins</option>}</select></div></div><div className="form-actions"><button className="btn" onClick={()=>setShowForm(false)}>{c.cancel}</button><button className="btn primary" disabled={busy||!form.title.trim()} onClick={create}>{busy?c.saving:c.save}</button></div></div></div>}
 </section>
}
