"use client";
import {useEffect,useMemo,useState} from "react";
import {Cake,CalendarHeart,Heart,Image,Plus,Sparkles,Users,History,Share2} from "lucide-react";
import {LifeEvent,Member,Memory} from "../lib/types";
import {getNetworkRepository} from "../lib/repository";
import {useLanguage} from "../lib/i18n";

export default function FamilyHome({members,events,memories:providedMemories,networkName,viewerMemberId,onSelect,onGo,onAddRelative,showMemories=true,showSpecialDays=true,showContributions=true,showSharing=true,canAddRelative=true,simple=false}:{members:Member[];events:LifeEvent[];memories?:Memory[];networkName?:string;viewerMemberId?:string;onSelect:(m:Member)=>void;onGo:(v:"community"|"participation"|"tree")=>void;onAddRelative:()=>void;showMemories?:boolean;showSpecialDays?:boolean;showContributions?:boolean;showSharing?:boolean;canAddRelative?:boolean;simple?:boolean}){
 const {language}=useLanguage(); const repo=getNetworkRepository(); const [memories,setMemories]=useState<Memory[]>(providedMemories||[]);
 useEffect(()=>{if(providedMemories){setMemories(providedMemories);return;}repo.fetchMemories().then(setMemories).catch(()=>setMemories([]))},[providedMemories]);
 const c=language==='hi'?{k:'आपका परिवार, साथ',hello:'आज परिवार में क्या नया है',sub:'यादें सँजोएँ, खास दिन याद रखें और एक-दूसरे से जुड़े रहें।',memory:'एक याद साझा करें',relative:'रिश्तेदार जोड़ें',moments:'हाल की यादें',see:'सभी यादें',coming:'आने वाले खास दिन',contribute:'आज का छोटा योगदान',help:'परिवार की जानकारी पूरी करने में एक मिनट मदद करें',start:'अभी मदद करें',empty:'पहली पारिवारिक याद साझा करें—एक तस्वीर और दो पंक्तियाँ काफी हैं।',birthday:'जन्मदिन',onThisDay:'आज के दिन',yearsAgo:'साल पहले'}:language==='mr'?{k:'आपले कुटुंब, एकत्र',hello:'आज कुटुंबात काय नवीन आहे',sub:'आठवणी जपा, खास दिवस लक्षात ठेवा आणि एकमेकांशी जोडलेले रहा.',memory:'आठवण सामायिक करा',relative:'नातेवाईक जोडा',moments:'अलीकडच्या आठवणी',see:'सर्व आठवणी',coming:'लवकरच खास दिवस',contribute:'आजचे छोटे योगदान',help:'कुटुंबाची माहिती पूर्ण करण्यासाठी एक मिनिट मदत करा',start:'आता मदत करा',empty:'पहिली कौटुंबिक आठवण सामायिक करा—एक फोटो आणि दोन ओळी पुरेशा आहेत.',birthday:'वाढदिवस',onThisDay:'आजच्या दिवशी',yearsAgo:'वर्षांपूर्वी'}:{k:'Your family, together',hello:'What’s happening in the family',sub:'Remember the stories, celebrate the moments and stay close across generations.',memory:'Share a memory',relative:'Add a relative',moments:'Recently shared',see:'See all memories',coming:'Special days coming up',contribute:'One small thing today',help:'Help make your family network a little more complete. It takes about a minute.',start:'Help the family',empty:'Share the first family memory—a photo and two lines are enough.',birthday:'Birthday',onThisDay:'On this day',yearsAgo:'years ago'};
 const upcoming=useMemo(()=>{const now=new Date();now.setHours(0,0,0,0);const next=(raw:string)=>{const d=new Date(raw+'T00:00:00');let n=new Date(now.getFullYear(),d.getMonth(),d.getDate());if(n<now)n.setFullYear(n.getFullYear()+1);return {n,days:Math.round((n.getTime()-now.getTime())/86400000)}};const birthdays=members.filter(m=>!m.date_of_death&&m.date_of_birth).map(m=>({...next(m.date_of_birth!),m,label:c.birthday}));const anniversaries=events.filter(e=>e.event_type==='marriage'&&e.event_date).map(e=>{const m=members.find(x=>x.id===e.member_id);return m?({...next(e.event_date!),m,label:language==='hi'?'वर्षगांठ':language==='mr'?'लग्नाचा वाढदिवस':'Anniversary'}):null}).filter(Boolean) as {m:Member;n:Date;days:number;label:string}[];return [...birthdays,...anniversaries].filter(x=>x.days<=45).sort((a,b)=>a.days-b.days).slice(0,5)},[members,events,language]);
 const onThisDay=useMemo(()=>{const now=new Date();return events.filter(e=>e.event_date).map(e=>({e,d:new Date(e.event_date+'T00:00:00')})).filter(x=>x.d.getMonth()===now.getMonth()&&x.d.getDate()===now.getDate()&&x.d.getFullYear()<now.getFullYear()).sort((a,b)=>a.d.getFullYear()-b.d.getFullYear()).slice(0,3)},[events]);
 const heroMembers=useMemo(()=>viewerMemberId?[...members].sort((a,b)=>a.id===viewerMemberId?-1:b.id===viewerMemberId?1:0):members,[members,viewerMemberId]);
 const viewer=viewerMemberId?members.find(m=>m.id===viewerMemberId):undefined;
 const recent=memories.slice(0,4); const incomplete=members.find(m=>!m.photo_url||!m.city||!m.date_of_birth);
 const pulse={stories:memories.length,coming:upcoming.length,needsHelp:members.filter(m=>!m.city||!m.date_of_birth||!m.bio).length};
 const shareDay=async(name:string,date:Date,label:string)=>{const text=`🎉 ${name}'s ${label} is ${date.toLocaleDateString('en-IN',{day:'numeric',month:'long'})}. Sending love from our family ❤️`;try{if(navigator.share)await navigator.share({title:`${name} · ${label}`,text});else await navigator.clipboard?.writeText(text)}catch{}};
 return <section className={`family-home ${simple?"simple-family-home":""}`}>
  <div className="family-home-hero"><div><span className="warm-kicker">{c.k}</span><h1>{networkName||c.hello}</h1>{viewer&&<div className="home-you-line"><Sparkles size={15}/><span><b>You are {viewer.full_name.split(/\s+/)[0]}</b> in this family view. Start with your own family line, then explore outward.</span></div>}<p>{simple?(language==='hi'?'अपने परिवार को देखें, किसी रिश्तेदार को खोजें और अपनी जानकारी सही रखें।':language==='mr'?'आपले कुटुंब पहा, नातेवाईक शोधा आणि आपली माहिती अद्ययावत ठेवा.':'See your family, find a relative and keep your own profile up to date.'):c.sub}</p><div className="welcome-actions">{showMemories?<button className="btn primary" onClick={()=>onGo('community')}><Heart size={15}/>{c.memory}</button>:<button className="btn primary" onClick={()=>onGo('tree')}><Users size={15}/>{language==='hi'?'परिवार देखें':language==='mr'?'कुटुंब पहा':'See my family'}</button>}{canAddRelative&&<button className="btn warm" onClick={onAddRelative}><Plus size={15}/>{c.relative}</button>}</div></div><div className="family-home-faces">{heroMembers.slice(0,6).map(m=><button key={m.id} onClick={()=>onSelect(m)}>{m.photo_url?<img src={m.photo_url} alt=""/>:<span>{m.full_name.split(/\s+/).map(x=>x[0]).slice(0,2).join('')}</span>}</button>)}</div></div>
  {simple&&showSpecialDays&&upcoming.length>0&&<button className="card simple-next-moment" onClick={()=>onSelect(upcoming[0].m)}><span className="simple-next-icon"><Cake size={20}/></span><span><small>{language==='hi'?'अगला खास दिन':language==='mr'?'पुढचा खास दिवस':'Next family moment'}</small><b>{upcoming[0].m.full_name}</b><em>{upcoming[0].label} · {upcoming[0].n.toLocaleDateString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN',{day:'numeric',month:'long'})}</em></span></button>}
  {!simple&&showSpecialDays&&onThisDay.length>0&&<div className="card on-this-day"><div className="on-this-day-icon"><History/></div><div className="on-this-day-copy"><span className="warm-kicker">{c.onThisDay}</span>{onThisDay.map(({e,d})=><button key={e.id} onClick={()=>{const m=members.find(x=>x.id===e.member_id);if(m)onSelect(m)}}><b>{e.title}</b><small>{new Date().getFullYear()-d.getFullYear()} {c.yearsAgo}{e.location?` · ${e.location}`:''}</small></button>)}</div></div>}
  {!simple&&<div className="family-pulse">{showMemories&&<button onClick={()=>onGo('community')}><Heart size={16}/><span><b>{pulse.stories}</b><small>family memories</small></span></button>}{showSpecialDays&&<button onClick={()=>onGo('tree')}><CalendarHeart size={16}/><span><b>{pulse.coming}</b><small>special days soon</small></span></button>}{showContributions&&<button onClick={()=>onGo('participation')}><Users size={16}/><span><b>{pulse.needsHelp}</b><small>profiles to enrich</small></span></button>}</div>}
  {!simple&&(showMemories||showSpecialDays)&&<div className="family-home-grid">{showMemories&&<div className="card home-memories"><div className="section-title"><div><span className="warm-kicker"><Image size={12}/> {c.moments}</span><h2>{c.moments}</h2></div><button className="btn small" onClick={()=>onGo('community')}>{c.see}</button></div>{!recent.length?<button className="home-empty-memory" onClick={()=>onGo('community')}><Heart size={24}/><span>{c.empty}</span></button>:<div className="home-memory-strip">{recent.map(x=><button key={x.id} className="home-memory-tile" onClick={()=>onGo('community')}>{x.photo_url?<img src={x.photo_url} alt=""/>:<div className="memory-placeholder"><Heart/></div>}<span><b>{x.title}</b><small>{new Date(x.created_at).toLocaleDateString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN')}</small></span></button>)}</div>}</div>}
   {showSpecialDays&&<div className="card home-coming"><span className="warm-kicker"><CalendarHeart size={12}/> {c.coming}</span><h2>{c.coming}</h2>{!upcoming.length?<p className="page-subtitle">No birthdays in the next 45 days.</p>:upcoming.map(x=><div className="home-milestone" key={x.m.id}><button className="milestone-person" onClick={()=>onSelect(x.m)}><span className="milestone-icon"><Cake size={16}/></span><span><b>{x.m.full_name}</b><small>{x.label} · {x.n.toLocaleDateString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN',{day:'numeric',month:'short'})}</small></span><em>{x.days===0?'Today':`${x.days}d`}</em></button>{showSharing&&<button className="milestone-share" onClick={()=>shareDay(x.m.full_name,x.n,x.label)} title="Share celebration card"><Share2 size={14}/></button>}</div>)}</div>}
  </div>}
  {showContributions&&<div className="card home-contribution"><div className="contribution-spark"><Sparkles/></div><div><span className="warm-kicker">{c.contribute}</span><h2>{incomplete?`Help complete ${incomplete.full_name}’s profile`:c.contribute}</h2><p>{c.help}</p></div><button className="btn primary" onClick={()=>onGo('participation')}><Users size={15}/>{c.start}</button></div>}
 </section>
}
