"use client";
import {useEffect,useMemo,useState} from "react";
import {Cake,CalendarHeart,Heart,Image,Plus,Sparkles,Users} from "lucide-react";
import {LifeEvent,Member,Memory} from "../lib/types";
import {getNetworkRepository} from "../lib/repository";
import {useLanguage} from "../lib/i18n";

export default function FamilyHome({members,events,networkName,onSelect,onGo,onAddRelative}:{members:Member[];events:LifeEvent[];networkName?:string;onSelect:(m:Member)=>void;onGo:(v:"community"|"participation"|"tree")=>void;onAddRelative:()=>void}){
 const {language}=useLanguage(); const repo=getNetworkRepository(); const [memories,setMemories]=useState<Memory[]>([]);
 useEffect(()=>{repo.fetchMemories().then(setMemories).catch(()=>setMemories([]))},[]);
 const c=language==='hi'?{k:'आपका परिवार, साथ',hello:'आज परिवार में क्या नया है',sub:'यादें सँजोएँ, खास दिन याद रखें और एक-दूसरे से जुड़े रहें।',memory:'एक याद साझा करें',relative:'रिश्तेदार जोड़ें',moments:'हाल की यादें',see:'सभी यादें',coming:'आने वाले खास दिन',contribute:'आज का छोटा योगदान',help:'परिवार की जानकारी पूरी करने में एक मिनट मदद करें',start:'अभी मदद करें',empty:'पहली पारिवारिक याद साझा करें—एक तस्वीर और दो पंक्तियाँ काफी हैं।',birthday:'जन्मदिन'}:language==='mr'?{k:'आपले कुटुंब, एकत्र',hello:'आज कुटुंबात काय नवीन आहे',sub:'आठवणी जपा, खास दिवस लक्षात ठेवा आणि एकमेकांशी जोडलेले रहा.',memory:'आठवण सामायिक करा',relative:'नातेवाईक जोडा',moments:'अलीकडच्या आठवणी',see:'सर्व आठवणी',coming:'लवकरच खास दिवस',contribute:'आजचे छोटे योगदान',help:'कुटुंबाची माहिती पूर्ण करण्यासाठी एक मिनिट मदत करा',start:'आता मदत करा',empty:'पहिली कौटुंबिक आठवण सामायिक करा—एक फोटो आणि दोन ओळी पुरेशा आहेत.',birthday:'वाढदिवस'}:{k:'Your family, together',hello:'What’s happening in the family',sub:'Remember the stories, celebrate the moments and stay close across generations.',memory:'Share a memory',relative:'Add a relative',moments:'Recently shared',see:'See all memories',coming:'Special days coming up',contribute:'One small thing today',help:'Help make your family network a little more complete. It takes about a minute.',start:'Help the family',empty:'Share the first family memory—a photo and two lines are enough.',birthday:'Birthday'};
 const upcoming=useMemo(()=>{const now=new Date();now.setHours(0,0,0,0);return members.filter(m=>!m.date_of_death&&m.date_of_birth).map(m=>{const d=new Date(m.date_of_birth+'T00:00:00');let n=new Date(now.getFullYear(),d.getMonth(),d.getDate());if(n<now)n.setFullYear(n.getFullYear()+1);return {m,n,days:Math.round((n.getTime()-now.getTime())/86400000)}}).filter(x=>x.days<=45).sort((a,b)=>a.days-b.days).slice(0,5)},[members]);
 const recent=memories.slice(0,4); const incomplete=members.find(m=>!m.photo_url||!m.city||!m.date_of_birth);
 return <section className="family-home">
  <div className="family-home-hero"><div><span className="warm-kicker">{c.k}</span><h1>{networkName||c.hello}</h1><p>{c.sub}</p><div className="welcome-actions"><button className="btn primary" onClick={()=>onGo('community')}><Heart size={15}/>{c.memory}</button><button className="btn warm" onClick={onAddRelative}><Plus size={15}/>{c.relative}</button></div></div><div className="family-home-faces">{members.slice(0,6).map(m=><button key={m.id} onClick={()=>onSelect(m)}>{m.photo_url?<img src={m.photo_url} alt=""/>:<span>{m.full_name.split(/\s+/).map(x=>x[0]).slice(0,2).join('')}</span>}</button>)}</div></div>
  <div className="family-home-grid"><div className="card home-memories"><div className="section-title"><div><span className="warm-kicker"><Image size={12}/> {c.moments}</span><h2>{c.moments}</h2></div><button className="btn small" onClick={()=>onGo('community')}>{c.see}</button></div>{!recent.length?<button className="home-empty-memory" onClick={()=>onGo('community')}><Heart size={24}/><span>{c.empty}</span></button>:<div className="home-memory-strip">{recent.map(x=><button key={x.id} className="home-memory-tile" onClick={()=>onGo('community')}>{x.photo_url?<img src={x.photo_url} alt=""/>:<div className="memory-placeholder"><Heart/></div>}<span><b>{x.title}</b><small>{new Date(x.created_at).toLocaleDateString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN')}</small></span></button>)}</div>}</div>
   <div className="card home-coming"><span className="warm-kicker"><CalendarHeart size={12}/> {c.coming}</span><h2>{c.coming}</h2>{!upcoming.length?<p className="page-subtitle">No birthdays in the next 45 days.</p>:upcoming.map(x=><button className="home-milestone" key={x.m.id} onClick={()=>onSelect(x.m)}><span className="milestone-icon"><Cake size={16}/></span><span><b>{x.m.full_name}</b><small>{c.birthday} · {x.n.toLocaleDateString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN',{day:'numeric',month:'short'})}</small></span><em>{x.days===0?'Today':`${x.days}d`}</em></button>)}</div>
  </div>
  <div className="card home-contribution"><div className="contribution-spark"><Sparkles/></div><div><span className="warm-kicker">{c.contribute}</span><h2>{incomplete?`Help complete ${incomplete.full_name}’s profile`:c.contribute}</h2><p>{c.help}</p></div><button className="btn primary" onClick={()=>onGo('participation')}><Users size={15}/>{c.start}</button></div>
 </section>
}
