"use client";
import {useEffect,useState} from "react";
import {Download,HardDrive,KeyRound,Settings2,ShieldCheck,Users,UserRoundCog} from "lucide-react";
import {ChangeRequest,NetworkSettings} from "../lib/types";
import {fetchFamilyAdminSummary,fetchFamilyMemberships,FamilyAdminSummary,FamilyMembershipRow,setFamilyMemberRole} from "../lib/remote";

type Tab="overview"|"members"|"approvals"|"privacy"|"storage"|"settings"|"export";
export default function FamilyAdminCenter({network,memberCount,relationshipCount,changeRequests,onSaveSettings,onOpenInvitations,onOpenParticipation,onExportCsv,onExportJson,onPrint,onNotify}:{network:NetworkSettings;memberCount:number;relationshipCount:number;changeRequests:ChangeRequest[];onSaveSettings:(p:Partial<NetworkSettings>)=>Promise<void>;onOpenInvitations:()=>void;onOpenParticipation:()=>void;onExportCsv:()=>void;onExportJson:()=>void;onPrint:()=>void;onNotify:(s:string)=>void}){
 const [tab,setTab]=useState<Tab>("overview"),[summary,setSummary]=useState<FamilyAdminSummary|null>(null),[people,setPeople]=useState<FamilyMembershipRow[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [s,p]=await Promise.all([fetchFamilyAdminSummary(),fetchFamilyMemberships()]);setSummary(s);setPeople(p)}catch(e:any){onNotify(e.message||"Could not load family administration.")}};
 useEffect(()=>{load()},[network.network_id]);
 const pending=changeRequests.filter(x=>x.status==="pending").length;
 const storage=summary?.media_usage_bytes||0, limit=summary?.storage_limit_bytes||104857600, pct=Math.min(100,Math.round(storage/Math.max(1,limit)*100));
 const role=async(row:FamilyMembershipRow,next:"admin"|"member")=>{setBusy(true);try{await setFamilyMemberRole(row.user_id,next);await load();onNotify(`${row.display_name||row.email||"Member"} is now ${next}.`)}catch(e:any){onNotify(e.message||"Could not change family role.")}finally{setBusy(false)}};
 const tabs:[Tab,string][]=[["overview","Overview"],["members","Members & roles"],["approvals","Approvals"],["privacy","Privacy"],["storage","Storage"],["settings","Family settings"],["export","Export / backup"]];
 return <div className="family-admin-center">
  <div className="admin-center-hero"><div><span className="warm-kicker"><ShieldCheck size={13}/> Family Admin Center</span><h1>{network.name}</h1><p>Run your family from one place—members, invitations, privacy, storage and settings.</p></div><button className="btn primary" onClick={onOpenInvitations}><KeyRound size={15}/> Invite relatives</button></div>
  <div className="admin-center-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==="overview"&&<><div className="admin-center-stats"><div><Users/><span><b>{memberCount}</b> family profiles</span></div><div><UserRoundCog/><span><b>{summary?.claimed_profiles||0}</b> claimed profiles</span></div><div><KeyRound/><span><b>{summary?.active_invitations||0}</b> active invites</span></div><div><ShieldCheck/><span><b>{pending}</b> approvals waiting</span></div></div><div className="admin-center-grid"><div className="card admin-action-card"><h3>Family health</h3><p>{relationshipCount} relationships · {summary?.admin_count||1} family admins</p><button className="btn" onClick={onOpenParticipation}>Review participation</button></div><div className="card admin-action-card"><h3>Storage</h3><p>{(storage/1048576).toFixed(1)} MB of {(limit/1048576).toFixed(0)} MB used</p><div className="usage-bar"><i style={{width:`${pct}%`}}/></div><small>{pct}% used · photos {network.photo_upload_enabled?"enabled":"disabled"}</small></div></div></>}
  {tab==="members"&&<div className="card admin-center-panel"><div className="section-title"><div><h2>Members & roles</h2><p className="page-subtitle">Family roles apply only inside this family.</p></div><button className="btn primary" onClick={onOpenInvitations}>Invite relatives</button></div>{people.length===0?<div className="empty compact">No claimed accounts yet.</div>:people.map(p=><div className="admin-member-row" key={p.user_id}><div className="admin-member-avatar">{(p.display_name||p.email||"?").slice(0,1).toUpperCase()}</div><span><b>{p.display_name||p.email||"Family member"}</b><small>{p.email||"Account connected"}{p.member_name?` · profile: ${p.member_name}`:""}</small></span><em className={`role-pill ${p.role}`}>{p.role}</em>{p.role!=="owner"&&<select disabled={busy} value={p.role} onChange={e=>role(p,e.target.value as "admin"|"member")}><option value="member">Member</option><option value="admin">Admin</option></select>}</div>)}</div>}
  {tab==="approvals"&&<div className="card admin-center-panel"><h2>Pending approvals</h2><p className="page-subtitle">Governed identity and relationship changes stay reviewable.</p>{changeRequests.filter(x=>x.status==="pending").length===0?<div className="empty compact">Nothing is waiting for approval.</div>:changeRequests.filter(x=>x.status==="pending").map(x=><div className="admin-simple-row" key={x.id}><span><b>{x.action.replaceAll("_"," ")}</b><small>{new Date(x.created_at).toLocaleString()}</small></span><em>Pending</em></div>)}</div>}
  {tab==="privacy"&&<div className="card admin-center-panel"><h2>Privacy defaults</h2><div className="admin-setting"><span><b>Photo uploads</b><small>Off is the lightweight, privacy-conscious Alpha default. Images are capped separately.</small></span><input type="checkbox" checked={!!network.photo_upload_enabled} onChange={e=>onSaveSettings({photo_upload_enabled:e.target.checked})}/></div><div className="admin-setting"><span><b>Safe self edits</b><small>Allow members to directly update low-risk fields; identity and relationships remain governed.</small></span><input type="checkbox" checked={network.self_edit_mode==="safe_fields_direct"} onChange={e=>onSaveSettings({self_edit_mode:e.target.checked?"safe_fields_direct":"review"})}/></div></div>}
  {tab==="storage"&&<div className="card admin-center-panel"><h2>Family storage</h2><div className="storage-big"><HardDrive/><div><b>{(storage/1048576).toFixed(1)} MB</b><span>of {(limit/1048576).toFixed(0)} MB Alpha allowance</span></div></div><div className="usage-bar large"><i style={{width:`${pct}%`}}/></div><p className="page-subtitle">Stored family media is counted per family. The current image limit is {(summary?.photo_max_bytes||102400)/1024} KB per upload.</p></div>}
  {tab==="settings"&&<div className="card admin-center-panel"><h2>Family settings</h2><div className="settings-readout"><label>Family name<strong>{network.name}</strong></label><label>Family URL<strong>/{network.slug||"family"}</strong></label><label>Your role<strong>{network.membership_role||"admin"}</strong></label></div><div className="admin-setting"><span><b>Upcoming family milestones</b><small>Show birthdays and family moments in the return experience.</small></span><input type="checkbox" checked={network.family_milestones_enabled!==false} onChange={e=>onSaveSettings({family_milestones_enabled:e.target.checked})}/></div></div>}
  {tab==="export"&&<div className="card admin-center-panel"><h2>Export / backup</h2><p className="page-subtitle">Keep a portable copy before large imports or important family changes.</p><div className="card-actions"><button className="btn primary" onClick={onExportCsv}><Download size={15}/> Export CSV</button><button className="btn" onClick={onExportJson}><Download size={15}/> Export JSON</button><button className="btn" onClick={onPrint}><Download size={15}/> Print / PDF</button></div></div>}
 </div>
}
