"use client";
import {useEffect,useMemo,useState} from "react";
import {Flag,FlaskConical,MessageSquareText,Radio,RefreshCw,Rocket,ShieldCheck,Trash2,UserPlus,Users,WandSparkles} from "lucide-react";
import {FEATURE_REGISTRY,FeatureBundle,FeatureKey,LaunchState} from "../lib/features";
import {addPlatformOwnerByEmail,applyAlphaDay1LaunchPreset,fetchPlatformFamilyTargets,fetchPlatformLaunchConsole,fetchPlatformOwnerAudit,fetchPlatformOwners,fetchPlatformRolloutAudit,fetchPlatformFamilyCreationRequests,reviewFamilyCreationRequest,fetchFamilyCreationPolicy,setFamilyCreationPolicy,fetchPlatformGuideFeedback,fetchGuideFeedbackSignals,updatePlatformGuideFeedbackStatus,PlatformGuideFeedback,fetchPlaygroundLaunchConsole,setPlaygroundFeatureVisibility,PlaygroundFeatureRow,PlatformFamilyCreationRequest,PlatformFamilyTarget,PlatformLaunchFeature,PlatformOwnerAuditRow,PlatformOwnerRow,PlatformRolloutAudit,removePlatformOwner,setPlatformBundleRollout,setPlatformFeatureRollout} from "../lib/remote";

const BUNDLES:{key:FeatureBundle;label:string;description:string}[]=[
 {key:"core",label:"Core family",description:"Home, family tree, profiles and family finding."},
 {key:"remember",label:"Remember",description:"Memories and family history."},
 {key:"celebrate",label:"Celebrate",description:"Birthdays, anniversaries and special days."},
 {key:"connect",label:"Connect",description:"Places, community, gatherings and relationship exploration."},
 {key:"contribute",label:"Contribute",description:"Prompts and tools that help relatives improve the family."},
 {key:"share",label:"Share",description:"WhatsApp, public cards, QR and printable experiences."},
 {key:"admin",label:"Administration",description:"Family administration and governance surfaces."},
];
const STATES:LaunchState[]=["hidden","test","pilot","released"];
const stateHelp:Record<LaunchState,string>={hidden:"Nobody sees it.",test:"Only platform owners see it.",pilot:"Only selected pilot families see it.",released:"Available to all eligible families."};

export default function FounderLaunchConsole({onChanged,onNotify}:{onChanged:()=>Promise<void>|void;onNotify:(message:string)=>void}){
 const [rows,setRows]=useState<PlatformLaunchFeature[]>([]),[playgroundRows,setPlaygroundRows]=useState<PlaygroundFeatureRow[]>([]),[families,setFamilies]=useState<PlatformFamilyTarget[]>([]),[audit,setAudit]=useState<PlatformRolloutAudit[]>([]),[owners,setOwners]=useState<PlatformOwnerRow[]>([]),[ownerAudit,setOwnerAudit]=useState<PlatformOwnerAuditRow[]>([]),[creationRequests,setCreationRequests]=useState<PlatformFamilyCreationRequest[]>([]),[guideFeedback,setGuideFeedback]=useState<PlatformGuideFeedback[]>([]),[feedbackSignals,setFeedbackSignals]=useState<{guide_key:string;feedback_type:string;family_count:number;feedback_count:number}[]>([]),[approvalRequired,setApprovalRequiredState]=useState(true),[busy,setBusy]=useState(true),[pilotIds,setPilotIds]=useState<string[]>([]),[newOwnerEmail,setNewOwnerEmail]=useState("");
 const load=async()=>{setBusy(true);try{const [features,playground,targets,history,ownerRows,ownerHistory,requests,policy,feedback,signals]=await Promise.all([fetchPlatformLaunchConsole(),fetchPlaygroundLaunchConsole(),fetchPlatformFamilyTargets(),fetchPlatformRolloutAudit(20),fetchPlatformOwners(),fetchPlatformOwnerAudit(12),fetchPlatformFamilyCreationRequests(),fetchFamilyCreationPolicy(),fetchPlatformGuideFeedback(),fetchGuideFeedbackSignals()]);setRows(features);setPlaygroundRows(playground);setFamilies(targets);setAudit(history);setOwners(ownerRows);setOwnerAudit(ownerHistory);setCreationRequests(requests);setApprovalRequiredState(policy);setGuideFeedback(feedback);setFeedbackSignals(signals)}catch(e:any){onNotify(e.message||"Could not load Launch Control.")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const byKey=useMemo(()=>Object.fromEntries(rows.map(r=>[r.feature_key,r])) as Record<string,PlatformLaunchFeature>,[rows]);
 const playgroundByKey=useMemo(()=>new Map(playgroundRows.map(r=>[r.feature_key,r] as const)),[playgroundRows]);
 const togglePilot=(id:string)=>setPilotIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const saveFeature=async(key:FeatureKey,state:LaunchState,announce=false,pilotOverride?:string[])=>{const targets=pilotOverride??pilotIds;if(state==="pilot"&&targets.length===0){onNotify("Select at least one Pilot family first.");return}setBusy(true);try{await setPlatformFeatureRollout(key,state,state==="pilot"?targets:[],announce);await load();await onChanged();onNotify(`${FEATURE_REGISTRY.find(f=>f.key===key)?.label||key} is now ${state}.`)}catch(e:any){onNotify(e.message||"Could not change feature rollout.")}finally{setBusy(false)}};
 const saveBundle=async(bundle:FeatureBundle,state:LaunchState,announce=false)=>{if(state==="pilot"&&pilotIds.length===0){onNotify("Select at least one Pilot family first.");return}setBusy(true);try{const changed=await setPlatformBundleRollout(bundle,state,state==="pilot"?pilotIds:[],announce);await load();await onChanged();onNotify(`${changed} feature${changed===1?"":"s"} moved to ${state}.`)}catch(e:any){onNotify(e.message||"Could not change bundle rollout.")}finally{setBusy(false)}};
 const addOwner=async()=>{if(!newOwnerEmail.trim())return;setBusy(true);try{await addPlatformOwnerByEmail(newOwnerEmail);setNewOwnerEmail("");await load();onNotify("Launch Control access granted.")}catch(e:any){onNotify(e.message||"Could not add platform owner.")}finally{setBusy(false)}};
 const removeOwner=async(row:PlatformOwnerRow)=>{if(row.is_me){onNotify("For safety, ask another platform owner to remove your access if needed.");return}setBusy(true);try{await removePlatformOwner(row.user_id);await load();onNotify("Launch Control access removed.")}catch(e:any){onNotify(e.message||"Could not remove platform owner.")}finally{setBusy(false)}};
 const applyDay1=async()=>{setBusy(true);try{const changed=await applyAlphaDay1LaunchPreset();setPilotIds([]);await load();await onChanged();onNotify(changed?`Day-1 Alpha preset applied to ${changed} feature${changed===1?"":"s"}.`:"Day-1 Alpha preset is already active.")}catch(e:any){onNotify(e.message||"Could not apply the Day-1 Alpha preset.")}finally{setBusy(false)}};
 const reviewCreation=async(row:PlatformFamilyCreationRequest,action:"approve"|"reject")=>{setBusy(true);try{await reviewFamilyCreationRequest(row.id,action);await load();onNotify(action==="approve"?`${row.name} approved. The requester is now Family Owner.`:`${row.name} request rejected.`)}catch(e:any){onNotify(e.message||"Could not review family request.")}finally{setBusy(false)}};
 const toggleCreationPolicy=async(next:boolean)=>{setBusy(true);try{await setFamilyCreationPolicy(next);setApprovalRequiredState(next);onNotify(next?"Family creation approval is now required.":"Alpha auto-approval is ON. Signed-in users can create families immediately.")}catch(e:any){onNotify(e.message||"Could not change family creation policy.")}finally{setBusy(false)}};
 const togglePlayground=async(key:FeatureKey,enabled:boolean)=>{setBusy(true);try{await setPlaygroundFeatureVisibility(key,enabled);setPlaygroundRows(v=>v.map(r=>r.feature_key===key?{...r,enabled}:r));onNotify(`${FEATURE_REGISTRY.find(f=>f.key===key)?.label||key} ${enabled?"shown":"hidden"} in Playground.`)}catch(e:any){onNotify(e.message||"Could not change Playground visibility.")}finally{setBusy(false)}};

 const setFeedbackStatus=async(id:string,status:string)=>{setBusy(true);try{await updatePlatformGuideFeedbackStatus(id,status);await load();onNotify("Feedback status updated. Roadmap files were not changed automatically.")}catch(e:any){onNotify(e.message||"Could not update feedback status.")}finally{setBusy(false)}};
 const setAllPlayground=async(enabled:boolean)=>{setBusy(true);try{for(const feature of FEATURE_REGISTRY.filter(f=>f.bundle!=="admin"&&playgroundByKey.has(f.key)))await setPlaygroundFeatureVisibility(feature.key,enabled);await load();onNotify(enabled?"All available member-facing Playground features are visible.":"All available member-facing Playground features are hidden.")}catch(e:any){onNotify(e.message||"Could not update Playground visibility.")}finally{setBusy(false)}};
 return <div className="founder-launch-console">
  <div className="founder-launch-hero"><div><span className="warm-kicker"><Rocket size={13}/> Platform owner</span><h1>Launch Control</h1><p>Reveal Family Network gradually. Deployment does not automatically mean release.</p></div><button className="btn" onClick={load} disabled={busy}><RefreshCw size={15}/> Refresh</button></div>
  <div className="launch-rule card"><ShieldCheck/><div><b>Release precedence</b><span>Founder rollout → family member setting → experience level → permission. A family admin can hide a released feature, but can never reveal something you have not released.</span></div></div>

  <section className="card guide-feedback-triage"><div className="section-title"><div><h2>Family feedback intelligence</h2><p className="page-subtitle">Structured product feedback across guides and screens. Status changes here never mutate roadmap files automatically.</p></div><span className="role-pill member"><MessageSquareText size={12}/> {guideFeedback.filter(x=>x.status==="new").length} new</span></div>
   {feedbackSignals.length>0&&<div className="feedback-signal-grid">{feedbackSignals.slice(0,6).map(s=><div key={`${s.guide_key}-${s.feedback_type}`}><b>{s.family_count} famil{s.family_count===1?"y":"ies"}</b><span>{s.feedback_type.replaceAll("_"," ")} · {s.guide_key||"general"}</span><small>{s.feedback_count} response{s.feedback_count===1?"":"s"}</small></div>)}</div>}
   <div className="feedback-triage-list">{guideFeedback.slice(0,30).map(f=><article key={f.id}><div><span className="warm-kicker">{f.feedback_type.replaceAll("_"," ")} · {f.guide_key||f.screen||"general"}</span><p>{f.message||"Quick helpfulness signal"}</p><small>{new Date(f.created_at).toLocaleString()} · {f.role||"member"} · {f.experience_mode||"unknown view"}</small></div><select value={f.status} disabled={busy} onChange={e=>setFeedbackStatus(f.id,e.target.value)}><option value="new">New</option><option value="reviewing">Reviewing</option><option value="planned">Planned</option><option value="already_supported">Already supported</option><option value="not_planned">Not planned</option><option value="implemented">Implemented</option></select></article>)}{guideFeedback.length===0&&<div className="empty">No guide feedback yet.</div>}</div>
  </section>

  <section className="card platform-owners"><div className="section-title"><div><h2>Who can control launches</h2><p className="page-subtitle">Launch Control belongs to platform owners, not ordinary family Owners/Admins. You can safely grant it to a few trusted Family Network accounts.</p></div><span className="role-pill member">{owners.length} owner{owners.length===1?"":"s"}</span></div>
   <div className="owner-add-row"><input className="text-input" type="email" value={newOwnerEmail} onChange={e=>setNewOwnerEmail(e.target.value)} placeholder="trusted-owner@example.com" aria-label="Platform owner email"/><button className="btn primary" type="button" disabled={busy||!newOwnerEmail.trim()} onClick={addOwner}><UserPlus size={15}/> Add owner</button></div>
   <div className="platform-owner-list">{owners.map(row=><div className="platform-owner-row" key={row.user_id}><span><b>{row.email||"Account without email"}</b><small>{row.is_me?"You · ":""}Launch Control access since {new Date(row.created_at).toLocaleDateString()}</small></span><button className="icon-button danger" type="button" title={row.is_me?"Ask another platform owner to remove your access":"Remove Launch Control access"} disabled={busy||row.is_me||owners.length<=1} onClick={()=>removeOwner(row)}><Trash2 size={15}/></button></div>)}</div>
   <div className="notice"><b>Safety:</b> The database refuses to remove the final platform owner. The person you add must already have created a Family Network account with that email.</div>
   {ownerAudit.length>0&&<details className="owner-audit"><summary>Recent owner-access changes</summary>{ownerAudit.map(row=><div className="rollout-history-row" key={row.id}><span><b>{row.target_email||"Unknown account"}</b><small>{new Date(row.created_at).toLocaleString()} · by {row.actor_email||"previous owner"}</small></span><em>{row.action}</em></div>)}</details>}
  </section>

  <section className="card family-creation-approvals"><div className="section-title"><div><h2>Family creation</h2><p className="page-subtitle">For Alpha exploration you can temporarily allow instant self-service creation. Turn approval back on whenever you want tighter platform control.</p></div><label className="living-setting founder-policy-toggle"><span><b>{approvalRequired?"Approval required":"Alpha auto-approval ON"}</b><small>{approvalRequired?"New users submit a request and wait for a platform owner.":"Any signed-in user can create/import a family immediately and becomes its Family Owner."}</small></span><input type="checkbox" checked={approvalRequired} disabled={busy} onChange={e=>toggleCreationPolicy(e.target.checked)}/></label></div><div className={`notice ${approvalRequired?"":"success-notice"}`}><b>Current behavior:</b> {approvalRequired?"Platform owner must approve new family spaces.":"No approval wait. Best for the current invite-only Alpha; switch this back on before wider public launch."}</div><div className="section-title" style={{marginTop:16}}><div><h3 style={{margin:0}}>Creation requests</h3></div><span className="role-pill member">{creationRequests.filter(r=>r.status==="pending").length} pending</span></div>
   {creationRequests.length===0?<div className="empty compact">No family creation requests yet.</div>:<div className="family-creation-request-list">{creationRequests.slice(0,20).map(row=><div className="family-creation-review-row" key={row.id}><span><b>{row.name}</b><small>{row.requester_email||"Unknown account"} · {new Date(row.created_at).toLocaleString()}</small>{row.description&&<em>{row.description}</em>}</span><div className="family-creation-review-actions"><span className={`status ${row.status}`}>{row.status}</span>{row.status==="pending"&&<><button className="btn small" disabled={busy} onClick={()=>reviewCreation(row,"reject")}>Reject</button><button className="btn primary small" disabled={busy} onClick={()=>reviewCreation(row,"approve")}>Approve family</button></>}</div></div>)}</div>}
  </section>

  <section className="card playground-feature-control"><div className="section-title"><div><span className="warm-kicker"><FlaskConical size={13}/> Playground showcase</span><h2>Playground feature visibility</h2><p className="page-subtitle">Independent from real-user rollout. Use this to make the anonymous sample reveal the strongest member-facing capabilities even while Alpha families remain conservative.</p></div><div className="card-actions"><button className="btn small" disabled={busy} onClick={()=>setAllPlayground(false)}>Hide all</button><button className="btn primary small" disabled={busy} onClick={()=>setAllPlayground(true)}>Show all</button></div></div><div className="family-feature-list">{FEATURE_REGISTRY.filter(f=>f.bundle!=="admin").map(feature=>{const row=playgroundByKey.get(feature.key);const backendReady=Boolean(row);const loading=busy&&playgroundRows.length===0;const enabled=row?.enabled===true;return <div className="admin-setting" key={feature.key}><span><b>{feature.label}</b><small>{feature.description} · {loading?"Loading Playground registry":backendReady?"Playground only":"Database update required before this control can be changed"}</small></span><input type="checkbox" checked={enabled} disabled={busy||!backendReady} onChange={e=>togglePlayground(feature.key,e.target.checked)}/></div>})}</div><div className="notice success-notice"><b>Recommended for the S3-A pilot:</b> show the strongest safe product breadth in Playground, while keeping public-profile and print/QR distribution off by default. Real-family rollout remains independent.</div></section>

  <section className="card alpha-preset"><div><span className="warm-kicker"><WandSparkles size={13}/> First-family release</span><h2>Day-1 Alpha preset</h2><p>Pilot baseline: release Core, Guide, Special Days, Memories, History, Family Pulse, Quiet Digest, Contributions and Relationship Explorer. Keep Community, Places, public-profile/QR distribution in Test; Gatherings and family sharing can stay Pilot.</p></div><button className="btn" type="button" disabled={busy} onClick={applyDay1}><WandSparkles size={15}/> Apply safe Day-1 preset</button></section>

  <section className="card pilot-targets"><div className="section-title"><div><h2>Pilot families</h2><p className="page-subtitle">Select the families used whenever you move a feature or bundle to Pilot.</p></div><span className="role-pill member">{pilotIds.length} selected</span></div>
   <div className="pilot-family-grid">{families.length===0?<div className="empty compact">No families are available yet.</div>:families.map(f=><label key={f.network_id} className={`pilot-family ${pilotIds.includes(f.network_id)?"selected":""}`}><input type="checkbox" checked={pilotIds.includes(f.network_id)} onChange={()=>togglePilot(f.network_id)}/><span><b>{f.name}</b><small>/{f.slug} · {f.member_count} active account{f.member_count===1?"":"s"}</small></span></label>)}</div>
  </section>
  <div className="launch-legend">{STATES.map(state=><span key={state} className={`launch-state ${state}`}><i/>{state}<small>{stateHelp[state]}</small></span>)}</div>
  <div className="launch-bundles">{BUNDLES.map(bundle=>{const defs=FEATURE_REGISTRY.filter(f=>f.bundle===bundle.key);const states=defs.map(d=>byKey[d.key]?.rollout_state||d.defaultLaunch);const common=states.every(x=>x===states[0])?states[0]:null;return <section className="card launch-bundle" key={bundle.key}>
   <div className="launch-bundle-head"><div><span className="warm-kicker"><Flag size={13}/> {bundle.label}</span><h2>{bundle.label}</h2><p>{bundle.description}</p></div><div className="bundle-actions"><select className="select" value={common||""} disabled={busy} onChange={e=>e.target.value&&saveBundle(bundle.key,e.target.value as LaunchState,false)}><option value="" disabled>Mixed</option>{STATES.map(state=><option key={state} value={state}>{state}</option>)}</select><button className="btn small" disabled={busy||!(common==="pilot"||common==="released")} onClick={()=>common&&saveBundle(bundle.key,common,true)}><Radio size={14}/> Announce</button></div></div>
   <div className="launch-feature-list">{defs.map(def=>{const row=byKey[def.key];const backendReady=Boolean(row);const loading=busy&&rows.length===0;const state=row?.rollout_state||def.defaultLaunch;return <div className="launch-feature-row" key={def.key}><div><b>{def.label}</b><small>{def.description}{loading?" · Loading launch registry":backendReady?"":" · Database update required"}</small></div><span className={`launch-state compact ${state}`}>{state}</span><select className="select" value={state} disabled={busy||!backendReady} onChange={e=>saveFeature(def.key,e.target.value as LaunchState,false)}>{STATES.map(s=><option key={s} value={s}>{s}</option>)}</select><button className="icon-button" title={backendReady?"Announce this feature as new":"Apply pending database migrations first"} disabled={busy||!backendReady||!(state==="pilot"||state==="released")} onClick={()=>saveFeature(def.key,state,true,row?.pilot_network_ids||[])}><FlaskConical size={15}/></button></div>})}</div>
  </section>})}</div>
  <section className="card rollout-history"><div className="section-title"><div><h2>Recent rollout activity</h2><p className="page-subtitle">A founder-only audit trail of feature exposure changes.</p></div></div>{audit.length===0?<div className="empty compact">No rollout changes recorded yet.</div>:audit.map(item=><div className="rollout-history-row" key={item.id}><span><b>{FEATURE_REGISTRY.find(f=>f.key===item.feature_key)?.label||item.feature_key}</b><small>{new Date(item.changed_at).toLocaleString()} · {item.bundle_key}{item.announced?" · announced":""}</small></span><em>{item.previous_state} → {item.new_state}</em></div>)}</section>
  <div className="card launch-footnote"><Users/><div><b>Family controls come after founder release</b><span>Family admins see only member-facing switches and can disable them for their own family. Admin capabilities remain role-controlled, not family-member preferences.</span></div></div>
 </div>
}
