"use client";
import {useMemo,useState} from "react";
import {ArrowRight,BookOpen,ChevronDown,ChevronUp,Compass,Heart,Lightbulb,PlayCircle,Search,ShieldCheck,Sparkles,Users,UserRound,Waypoints} from "lucide-react";
import type {GuideAudience,GuideEntry} from "../lib/guide-types";
import {FUTURE_INTERESTS,GUIDE_ENTRIES,GUIDE_GOALS,GUIDE_SECTIONS,IDEAS_FOR_FAMILY,PERSONAS,guideVisibleTo,searchGuides} from "../lib/user-guide-content";
import GuideFeedback from "./GuideFeedback";
import {submitGuideFeedback} from "../lib/remote";

type Props={audience:GuideAudience;experience:string;demo:boolean;featureVisible:(key:string)=>boolean;initialKey?:string;onOpenFeature:(action?:string)=>void;onTryPlayground:(key?:string)=>void;onNotify:(s:string)=>void};
const statusLabel=(s:GuideEntry["status"])=>s==="live"?"Live":s==="live_verify"?"Live · verify deployment":s==="partial"?"Partial":"Being explored";
export default function GuidePortal({audience,experience,demo,featureVisible,initialKey,onOpenFeature,onTryPlayground,onNotify}:Props){
 const visible=useMemo(()=>GUIDE_ENTRIES.filter(e=>guideVisibleTo(e,audience,featureVisible)),[audience,featureVisible]);
 const [query,setQuery]=useState(""),[selected,setSelected]=useState(initialKey||""),[personaOpen,setPersonaOpen]=useState<string>(""),[mode,setMode]=useState<"overview"|"library"|"privacy">(initialKey?"library":"overview");
 const results=useMemo(()=>searchGuides(query,visible),[query,visible]);
 const selectedEntry=visible.find(e=>e.key===selected);
 const openEntry=(key:string)=>{setSelected(key);setMode("library");window.setTimeout(()=>document.getElementById("guide-detail")?.scrollIntoView({behavior:"smooth",block:"start"}),20)};
 return <div className="guide-portal">
  <section className="guide-hero">
   <div><span className="warm-kicker"><Compass size={14}/> Explore & Guide</span><h1>Your family is more than a tree.</h1><p>Family Network is a private living family space to understand relationships, preserve stories, celebrate important moments, contribute trusted information and stay connected across generations.</p><div className="guide-pillars"><span><Waypoints/>Know your family</span><span><Heart/>Remember your story</span><span><Users/>Stay connected</span><span><Sparkles/>Build it together</span></div></div>
   <div className="guide-hero-note"><b>Powerful underneath. Effortless on the surface.</b><span>Use the guide by goal, by feature, or by the kind of family member you are.</span></div>
  </section>

  <div className="guide-search-wrap"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: add my mother, find cousins, import Excel, who can see my phone number…" aria-label="Search Family Network guide"/>{query&&<button className="btn small" onClick={()=>setQuery("")}>Clear</button>}</div>
  {query&&<section className="guide-search-results"><div className="section-title"><div><h2>Guide search</h2><p className="page-subtitle">Fast, deterministic help across the product guide.</p></div></div>{results.length===0?<div className="empty">No exact guide match yet. Try a shorter goal such as “add mother”, “privacy”, “Excel” or “marriage”.</div>:<div className="guide-result-list">{results.map(e=><button key={e.key} onClick={()=>openEntry(e.key)}><span><b>{e.title}</b><small>{e.summary}</small></span><ArrowRight size={16}/></button>)}</div>}</section>}

  {!query&&<>
   <section><div className="section-title"><div><h2>What brings you here?</h2><p className="page-subtitle">Start from what you want, not from product terminology.</p></div></div><div className="guide-path-grid">
    <button onClick={()=>{setMode("overview");document.getElementById("guide-personas")?.scrollIntoView({behavior:"smooth"})}}><Sparkles/><b>I'm new — show me what this can do</b><span>See real family stories and use cases.</span></button>
    <button onClick={()=>openEntry("add-myself")}><Users/><b>I want to build my family</b><span>Start small, invite others or import a larger family.</span></button>
    <button onClick={()=>setMode("library")}><BookOpen/><b>I want to understand a feature</b><span>Browse the complete module library.</span></button>
    <button onClick={()=>document.getElementById("guide-goals")?.scrollIntoView({behavior:"smooth"})}><Lightbulb/><b>I need help with something</b><span>Choose a goal in normal everyday language.</span></button>
   </div></section>

   <nav className="guide-subnav" aria-label="Guide sections"><button className={mode==="overview"?"active":""} onClick={()=>setMode("overview")}>Explore everything</button><button className={mode==="library"?"active":""} onClick={()=>setMode("library")}>Module library</button><button className={mode==="privacy"?"active":""} onClick={()=>{setMode("privacy");setSelected("privacy-trust")}}>Privacy & Trust</button></nav>

   {mode==="overview"&&<>
    <section className="guide-story card"><span className="warm-kicker">What is Family Network?</span><h2>A living family space, not a static family tree.</h2><p>A tree can show names and lines. A living family network can also preserve the stories behind those names, help children understand generations, keep important dates and history alive, invite relatives to fill missing knowledge, and enable carefully opted-in wider-community discovery without treating the private family graph as public data.</p><div className="guide-value-grid"><div><b>Know</b><span>Understand people, generations and relationship paths.</span></div><div><b>Remember</b><span>Preserve photos, stories, life events and origins.</span></div><div><b>Connect</b><span>Celebrate moments, find relatives and use trusted introductions.</span></div><div><b>Compound</b><span>Every verified profile, relationship and memory makes the family space more useful later.</span></div></div></section>

    <section><div className="section-title"><div><h2>Imagine your family using this</h2><p className="page-subtitle">The product becomes meaningful when it creates family moments, not when it merely stores records.</p></div></div><div className="guide-story-grid">{["Grandma records a story about Grandpa.","A young relative moves to another city and finds extended family there.","A newly married person learns a large new family before a wedding.","Relatives identify people in an old photo.","A reunion becomes a permanent family memory afterward.","Children explore great-grandparents and family origins.","Someone finds a trusted professional or mentor in the wider community.","A family seeks a respectful opt-in marriage introduction through trusted family connections."].map(x=><article className="card" key={x}><Heart size={18}/><p>{x}</p></article>)}</div></section>

    <section id="guide-personas"><div className="section-title"><div><h2>Family Network for people like me</h2><p className="page-subtitle">Different generations should find different value without needing to learn the whole app.</p></div></div><div className="persona-list">{PERSONAS.map(p=><article className="card persona-card" key={p.title}><button className="persona-head" onClick={()=>setPersonaOpen(personaOpen===p.title?"":p.title)}><UserRound size={17}/><span><b>{p.title}</b><small>{p.care}</small></span>{personaOpen===p.title?<ChevronUp/>:<ChevronDown/>}</button>{personaOpen===p.title&&<div className="persona-body"><b>Useful capabilities</b><div className="chip-row">{p.capabilities.map(x=><span className="role-pill member" key={x}>{x}</span>)}</div><b>Sample journey</b><p>{p.journey}</p></div>}</article>)}</div></section>

    <section id="guide-goals"><div className="section-title"><div><h2>What do you want to do?</h2><p className="page-subtitle">Users think in goals, not feature names.</p></div></div><div className="guide-goal-grid">{GUIDE_GOALS.map(([goal,key])=><button key={goal} onClick={()=>openEntry(key)}><span>{goal}</span><ArrowRight size={15}/></button>)}</div></section>

    <section><div className="section-title"><div><h2>Ideas for your family</h2><p className="page-subtitle">Small prompts that can turn an empty family space into something worth returning to.</p></div></div><div className="ideas-grid">{Object.entries(IDEAS_FOR_FAMILY).map(([title,ideas])=><article className="card" key={title}><h3>{title}</h3>{ideas.map(x=><p key={x}>• {x}</p>)}</article>)}</div></section>

    <section className="card owner-playbook"><div className="section-title"><div><h2>Family Owner playbook</h2><p className="page-subtitle">A practical path from empty family to a living family space.</p></div></div><ol>{["Create family","Add yourself","Add closest relatives","Invite 3–5 people","Import the larger family if available","Review submissions/corrections","Add meaningful memories","Preserve family history","Encourage profile completion","Add/organize a gathering","Review family activity","Connect to the wider community when useful"].map(x=><li key={x}>{x}</li>)}</ol></section>

    <section className="card first-seven"><div className="section-title"><div><h2>First 7 steps</h2><p className="page-subtitle">A gentle activation journey—progress, not pressure.</p></div></div><div className="seven-step-grid">{["Know your family","Complete yourself","Preserve one memory","Invite one relative","Discover family history","Help complete one family detail","Share something meaningful"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</div></section>

    <section><div className="section-title"><div><h2>Things you may not know Family Network can do</h2></div></div><div className="surprise-grid">{["Explain relationship-to-me","Switch between personal and full lineage","Preserve deceased-relative stories and history","Search by profession or city","Show family geographic spread","Use governed correction requests","Support multiple family networks","Explore community without exposing the private tree","Explain trusted family paths","Share a memory/digest without sharing the full graph"].map(x=><div className="card" key={x}><Sparkles size={16}/><span>{x}</span></div>)}</div></section>

    <section><div className="section-title"><div><h2>What's new</h2><p className="page-subtitle">User-facing discoveries, not technical changelogs.</p></div></div><div className="guide-story-grid"><article className="card"><Waypoints/><h3>Trusted Introductions</h3><p>Use explicit family trust paths and consent-based introduction requests.</p><button className="text-action" onClick={()=>openEntry("introductions")}>Learn more <ArrowRight size={13}/></button></article><article className="card"><Heart/><h3>Quiet Family Digest</h3><p>Catch up on meaningful family activity without a noisy feed.</p><button className="text-action" onClick={()=>openEntry("digest")}>Learn more <ArrowRight size={13}/></button></article></div></section>

    <section><div className="section-title"><div><h2>Being explored</h2><p className="page-subtitle">Ideas we may explore. Interest is a signal—not a roadmap commitment.</p></div></div><div className="future-grid">{FUTURE_INTERESTS.map(x=><article className="card" key={x}><b>{x}</b><button className="btn small" onClick={async()=>{if(demo){onNotify("Sign in to register product interest.");return}try{await submitGuideFeedback({guide_key:"future-roadmap",screen:"guide:future",feedback_type:"future_interest",message:x,role:audience,experience_mode:experience,app_version:"S2-E"});onNotify("Thanks — your interest was recorded as a product signal, not a roadmap commitment.")}catch(e:any){onNotify(e.message||"Could not record interest.")}}}>I'd use this</button></article>)}</div></section>
   </>}

   {(mode==="library"||mode==="privacy")&&<section className="guide-library"><div className="guide-library-nav">{GUIDE_SECTIONS.filter(s=>visible.some(e=>e.section===s.key)).map(s=><div key={s.key}><h3>{s.label}</h3>{visible.filter(e=>e.section===s.key).map(e=><button className={selected===e.key?"active":""} key={e.key} onClick={()=>setSelected(e.key)}>{e.title}<small>{statusLabel(e.status)}</small></button>)}</div>)}</div><div className="guide-library-main" id="guide-detail">{selectedEntry?<GuideDetail entry={selectedEntry} onOpenFeature={onOpenFeature} onTryPlayground={onTryPlayground} onOpen={openEntry} role={audience} experience={experience} demo={demo} onNotify={onNotify}/>:<div className="card empty-guide"><BookOpen size={30}/><h2>Choose a feature</h2><p>Every guide uses the same structured product source, so contextual help, search and this library stay aligned.</p></div>}</div></section>}
   {mode==="privacy"&&!selectedEntry&&<GuideDetail entry={visible.find(e=>e.key==="privacy-trust")!} onOpenFeature={onOpenFeature} onTryPlayground={onTryPlayground} onOpen={openEntry} role={audience} experience={experience} demo={demo} onNotify={onNotify}/>} 
  </>}
 </div>;
}

function GuideDetail({entry,onOpenFeature,onTryPlayground,onOpen,role,experience,demo,onNotify}:{entry:GuideEntry;onOpenFeature:(a?:string)=>void;onTryPlayground:(k?:string)=>void;onOpen:(k:string)=>void;role:GuideAudience;experience:string;demo:boolean;onNotify:(s:string)=>void}){
 return <article className="guide-detail card"><div className="guide-detail-head"><div><span className={`guide-status ${entry.status}`}>{statusLabel(entry.status)}</span><h1>{entry.title}</h1><p>{entry.summary}</p></div><BookOpen size={26}/></div><div className="guide-detail-section"><h3>What is it?</h3><p>{entry.summary}</p></div><div className="guide-detail-section"><h3>Why use it?</h3><p>{entry.why}</p></div><div className="guide-detail-section"><h3>How to use it</h3><ol>{entry.steps.map(x=><li key={x}>{x}</li>)}</ol></div><div className="guide-detail-section"><h3>Examples & ideas</h3>{entry.examples.map(x=><p key={x}>• {x}</p>)}{entry.ideas?.map(x=><p key={x}>• {x}</p>)}</div><div className="guide-two-col"><div className="guide-detail-section"><h3>Who can do what?</h3><p>{entry.permissions}</p></div><div className="guide-detail-section"><h3>Privacy</h3><p>{entry.privacy}</p></div></div>{entry.faq&&<div className="guide-detail-section"><h3>Common questions</h3>{entry.faq.map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</div>}{entry.troubleshooting&&<div className="guide-detail-section"><h3>Troubleshooting & recovery</h3>{entry.troubleshooting.map(x=><p key={x}>• {x}</p>)}</div>}{entry.related&&<div className="guide-detail-section"><h3>Related features</h3><div className="chip-row">{entry.related.map(k=><button className="role-pill member" key={k} onClick={()=>onOpen(k)}>{GUIDE_ENTRIES.find(e=>e.key===k)?.title||k}</button>)}</div></div>}<div className="card-actions guide-detail-actions">{entry.action&&<button className="btn primary" onClick={()=>onOpenFeature(entry.action)}>Open this feature <ArrowRight size={14}/></button>}{entry.playground&&<button className="btn" onClick={()=>onTryPlayground(entry.key)}><PlayCircle size={14}/> Try in Playground · no save</button>}</div><GuideFeedback guideKey={entry.key} screen={`guide:${entry.key}`} role={role} experience={experience} demo={demo} onNotify={onNotify}/></article>;
}
