"use client";
import {useState} from 'react';
import * as XLSX from 'xlsx';
import {AlertTriangle, CheckCircle2, XCircle} from 'lucide-react';
import {Member,Relationship} from '../lib/types';
import {validateImportRows} from '../lib/validation';

function uuid(){return globalThis.crypto?.randomUUID?.() || '00000000-0000-4000-8000-'+Math.random().toString(16).slice(2).padEnd(12,'0').slice(0,12)}
function isUuid(v:any){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function text(v:any){return String(v??'').trim()}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:undefined}
function xmlToRows(xml:string){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('Invalid XML.');const nodes=Array.from(doc.querySelectorAll('member,person,record'));if(!nodes.length)throw new Error('No member/person/record elements found in XML.');return nodes.map(n=>{const row:any={};Array.from(n.children).forEach(c=>row[c.tagName]=c.textContent||'');return row;});}

export default function ImportModal({onClose,onImport,existingMembers=[],existingRelationships=[]}:{onClose:()=>void;onImport:(members:Member[],rels:Relationship[])=>void;existingMembers?:Member[];existingRelationships?:Relationship[]}){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[fileName,setFileName]=useState(''),[busy,setBusy]=useState(false),[report,setReport]=useState<any>(null),[parsed,setParsed]=useState<{members:Member[];relationships:Relationship[]}|null>(null);
 async function handleFile(file:File){setError('');setReport(null);setParsed(null);setFileName(file.name);try{const buf=await file.arrayBuffer();let data:any[]=[];if(/\.xml$/i.test(file.name))data=xmlToRows(new TextDecoder().decode(buf));else{const wb=XLSX.read(buf,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];data=XLSX.utils.sheet_to_json(ws,{defval:''});}if(!data.length)throw new Error('The selected file contains no member rows.');setRows(data);}catch(e:any){setRows([]);setError(e.message||'Could not parse file.');}}
 function build(){
  const newMembers:Member[]=[];const sourceToId=new Map<string,string>();const nameToId=new Map<string,string>();const errors:string[]=[];
  rows.forEach((r:any,i)=>{const name=text(r.full_name||r.name);if(!name){errors.push(`Row ${i+2}: full_name/name is required.`);return;}const source=text(r.id||r.source_id||r.member_id);if(source&&sourceToId.has(source))errors.push(`Row ${i+2}: duplicate source ID ${source}.`);const dbId=isUuid(source)?source:uuid();if(newMembers.some(m=>m.id===dbId))errors.push(`Row ${i+2}: duplicate ID ${source||dbId}.`);const generation=Number(r.generation_level||1);if(!Number.isInteger(generation)||generation<1)errors.push(`Row ${i+2}: generation_level must be a positive integer.`);const member:Member={id:dbId,full_name:name,date_of_birth:text(r.date_of_birth)||undefined,date_of_death:text(r.date_of_death)||undefined,generation_level:Math.max(1,generation),profession:text(r.profession)||undefined,city:text(r.city)||undefined,country:text(r.country)||'India',latitude:num(r.latitude),longitude:num(r.longitude),photo_url:text(r.photo_url)||'',bio:text(r.bio)||'',phone:text(r.phone)||undefined,email:text(r.email)||undefined,profile_status:'approved',gender:r.gender};newMembers.push(member);if(source)sourceToId.set(source,dbId);nameToId.set(name.toLowerCase(),dbId);});
  if(errors.length)throw new Error(errors.slice(0,10).join('\n'));
  const resolve=(v:any)=>{const s=text(v);if(!s)return undefined;if(sourceToId.has(s))return sourceToId.get(s);if(isUuid(s)&&newMembers.some(m=>m.id===s))return s;return nameToId.get(s.toLowerCase());};
  const rels:Relationship[]=[];const seen=new Set<string>();const add=(a:string|undefined,b:string|undefined,type:Relationship['relationship_type'])=>{if(!a||!b||a===b)return;const key=type==='spouse'?`${type}|${[a,b].sort().join('|')}`:`${type}|${a}|${b}`;if(seen.has(key))return;seen.add(key);rels.push({id:uuid(),person_id:a,related_person_id:b,relationship_type:type});};
  rows.forEach((r:any)=>{const person=resolve(r.id||r.source_id||r.member_id)||resolve(r.full_name||r.name);if(!person)return;['father_id','mother_id','parent_id','father','mother','parent'].forEach(k=>add(resolve(r[k]),person,'parent'));add(person,resolve(r.spouse_id||r.spouse),'spouse');});
  return {members:newMembers,relationships:rels};
 }
 function validate(){setBusy(true);setError('');try{const data=build();const r=validateImportRows(data.members,data.relationships,existingMembers,existingRelationships);setParsed(data);setReport(r);if(r.errors.length)setError(`Import blocked: ${r.errors.length} error(s) must be fixed before importing.`);}catch(e:any){setParsed(null);setReport(null);setError(e.message||'Import validation failed.')}finally{setBusy(false)}}
 function importNow(){if(!parsed||!report||report.errors.length)return;setBusy(true);try{onImport(parsed.members,parsed.relationships);onClose();}catch(e:any){setError(e.message||'Import failed.')}finally{setBusy(false)}}
 return <div className="modal-overlay"><div className="modal"><div className="drawer-head"><h2 style={{margin:0}}>Import hierarchy data</h2><button className="btn small" onClick={onClose}>Close</button></div><p className="page-subtitle">CSV, XLSX, XLS or XML. Source IDs are treated as external references and converted to database UUIDs. P4.1 also checks duplicates, orphan relationships, cycles and generation consistency before writing.</p><div className="dropzone" style={{marginTop:18}}><input type="file" accept=".csv,.xlsx,.xls,.xml" onChange={e=>e.target.files?.[0]&&handleFile(e.target.files[0])}/>{fileName&&<p style={{fontWeight:600,color:'#293449'}}>{fileName}</p>}</div>{error&&<div className="notice danger-text" style={{whiteSpace:'pre-line'}}><XCircle size={15}/> {error}</div>}{rows.length>0&&<div style={{marginTop:18}}><div className="notice">Parsed {rows.length} rows. Previewing the first 5.</div><div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]).slice(0,8).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,5).map((r,i)=><tr key={i}>{Object.keys(rows[0]).slice(0,8).map(k=><td key={k}>{String(r[k]).slice(0,35)}</td>)}</tr>)}</tbody></table></div></div>}{report&&<div className="validation-panel"><div className="validation-summary"><div className={report.errors.length?'validation-bad':'validation-good'}>{report.errors.length?<XCircle size={17}/>:<CheckCircle2 size={17}/>} {report.errors.length?`${report.errors.length} errors`:'No blocking errors'}</div><div className={report.warnings.length?'validation-warn':'validation-good'}>{report.warnings.length?<AlertTriangle size={17}/>:<CheckCircle2 size={17}/>} {report.warnings.length} warnings</div></div>{report.errors.slice(0,8).map((x:any,i:number)=><div className="validation-issue error" key={`e${i}`}><b>{x.code}</b><span>{x.message}</span></div>)}{report.warnings.slice(0,8).map((x:any,i:number)=><div className="validation-issue warning" key={`w${i}`}><b>{x.code}</b><span>{x.message}</span></div>)}{(report.errors.length+report.warnings.length)>16&&<div className="person-meta">Showing the first 16 issues. Fix errors and validate again for the complete result.</div>}</div>}
 <div className="form-actions"><button className="btn" onClick={onClose}>Cancel</button>{!report?<button className="btn primary" disabled={!rows.length||busy} onClick={validate}>{busy?'Validating…':'Validate Import'}</button>:<button className="btn primary" disabled={busy||report.errors.length>0} onClick={importNow}>{busy?'Importing…':'Import Validated Data'}</button>}</div></div></div>
}
