"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,GitBranch,MapPin,ShieldCheck,UserRound} from "lucide-react";
import {supabase} from "../lib/supabase";
import {trackPublicParticipation} from "../lib/remote";

type PublicMember={id:string;full_name:string;generation_level:number;profession?:string;city?:string;country?:string;bio?:string;date_of_death?:string};
const initials=(name:string)=>name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
export default function PublicMemberPage({memberId}:{memberId:string}){
 const [member,setMember]=useState<PublicMember|null>(null),[network,setNetwork]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{if(!supabase)throw new Error("This network is not configured for shared access.");const [m,n]=await Promise.all([supabase.rpc("get_public_family_member",{p_member_id:memberId}),supabase.rpc("get_public_network_info")]);if(m.error)throw m.error;if(n.error)throw n.error;const found=(m.data||[])[0];if(!found)throw new Error("This profile is not public or is no longer available.");setMember(found);setNetwork((n.data||[])[0]);const source=new URLSearchParams(window.location.search).get("source");trackPublicParticipation(source==="qr"?"qr_view":"profile_view",memberId,source||"direct").catch(()=>{})}catch(e:any){setError(e.message||"Could not load this profile.")}finally{setLoading(false)}})()},[memberId]);
 if(loading)return <div className="loading-screen"><GitBranch size={28}/><div><b>Opening profile…</b><div className="page-subtitle">Only public information will be shown</div></div></div>;
 if(error||!member)return <main className="landing"><div className="landing-card"><h1>Profile unavailable</h1><p className="page-subtitle">{error}</p><a className="btn primary" href="/public">View public directory</a></div></main>;
 return <main className="public-profile-page"><div className="public-profile-shell"><a href="/public" className="back-link"><ArrowLeft size={15}/> Public directory</a><article className="card public-profile-card"><div className={`public-profile-avatar ${member.date_of_death?"grayscale":""}`}>{initials(member.full_name)}</div><div><span className="mode-pill shared">Public profile</span><h1>{member.full_name}</h1>{member.date_of_death&&<p className="in-memoriam">Remembered with love</p>}<p className="public-role"><UserRound size={16}/>{member.profession||network?.entity_label||"Member"}</p>{(member.city||member.country)&&<p className="public-role"><MapPin size={16}/>{[member.city,member.country].filter(Boolean).join(", ")}</p>}<p className="public-role"><GitBranch size={16}/>{network?.level_label||"Generation"} {member.generation_level}</p>{member.bio&&<div className="public-bio">{member.bio}</div>}</div></article><div className="card privacy-note"><ShieldCheck size={22}/><div><b>Privacy-respecting public profile</b><p>No phone number, email address, exact location, relationships, or private photos are exposed here.</p></div></div><div className="card public-join"><h3>Are you part of {network?.name||"this network"}?</h3><p>Use your private invitation to claim your profile and help complete the family story.</p><a className="btn primary" href="/">Sign in to the private network</a></div></div></main>;
}
