"use client";
import {useEffect,useState} from 'react';
import {Bell,Heart,ImagePlus,Check,Trash2,Search,Share2} from 'lucide-react';
import {Memory,MemoryReaction,Member,Notification} from '../lib/types';
import {getNetworkRepository} from '../lib/repository';
import {uploadCommunityPhoto,removeStoredMedia} from '../lib/storage';
import {isSupabaseConfigured} from '../lib/supabase';
import {useLanguage} from '../lib/i18n';
import {getNetworkConfig,NetworkSettings} from '../lib/network';
import {fetchNotificationPreferences,saveNotificationPreferences,NotificationPreferences,setMemoryReaction,trackFamilyEngagement} from '../lib/remote';

export default function CommunityHub({members,auth,network,onSelect,onNotify,demoMemories,readOnly=false,showQuietDigest=true}:{members:Member[];auth:any;network?:NetworkSettings|null;onSelect:(m:Member)=>void;onNotify:(x:string)=>void;demoMemories?:Memory[];readOnly?:boolean;showQuietDigest?:boolean}){
 const cfg=getNetworkConfig(network??null);
 const {language}=useLanguage();
 const c=language==='hi'?{title:'परिवार की यादें',subtitle:'परिवार की तस्वीरें, कहानियाँ और नए पल।',share:'याद साझा करें',memories:'कहानियाँ और तस्वीरें',memoryHelp:'एक पारिवारिक पल, कहानी या तस्वीर साझा करें।',search:'यादों में खोजें…',empty:'अभी कोई याद नहीं। पहली याद आप साझा करें।',updates:'नई जानकारी',updatesHelp:'स्वीकृतियाँ और account गतिविधि।',noUpdates:'कोई नई जानकारी नहीं।',close:'बंद करें',about:'किस सदस्य के बारे में',familyMemory:'पूरे परिवार की याद',memoryTitle:'शीर्षक',story:'कहानी',photo:'तस्वीर',visibility:'कौन देख सकता है',cancel:'रद्द करें',save:'याद साझा करें',saving:'सहेज रहे हैं…'}:language==='mr'?{title:'कुटुंबाच्या आठवणी',subtitle:'कौटुंबिक छायाचित्रे, कथा आणि नवीन क्षण.',share:'आठवण सामायिक करा',memories:'कथा आणि छायाचित्रे',memoryHelp:'एक कौटुंबिक क्षण, कथा किंवा छायाचित्र सामायिक करा.',search:'आठवणींमध्ये शोधा…',empty:'अजून आठवणी नाहीत. पहिली आठवण आपण सामायिक करा.',updates:'नवीन माहिती',updatesHelp:'मंजुरी आणि account हालचाल.',noUpdates:'नवीन माहिती नाही.',close:'बंद करा',about:'कोणत्या सदस्याबद्दल',familyMemory:'संपूर्ण कुटुंबाची आठवण',memoryTitle:'शीर्षक',story:'कथा',photo:'छायाचित्र',visibility:'कोण पाहू शकते',cancel:'रद्द करा',save:'आठवण सामायिक करा',saving:'जतन करत आहोत…'}:{title:'Family memories',subtitle:'Photos, stories and new moments from your family.',share:'Share a memory',memories:'Stories and photos',memoryHelp:'Share a family moment, story or photo. Keep it simple and personal.',search:'Search memories…',empty:'No memories yet. Be the first to share one.',updates:'Updates',updatesHelp:'Approvals and account activity.',noUpdates:'No new updates.',close:'Close',about:'About member',familyMemory:'Whole-family memory',memoryTitle:'Title',story:'Story',photo:'Photo',visibility:'Who can see this',cancel:'Cancel',save:'Share memory',saving:'Saving…'};
 const repo=getNetworkRepository();
 const [memories,setMemories]=useState<Memory[]>(demoMemories||[]),[notifications,setNotifications]=useState<Notification[]>([]),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const [prefs,setPrefs]=useState<NotificationPreferences>({digest:'weekly',special_days:true,memories:false,gatherings:true,contributions:true,introductions:true,family_changes:true,preferred_weekday:0}),[prefsOpen,setPrefsOpen]=useState(false);
 const [form,setForm]=useState({member_id:auth?.member_id||'',related_member_ids:[] as string[],title:'',story:'',visibility:'member' as const,photo_url:''});
 const load=async()=>{if(readOnly&&demoMemories){setMemories(demoMemories);setNotifications([]);return;}try{setMemories(await repo.fetchMemories());setNotifications(await repo.fetchNotifications())}catch(e:any){onNotify(e.message||'Could not load community updates.')}};
 useEffect(()=>{load();if(!readOnly)fetchNotificationPreferences().then(setPrefs).catch(()=>{})},[readOnly,demoMemories]);
 const create=async()=>{if(!form.title.trim())return;setBusy(true);let uploaded:string|undefined;try{let photo=form.photo_url;if((document.getElementById('community-photo') as HTMLInputElement)?.files?.[0]) {photo=await uploadCommunityPhoto((document.getElementById('community-photo') as HTMLInputElement).files![0],auth?.id||'anonymous');uploaded=photo;}await repo.createMemory({member_id:form.member_id||undefined,related_member_ids:form.related_member_ids,title:form.title.trim(),story:form.story||undefined,photo_url:photo||undefined,visibility:form.visibility});setForm({member_id:auth?.member_id||'',related_member_ids:[],title:'',story:'',visibility:'member',photo_url:''});setShowForm(false);await load();onNotify('Memory shared with the community.')}catch(e:any){if(uploaded)removeStoredMedia(uploaded,'community-media').catch(()=>{});onNotify(e.message||'Could not create memory.')}finally{setBusy(false)}};
 const mark=async(n:Notification)=>{try{await repo.markNotificationRead(n.id);setNotifications(x=>x.map(v=>v.id===n.id?{...v,read_at:new Date().toISOString()}:v))}catch(e:any){onNotify(e.message||'Could not update notification.')}};
 const react=async(m:Memory,reaction:MemoryReaction)=>{const next=m.my_reaction===reaction?null:reaction;try{if(!readOnly)await setMemoryReaction(m.id,next);setMemories(xs=>xs.map(x=>x.id===m.id?{...x,my_reaction:next||undefined,reaction_counts:{...(x.reaction_counts||{}),[reaction]:Math.max(0,Number(x.reaction_counts?.[reaction]||0)+(next?1:-1))}}:x))}catch(e:any){onNotify(e.message||'Could not save reaction.')}};
 const shareMemory=async(m:Memory)=>{const people=(m.related_member_ids||[]).map(id=>members.find(x=>x.id===id)?.full_name).filter(Boolean).slice(0,3).join(', ');const text=`❤️ ${m.title}${people?`\nWith ${people}`:''}${m.story?`\n\n${m.story.slice(0,240)}`:''}\n\nShared from our family network`;const canNativeShare=typeof navigator.share==='function';try{if(canNativeShare)await navigator.share({title:m.title,text});else{await navigator.clipboard?.writeText(text);onNotify('Memory card copied for WhatsApp.')}if(!readOnly)trackFamilyEngagement('memory_share','memory',m.id,canNativeShare?'native':'copy').catch(()=>{})}catch(e:any){if(e?.name!=='AbortError')onNotify('Could not share this memory.')}};
 const remove=async(id:string)=>{try{const media=memories.find(m=>m.id===id)?.photo_url;await repo.deleteMemory(id);if(media)await removeStoredMedia(media,'community-media').catch(()=>{});setMemories(x=>x.filter(m=>m.id!==id));onNotify('Memory removed.')}catch(e:any){onNotify(e.message||'Could not remove memory.')}};
 const visible=memories.filter(m=>{const q=query.toLowerCase();if(!q)return true;const owner=m.member_id?members.find(x=>x.id===m.member_id):undefined;return `${m.title} ${m.story||''} ${owner?.full_name||''}`.toLowerCase().includes(q)});
 return <section><div className="page-head"><div><h1 className="page-title">{c.title}</h1><p className="page-subtitle">{readOnly?"A showcase of stories connected to real people and moments in the sample family.":c.subtitle}</p></div><div className="card-actions">{!readOnly&&<button className="btn primary" onClick={()=>setShowForm(true)}><Heart size={15}/> {c.share}</button>}</div></div>
  <div className="community-grid">
   <div className="card community-main"><div className="profile-section-head"><div><h3 style={{margin:0}}>{c.memories}</h3><p className="page-subtitle">{c.memoryHelp}</p></div></div><div className="search-bar" style={{marginTop:12}}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.search}/></div>{visible.length===0&&<div className="empty">{c.empty}</div>}<div className="memory-grid">{visible.map(m=>{const owner=m.member_id?members.find(x=>x.id===m.member_id):undefined;return <article className="memory-card" key={m.id}>{m.photo_url&&<img src={m.photo_url} alt=""/>}<div className="memory-body"><div className="memory-title">{m.title}</div>{m.story&&<div className="memory-story">{m.story}</div>}<div className="person-meta">{(m.related_member_ids?.length?m.related_member_ids.map(id=>members.find(x=>x.id===id)?.full_name).filter(Boolean).slice(0,3).join(', '):owner?.full_name)||''}{(m.related_member_ids?.length||owner)?' · ':''}{new Date(m.created_at).toLocaleDateString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN')}</div><div className="memory-reactions">{([['heart','❤️'],['smile','😊'],['pray','🙏'],['celebrate','🎉']] as [MemoryReaction,string][]).map(([r,emoji])=><button key={r} className={m.my_reaction===r?'active':''} onClick={()=>react(m,r)} title={readOnly?'Try a reaction — sample only, nothing is saved':'React'}><span>{emoji}</span>{Number(m.reaction_counts?.[r]||0)>0&&<small>{m.reaction_counts?.[r]}</small>}</button>)}</div><div className="memory-card-actions"><button className="btn tiny" onClick={()=>shareMemory(m)} title="Share a privacy-safe memory card"><Share2 size={12}/> Share</button>{(m.created_by===auth?.id||auth?.role==='admin')&&<button className="btn tiny danger" onClick={()=>remove(m.id)}><Trash2 size={12}/></button>}</div></div></article>})}</div></div>
   <div className="card community-side"><div className="profile-section-head"><div><h3 style={{margin:0}}>{c.updates}</h3><p className="page-subtitle">{c.updatesHelp}</p></div><Bell size={18}/></div>{notifications.length===0&&<div className="empty">{c.noUpdates}</div>}{notifications.map(n=><button key={n.id} className={`notification-row ${n.read_at?'read':''}`} onClick={()=>mark(n)}><span className="notification-dot">{n.read_at?<Check size={11}/>:''}</span><span><strong>{n.title}</strong><small>{n.body||''}</small><em>{new Date(n.created_at).toLocaleString(language==='hi'?'hi-IN':language==='mr'?'mr-IN':'en-IN')}</em></span></button>)}</div>
  </div>
  {showQuietDigest&&!readOnly&&<div className="card quiet-preferences"><button className="quiet-preferences-head" onClick={()=>setPrefsOpen(x=>!x)}><Bell size={17}/><span><b>Quiet family digest</b><small>One useful summary instead of a stream of alerts.</small></span><em>{prefs.digest==='off'?'Off':`${prefs.digest} digest`}</em></button>{prefsOpen&&<div className="quiet-preferences-body"><div className="digest-pref-grid"><label>Digest<select className="select" value={prefs.digest} onChange={e=>setPrefs({...prefs,digest:e.target.value as NotificationPreferences['digest']})}><option value="off">Off</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label>{prefs.digest==='weekly'&&<label>Preferred day<select className="select" value={prefs.preferred_weekday} onChange={e=>setPrefs({...prefs,preferred_weekday:Number(e.target.value)})}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label>}</div><div className="digest-pref-checks"><label><input type="checkbox" checked={prefs.special_days} onChange={e=>setPrefs({...prefs,special_days:e.target.checked})}/> Birthdays & special days</label><label><input type="checkbox" checked={prefs.memories} onChange={e=>setPrefs({...prefs,memories:e.target.checked})}/> New family memories</label><label><input type="checkbox" checked={prefs.gatherings} onChange={e=>setPrefs({...prefs,gatherings:e.target.checked})}/> Gathering updates</label><label><input type="checkbox" checked={prefs.family_changes} onChange={e=>setPrefs({...prefs,family_changes:e.target.checked})}/> New family members</label><label><input type="checkbox" checked={prefs.contributions} onChange={e=>setPrefs({...prefs,contributions:e.target.checked})}/> Small ways I can help</label><label><input type="checkbox" checked={prefs.introductions} onChange={e=>setPrefs({...prefs,introductions:e.target.checked})}/> Trusted introductions</label></div><div className="digest-pref-note">The app stores your preference now. External email/push delivery remains optional infrastructure; the same digest is always available privately on Home.</div><button className="btn primary small" onClick={async()=>{try{await saveNotificationPreferences(prefs);onNotify('Quiet digest preferences saved.');setPrefsOpen(false)}catch(e:any){onNotify(e.message||'Could not save preferences.')}}}>Save preferences</button></div>}</div>}
  {showForm&&!readOnly&&<div className="modal-overlay" onMouseDown={(event)=>event.target===event.currentTarget&&setShowForm(false)}><div className="modal" role="dialog" aria-modal="true" style={{maxWidth:600}}><div className="drawer-head"><h2 style={{margin:0}}>{c.share}</h2><button className="btn small" onClick={()=>setShowForm(false)}>{c.close}</button></div><p className="page-subtitle">{c.memoryHelp}</p><div className="form-grid"><div className="field full"><label>{c.about}</label><select className="select" value={form.member_id} onChange={e=>setForm({...form,member_id:e.target.value})} disabled={auth?.role!=='admin'}><option value="">{c.familyMemory}</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></div><div className="field full"><label>{language==='hi'?'इस याद में कौन है?':language==='mr'?'या आठवणीत कोण आहे?':'Who is part of this memory?'}</label><select className="select multi" multiple value={form.related_member_ids} onChange={e=>setForm({...form,related_member_ids:Array.from(e.target.selectedOptions,x=>x.value)})}>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><small className="field-help">{language==='hi'?'एक या कई रिश्तेदार चुनें।':language==='mr'?'एक किंवा अनेक नातेवाईक निवडा.':'Choose one or more relatives. This helps the memory appear with everyone involved.'}</small></div><div className="field full"><label>{c.memoryTitle}</label><input className="text-input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="field full"><label>{c.story}</label><textarea className="text-input" rows={5} value={form.story} onChange={e=>setForm({...form,story:e.target.value})}/></div><div className="field"><label>{c.photo}</label>{cfg.photo_upload_enabled?<><input id="community-photo" className="text-input" type="file" accept="image/jpeg,image/png,image/webp" disabled={!isSupabaseConfigured}/><small className="field-help">Images are automatically resized/compressed to fit the family limit (maximum 100 KB).</small></>:<small className="field-help">Photo uploads are disabled for this family. Share the story without an image.</small>}</div><div className="field"><label>{c.visibility}</label><select className="select" value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value as any})}><option value="public">Public</option><option value="member">Members</option>{auth?.role==='admin'&&<option value="admin">Admins</option>}</select></div></div><div className="form-actions"><button className="btn" onClick={()=>setShowForm(false)}>{c.cancel}</button><button className="btn primary" disabled={busy||!form.title.trim()} onClick={create}>{busy?c.saving:c.save}</button></div></div></div>}
 </section>
}
