"use client";
import {useEffect,useMemo,useState} from "react";
import {Check,Clipboard,GitMerge,Link2,Plus,RefreshCw,Send,ShieldCheck,UsersRound,X} from "lucide-react";
import {commitFamilyIntakeBranch,createFamilyIntakeLink,createFamilyIntakeSession,decideFamilyIntakeMatch,fetchFamilyIntakeDashboard,revokeFamilyIntakeLink} from "../lib/remote";
import type {FamilyIntakeDashboard} from "../lib/family-intake-types";

const empty:FamilyIntakeDashboard={sessions:[],branches:[],people:[],candidates:[],conflicts:[],metrics:{links_opened:0,submissions:0,people_reported:0,branches_committed:0}};
export default function FamilyIntakeAdmin({familyName,onClose,onCommitted,onNotify}:{familyName:string;onClose:()=>void;onCommitted:()=>Promise<void>|void;onNotify:(m:string)=>void}){
 const [data,setData]=useState<FamilyIntakeDashboard>(empty),[busy,setBusy]=useState(false),[label,setLabel]=useState(""),[sessionTitle,setSessionTitle]=useState("Build our family together"),[rawLink,setRawLink]=useState(""),[error,setError]=useState("");
 const load=async()=>{try{setData(await fetchFamilyIntakeDashboard())}catch(e:any){setError(e.message||"Could not load family intake.")}};
 useEffect(()=>{load()},[]);
 const activeSession=data.sessions.find(s=>s.status!=="closed"&&s.status!=="completed")||data.sessions[0];
 const waiting=data.branches.filter(b=>b.status==="submitted");
 const peopleById=useMemo(()=>Object.fromEntries(data.people.map(p=>[p.id,p])),[data.people]);
 const createSession=async()=>{setBusy(true);setError("");try{await createFamilyIntakeSession(sessionTitle);await load();onNotify("Family contribution intake created.")}catch(e:any){setError(e.message||"Could not create intake.")}finally{setBusy(false)}};
 const createLink=async()=>{if(!activeSession)return;setBusy(true);setError("");try{const token=await createFamilyIntakeLink(activeSession.id,label);const url=`${window.location.origin}/contribute/${token}`;setRawLink(url);setLabel("");await load();}catch(e:any){setError(e.message||"Could not create contribution link.")}finally{setBusy(false)}};
 const copy=async()=>{if(!rawLink)return;await navigator.clipboard.writeText(rawLink);onNotify("Contribution link copied.")};
 const decide=async(id:string,d:"same"|"different"|"not_sure")=>{setBusy(true);try{await decideFamilyIntakeMatch(id,d);await load()}catch(e:any){onNotify(e.message||"Could not save match decision.")}finally{setBusy(false)}};
 const commit=async(id:string)=>{setBusy(true);try{const r=await commitFamilyIntakeBranch(id);await load();await onCommitted();onNotify(`Branch added: ${r.created_people} new, ${r.matched_people} matched, ${r.relationships} relationships.`)}catch(e:any){onNotify(e.message||"Could not add this branch yet.")}finally{setBusy(false)}};
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal intake-admin-modal"><div className="modal-head"><div><span className="warm-kicker"><UsersRound size={13}/> S3-A1 · Build together</span><h2>Collect family branches</h2><p>Share simple forms first. Nothing enters {familyName} until you review and approve it here.</p></div><button className="icon-button" onClick={onClose}><X/></button></div>
   <div className="intake-admin-stats"><div><b>{data.metrics.links_opened}</b><span>link opens</span></div><div><b>{data.metrics.submissions}</b><span>branches submitted</span></div><div><b>{data.metrics.people_reported}</b><span>people reported</span></div><div><b>{data.metrics.branches_committed}</b><span>branches added</span></div></div>
   {!activeSession?<div className="card intake-create-session"><h3>Start distributed family intake</h3><p>Create one collection session, then make a separate secure link for each branch representative.</p><label><span>Intake title</span><input className="text-input" value={sessionTitle} onChange={e=>setSessionTitle(e.target.value)}/></label><button className="btn primary" disabled={busy} onClick={createSession}><Plus size={15}/> Start intake</button></div>:<>
     <div className="card intake-share-box"><div><h3>Invite 3–5 branch representatives</h3><p>Use a separate link for each person. The link lets them contribute only; it does not reveal the family tree.</p></div><div className="intake-link-create"><input className="text-input" value={label} onChange={e=>setLabel(e.target.value)} placeholder="e.g. Ramesh uncle · paternal branch"/><button className="btn primary" disabled={busy} onClick={createLink}><Link2 size={15}/> Create link</button></div>{rawLink&&<div className="intake-generated-link"><input className="text-input" readOnly value={rawLink}/><button className="btn" onClick={copy}><Clipboard size={15}/> Copy</button></div>}<div className="intake-privacy-note"><ShieldCheck/> Secure random tokens are stored only as hashes. Family code and contribution link do not grant private-family read access.</div></div>
     <div className="intake-admin-section"><div className="section-title"><div><h3>Branches</h3><p className="page-subtitle">Submitted branches stay staged until you approve them.</p></div><button className="btn small" onClick={load}><RefreshCw size={14}/> Refresh</button></div>{data.branches.length===0?<div className="empty compact">Create your first representative link above.</div>:data.branches.map(b=>{const branchPeople=data.people.filter(p=>p.access_id===b.id);const branchCandidates=data.candidates.filter(c=>branchPeople.some(p=>p.id===c.staged_person_id)&&(c.status==="open"||c.status==="unsure"));return <div className={`card intake-branch-card ${b.status}`} key={b.id}><div className="intake-branch-head"><span><b>{b.representative_label||"Family representative"}</b><small>{b.people_count} people · {b.relationship_count} relationships · {b.status}</small></span>{b.status==="active"&&<button className="btn small" disabled={busy} onClick={async()=>{await revokeFamilyIntakeLink(b.id);await load()}}>Revoke</button>}</div>{branchPeople.length>0&&<div className="intake-branch-people">{branchPeople.map(p=><span key={p.id}>{p.full_name}<small>{p.role_from_anchor?.replaceAll("_"," ")}{p.birth_year?` · ${p.birth_year}`:""}</small></span>)}</div>}{branchCandidates.length>0&&<div className="intake-match-review"><h4>Possible overlaps</h4>{branchCandidates.map(c=>{const p=peopleById[c.staged_person_id];return <div className="intake-match-row" key={c.id}><div><b>{p?.full_name}</b><span>may be <strong>{c.candidate_name}</strong></span><small>{c.score}% confidence · {c.confidence_band}{c.status==="unsure"?" · marked not sure":""}</small></div><div className="intake-match-actions"><button className="btn small" disabled={busy} onClick={()=>decide(c.id,"same")}><Check size={13}/> Same</button><button className="btn small" disabled={busy} onClick={()=>decide(c.id,"different")}>Different</button><button className="btn small" disabled={busy} onClick={()=>decide(c.id,"not_sure")}>Not sure</button></div></div>})}</div>}{b.status==="submitted"&&<div className="intake-branch-commit"><button className="btn primary" disabled={busy||branchCandidates.some(c=>c.confidence_band!=="low")} onClick={()=>commit(b.id)}><GitMerge size={15}/> Add reviewed branch to family</button>{branchCandidates.some(c=>c.confidence_band!=="low")&&<small>Resolve medium/high possible overlaps first. Low-confidence name-only suggestions do not block commit.</small>}</div>}</div>})}</div>
   </>}
   {data.conflicts.length>0&&<div className="notice"><b>{data.conflicts.length} preserved fact conflict{data.conflicts.length>1?"s":""}.</b> Existing family facts were not silently overwritten. These remain available for later reconciliation.</div>}
   {error&&<div className="notice danger-text">{error}</div>}
   <div className="modal-actions"><button className="btn" onClick={onClose}>Close</button>{waiting.length>0&&<span className="intake-waiting"><Send size={14}/> {waiting.length} branch{waiting.length>1?"es":""} waiting</span>}</div>
 </section></div>;
}
