"use client";
import {useEffect,useMemo,useState} from "react";
import {BadgeIndianRupee,CalendarRange,History,Save,ShieldCheck,UsersRound} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../core/network-os/contracts";
import {addFcaFinanceEntry,assignFcaRole,fetchFcaAdminSnapshot,setFcaFamilyMembership,updateFcaSettings,upsertFcaMembershipYear,type FcaAdminSnapshot} from "../capabilities/template-product/remote";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";

export default function FamilyAssociationAdminPanel({entities,onNotify}:{entities:NetworkAffiliatedEntity[];onNotify:(s:string)=>void}){
 const [data,setData]=useState<FcaAdminSnapshot|null>(null),[busy,setBusy]=useState(false);
 const load=async()=>{try{setData(await fetchFcaAdminSnapshot())}catch(e:any){onNotify(e.message||"Could not load annual association controls.")}};useEffect(()=>{void load()},[]);
 const families=useMemo(()=>entities.filter(e=>e.entity.kind==="family"),[entities]),people=useMemo(()=>entities.filter(e=>e.entity.kind==="person"),[entities]);
 const [settings,setSettings]=useState<any>({dependent_age_limit:22,grace_period_days:30,max_auto_children:2,onboarding_policy:"join_review_later",finance_visibility:"admins"});
 useEffect(()=>{if(data?.settings)setSettings((x:any)=>({...x,...data.settings}))},[data]);
 const [year,setYear]=useState({label:"2026–27",startDate:"2026-04-01",endDate:"2027-03-31",familyFee:"",grace:"30",status:"open"});
 const [membership,setMembership]=useState({yearId:"",familyId:"",representativeId:"",status:"active",paymentStatus:"paid",amountPaid:"",reference:""});
 const [role,setRole]=useState({yearId:"",personId:"",roleId:"",startsOn:"",endsOn:"",notes:""});
 const [finance,setFinance]=useState({yearId:"",entryType:"membership_collection",amount:"",description:"",visibility:"admins"});
 const activeYear=data?.years?.find((y:any)=>y.status==="open")||data?.years?.[0];
 useEffect(()=>{if(activeYear){setMembership(x=>({...x,yearId:x.yearId||activeYear.id}));setRole(x=>({...x,yearId:x.yearId||activeYear.id}));setFinance(x=>({...x,yearId:x.yearId||activeYear.id}))}},[activeYear?.id]);
 const run=async(fn:()=>Promise<any>,msg:string)=>{setBusy(true);try{await fn();onNotify(msg);await load()}catch(e:any){onNotify(e.message||"Could not save.")}finally{setBusy(false)}};
 const totalCollected=(data?.finance||[]).filter((x:any)=>Number(x.amount)>0).reduce((n:number,x:any)=>n+Number(x.amount||0),0),totalSpent=Math.abs((data?.finance||[]).filter((x:any)=>Number(x.amount)<0||["expense","event_allocation","good_cause"].includes(x.entry_type)).reduce((n:number,x:any)=>n+Number(x.amount||0),0));
 if(!data)return <NetworkEmpty title="Loading annual operations" description="Membership, governance and finance history are being loaded."/>;
 return <div className="fca-admin-panel"><NetworkSectionHead kicker={<><ShieldCheck size={12}/> Family Community operations</>} title="Manage Community" description="Official membership, annual-cycle, governance and finance records are controlled here—not in ordinary member profile editing."/>
  <div className="network-metric-grid"><NetworkMetric value={families.length} label="Families"/><NetworkMetric value={people.length} label="People"/><NetworkMetric value={data.memberships.filter((m:any)=>m.status==="active").length} label="Active memberships"/><NetworkMetric value={`₹${totalCollected.toLocaleString("en-IN")}`} label="Ledger inflow"/></div>
  <div className="fca-admin-grid"><section className="card"><span className="warm-kicker"><CalendarRange size={12}/> Annual policy</span><h3>Membership defaults</h3><div className="form-grid"><label className="field"><span>Dependent age limit</span><input className="text-input" type="number" value={settings.dependent_age_limit} onChange={e=>setSettings({...settings,dependent_age_limit:Number(e.target.value)})}/></label><label className="field"><span>Grace period (days)</span><input className="text-input" type="number" value={settings.grace_period_days} onChange={e=>setSettings({...settings,grace_period_days:Number(e.target.value)})}/></label><label className="field"><span>Auto-approved children</span><input className="text-input" type="number" value={settings.max_auto_children} onChange={e=>setSettings({...settings,max_auto_children:Number(e.target.value)})}/></label><label className="field"><span>New family onboarding</span><select className="select" value={settings.onboarding_policy} onChange={e=>setSettings({...settings,onboarding_policy:e.target.value})}><option value="join_review_later">Join now, admin reviews later</option><option value="approval_required">Approval required</option><option value="invitation_only">Invitation only</option></select></label><label className="field"><span>Finance visibility</span><select className="select" value={settings.finance_visibility} onChange={e=>setSettings({...settings,finance_visibility:e.target.value})}><option value="admins">Admins only</option><option value="members">Members</option><option value="highlighted">Highlighted summary</option></select></label></div><button className="btn primary" disabled={busy} onClick={()=>run(()=>updateFcaSettings({dependentAgeLimit:Number(settings.dependent_age_limit),gracePeriodDays:Number(settings.grace_period_days),maxAutoChildren:Number(settings.max_auto_children),onboardingPolicy:settings.onboarding_policy,financeVisibility:settings.finance_visibility}),"Community policy updated.")}><Save size={14}/> Save policy</button></section>
  <section className="card"><span className="warm-kicker"><CalendarRange size={12}/> April–March</span><h3>Create membership year</h3><div className="form-grid"><label className="field"><span>Year label</span><input className="text-input" value={year.label} onChange={e=>setYear({...year,label:e.target.value})}/></label><label className="field"><span>Family fee</span><input className="text-input" type="number" value={year.familyFee} onChange={e=>setYear({...year,familyFee:e.target.value})}/></label><label className="field"><span>Start</span><input className="text-input" type="date" value={year.startDate} onChange={e=>setYear({...year,startDate:e.target.value})}/></label><label className="field"><span>End</span><input className="text-input" type="date" value={year.endDate} onChange={e=>setYear({...year,endDate:e.target.value})}/></label><label className="field"><span>Grace</span><input className="text-input" type="number" value={year.grace} onChange={e=>setYear({...year,grace:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!year.label||!year.familyFee} onClick={()=>run(()=>upsertFcaMembershipYear({label:year.label,startDate:year.startDate,endDate:year.endDate,familyFee:Number(year.familyFee),gracePeriodDays:Number(year.grace),status:year.status}),"Membership year saved.")}>Create / update year</button><div className="fca-history-list">{data.years.map((y:any)=><div key={y.id}><b>{y.label}</b><span>₹{Number(y.family_fee).toLocaleString("en-IN")} / family</span><small>{y.start_date} → {y.end_date} · {y.status}</small></div>)}</div></section>
  <section className="card"><span className="warm-kicker"><UsersRound size={12}/> Family membership</span><h3>Renew / mark payment</h3><div className="form-grid"><label className="field full"><span>Membership year</span><select className="select" value={membership.yearId} onChange={e=>setMembership({...membership,yearId:e.target.value})}><option value="">Select</option>{data.years.map((y:any)=><option value={y.id} key={y.id}>{y.label}</option>)}</select></label><label className="field"><span>Family</span><select className="select" value={membership.familyId} onChange={e=>setMembership({...membership,familyId:e.target.value})}><option value="">Select</option>{families.map(f=><option value={f.entity.id} key={f.entity.id}>{f.entity.label}</option>)}</select></label><label className="field"><span>Representative</span><select className="select" value={membership.representativeId} onChange={e=>setMembership({...membership,representativeId:e.target.value})}><option value="">Select</option>{people.map(p=><option value={p.entity.id} key={p.entity.id}>{p.entity.label}</option>)}</select></label><label className="field"><span>Status</span><select className="select" value={membership.status} onChange={e=>setMembership({...membership,status:e.target.value})}>{["pending","active","grace","inactive","removed","transferred"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Payment</span><select className="select" value={membership.paymentStatus} onChange={e=>setMembership({...membership,paymentStatus:e.target.value})}>{["unpaid","paid","waived","partial","not_required"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Amount paid</span><input className="text-input" type="number" value={membership.amountPaid} onChange={e=>setMembership({...membership,amountPaid:e.target.value})}/></label><label className="field"><span>Reference</span><input className="text-input" value={membership.reference} onChange={e=>setMembership({...membership,reference:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!membership.yearId||!membership.familyId} onClick={()=>run(()=>setFcaFamilyMembership({yearId:membership.yearId,familyEntityId:membership.familyId,representativeEntityId:membership.representativeId||null,status:membership.status,paymentStatus:membership.paymentStatus,amountPaid:Number(membership.amountPaid||0),paymentReference:membership.reference}),"Family membership updated.")}>Save membership</button></section>
  <section className="card"><span className="warm-kicker"><History size={12}/> Leadership history</span><h3>Assign controlled role</h3><div className="form-grid"><label className="field"><span>Year</span><select className="select" value={role.yearId} onChange={e=>setRole({...role,yearId:e.target.value})}><option value="">Select</option>{data.years.map((y:any)=><option value={y.id} key={y.id}>{y.label}</option>)}</select></label><label className="field"><span>Person</span><select className="select" value={role.personId} onChange={e=>setRole({...role,personId:e.target.value})}><option value="">Select</option>{people.map(p=><option value={p.entity.id} key={p.entity.id}>{p.entity.label}</option>)}</select></label><label className="field"><span>Designation</span><select className="select" value={role.roleId} onChange={e=>setRole({...role,roleId:e.target.value})}><option value="">Select</option>{data.roles.map((r:any)=><option value={r.id} key={r.id}>{r.label}{r.portfolio?` — ${r.portfolio}`:""}</option>)}</select></label><label className="field"><span>Starts</span><input className="text-input" type="date" value={role.startsOn} onChange={e=>setRole({...role,startsOn:e.target.value})}/></label><label className="field"><span>Ends</span><input className="text-input" type="date" value={role.endsOn} onChange={e=>setRole({...role,endsOn:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!role.personId||!role.roleId} onClick={()=>run(()=>assignFcaRole({yearId:role.yearId||null,personEntityId:role.personId,roleCatalogId:role.roleId,startsOn:role.startsOn||null,endsOn:role.endsOn||null,notes:role.notes}),"Leadership history updated.")}>Assign role</button><div className="fca-history-list">{data.role_history.slice(0,8).map((h:any)=><div key={h.id}><b>{h.person_label}</b><span>{h.role_label}{h.portfolio?` · ${h.portfolio}`:""}</span><small>{h.year_label||"Historical"}</small></div>)}</div></section>
  <section className="card"><span className="warm-kicker"><BadgeIndianRupee size={12}/> Annual fund</span><h3>Finance ledger</h3><div className="form-grid"><label className="field"><span>Year</span><select className="select" value={finance.yearId} onChange={e=>setFinance({...finance,yearId:e.target.value})}><option value="">Select</option>{data.years.map((y:any)=><option value={y.id} key={y.id}>{y.label}</option>)}</select></label><label className="field"><span>Entry type</span><select className="select" value={finance.entryType} onChange={e=>setFinance({...finance,entryType:e.target.value})}>{["opening_balance","membership_collection","donation","event_contribution","sponsorship","event_allocation","good_cause","expense","carry_forward","adjustment"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className="field"><span>Amount</span><input className="text-input" type="number" value={finance.amount} onChange={e=>setFinance({...finance,amount:e.target.value})}/></label><label className="field"><span>Visibility</span><select className="select" value={finance.visibility} onChange={e=>setFinance({...finance,visibility:e.target.value})}><option value="admins">Admins only</option><option value="members">Members</option><option value="highlighted">Highlighted</option></select></label><label className="field full"><span>Description</span><input className="text-input" value={finance.description} onChange={e=>setFinance({...finance,description:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!finance.yearId||!finance.amount} onClick={()=>run(()=>addFcaFinanceEntry({yearId:finance.yearId,entryType:finance.entryType,amount:Number(finance.amount),description:finance.description,visibility:finance.visibility}),"Finance entry added.")}>Add ledger entry</button><p className="fca-finance-note">Current ledger view: ₹{totalCollected.toLocaleString("en-IN")} inflow · ₹{totalSpent.toLocaleString("en-IN")} allocated/spent. This is an operating ledger, not payment processing/accounting.</p></section></div>
 </div>
}
