"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Building2,CalendarClock,DoorOpen,HardHat,PhoneCall,Plus,ShieldCheck,UsersRound,Wrench} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../core/network-os/contracts";
import {addHsAssetService,authorizeHsStaffUnit,createHsMoveRequest,createHsRenovationRequest,createHsVisitor,fetchHsSecuritySnapshot,reviewHsOperationalRequest,updateHsVisitorStatus,upsertHsAsset,upsertHsCompliance,upsertHsEmergencyContact,upsertHsStaff,type HsSecuritySnapshot} from "../verticals/housing-society/runtime/security-remote";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";
const EMPTY:HsSecuritySnapshot={isSecurityOperator:false,visitors:[],staff:[],moveRequests:[],renovations:[],assets:[],compliance:[],emergencyContacts:[]};
const today=()=>new Date().toISOString().slice(0,10),soon=()=>new Date(Date.now()+86400000).toISOString().slice(0,16);
export default function HousingSocietySecurityPanel({isAdmin,demo=false,entities,onNotify}:{isAdmin:boolean;demo?:boolean;entities:NetworkAffiliatedEntity[];onNotify:(s:string)=>void}){
 const units=useMemo(()=>entities.filter(e=>e.entity.kind==="unit"),[entities]);const [data,setData]=useState(EMPTY),[busy,setBusy]=useState(false);
 const [unitId,setUnitId]=useState(""),[visitor,setVisitor]=useState(""),[visitType,setVisitType]=useState("guest"),[expectedAt,setExpectedAt]=useState(soon());
 const [moveType,setMoveType]=useState<"move_in"|"move_out">("move_in"),[moveDate,setMoveDate]=useState(today());
 const [renoTitle,setRenoTitle]=useState(""),[renoStart,setRenoStart]=useState(today()),[renoEnd,setRenoEnd]=useState("");
 const [staffName,setStaffName]=useState(""),[staffType,setStaffType]=useState("maid"),[staffPhone,setStaffPhone]=useState(""),[staffUnit,setStaffUnit]=useState(""),[selectedStaff,setSelectedStaff]=useState("");
 const [assetCode,setAssetCode]=useState("LIFT-1"),[assetName,setAssetName]=useState("Tower A Lift"),[assetCategory,setAssetCategory]=useState("Lift"),[assetLocation,setAssetLocation]=useState("Tower A"),[selectedAsset,setSelectedAsset]=useState(""),[nextService,setNextService]=useState("");
 const [compCategory,setCompCategory]=useState("Fire Safety"),[compTitle,setCompTitle]=useState("Fire equipment inspection"),[compDue,setCompDue]=useState("");
 const [ecCategory,setEcCategory]=useState("Emergency"),[ecLabel,setEcLabel]=useState("Society Security"),[ecPhone,setEcPhone]=useState("");
 const load=async()=>{if(demo){setData({isSecurityOperator:false,visitors:[{id:"v1",unitLabel:"A-101",visitorName:"Guest of A-101",visitType:"guest",expectedAt:"2026-09-08T19:00:00+05:30",status:"expected"}],staff:[],moveRequests:[{id:"m1",unitLabel:"B-304",moveType:"move_in",scheduledOn:"2026-09-15",status:"approved"}],renovations:[{id:"r1",unitLabel:"A-402",title:"Kitchen renovation",startsOn:"2026-09-10",status:"approved",nocReference:"NOC-2026-17"}],assets:[{id:"a1",assetCode:"LIFT-A1",name:"Tower A Lift",category:"Lift",location:"Tower A",status:"active",warrantyUntil:"2027-03-31",nextServiceOn:"2026-09-20"}],compliance:[{id:"c1",category:"Fire Safety",title:"Fire extinguisher inspection",dueOn:"2026-09-30",status:"open",visibility:"members"}],emergencyContacts:[{id:"e1",category:"Emergency",label:"Society Security",phone:"020-40000000",priority:1}]});return}try{setData(await fetchHsSecuritySnapshot())}catch(e:any){onNotify(e.message||"Could not load security and compliance.")}};
 useEffect(()=>{load()},[]);const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);try{await fn();onNotify(ok);await load()}catch(e:any){onNotify(e.message||"Could not save operational change.")}finally{setBusy(false)}};
 const expiring=data.compliance.filter(c=>c.dueOn&&new Date(c.dueOn).getTime()<=Date.now()+30*86400000&&c.status==="open");
 return <div className="hs5-security"><NetworkSectionHead kicker={<><ShieldCheck size={12}/> HS-5 security & compliance</>} title="Security, approvals, assets & compliance" description="Resident self-service is flat-scoped; guards/facility operators can receive narrow operational access without becoming society admins."/>
 <section className="network-metric-grid"><NetworkMetric value={data.visitors.filter(v=>v.status==="inside").length} label="Visitors inside"/><NetworkMetric value={data.assets.length} label="Society assets"/><NetworkMetric value={expiring.length} label="Compliance due ≤30d"/><NetworkMetric value={data.emergencyContacts.length} label="Emergency contacts"/></section>
 <section className="card"><NetworkSectionHead kicker={<><PhoneCall size={12}/> Emergency</>} title="Emergency contacts" description="Member-visible society, fire, police, hospital and utility contacts."/>{data.emergencyContacts.length?<div className="hs2-list">{data.emergencyContacts.map(e=><div key={e.id}><PhoneCall/><span><b>{e.label}</b><small>{e.category} · {e.phone}</small></span></div>)}</div>:<NetworkEmpty icon={<PhoneCall/>} title="No emergency contacts" description="Committee can publish critical contacts here."/>}</section>
 <div className="hs2-admin-grid"><section className="card"><h3>Visitor pre-approval</h3><div className="stack-form"><select className="select" value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Select my flat</option>{units.map(u=><option key={u.entity.id} value={u.entity.id}>{u.entity.label}</option>)}</select><input className="text-input" value={visitor} onChange={e=>setVisitor(e.target.value)} placeholder="Visitor name"/><select className="select" value={visitType} onChange={e=>setVisitType(e.target.value)}><option value="guest">Guest</option><option value="delivery">Delivery</option><option value="service">Service</option><option value="cab">Cab</option><option value="other">Other</option></select><input className="text-input" type="datetime-local" value={expectedAt} onChange={e=>setExpectedAt(e.target.value)}/><button className="btn primary" disabled={busy||demo||!unitId||visitor.trim().length<2} onClick={()=>run(()=>createHsVisitor({unitId,visitorName:visitor,visitType,expectedAt}),"Visitor pre-approved.")}><DoorOpen size={14}/> Add visitor</button></div><div className="hs2-list">{data.visitors.slice(0,8).map(v=><div key={v.id}><DoorOpen/><span><b>{v.visitorName} · {v.unitLabel}</b><small>{v.visitType} · {v.status}{v.expectedAt?` · ${new Date(v.expectedAt).toLocaleString()}`:""}</small></span>{data.isSecurityOperator&&v.status==="expected"&&<button className="btn small" onClick={()=>run(()=>updateHsVisitorStatus(v.id,"inside"),"Visitor checked in.")}>Check in</button>}{data.isSecurityOperator&&v.status==="inside"&&<button className="btn small" onClick={()=>run(()=>updateHsVisitorStatus(v.id,"exited"),"Visitor checked out.")}>Check out</button>}</div>)}</div></section>
 <section className="card"><h3>Move-in / move-out & renovation</h3><div className="stack-form"><select className="select" value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Select flat</option>{units.map(u=><option key={u.entity.id} value={u.entity.id}>{u.entity.label}</option>)}</select><select className="select" value={moveType} onChange={e=>setMoveType(e.target.value as any)}><option value="move_in">Move in</option><option value="move_out">Move out</option></select><input className="text-input" type="date" value={moveDate} onChange={e=>setMoveDate(e.target.value)}/><button className="btn" disabled={busy||demo||!unitId} onClick={()=>run(()=>createHsMoveRequest({unitId,moveType,scheduledOn:moveDate}),"Move request submitted.")}>Submit move request</button><input className="text-input" value={renoTitle} onChange={e=>setRenoTitle(e.target.value)} placeholder="Renovation / work title"/><input className="text-input" type="date" value={renoStart} onChange={e=>setRenoStart(e.target.value)}/><input className="text-input" type="date" value={renoEnd} onChange={e=>setRenoEnd(e.target.value)}/><button className="btn" disabled={busy||demo||!unitId||renoTitle.trim().length<3} onClick={()=>run(()=>createHsRenovationRequest({unitId,title:renoTitle,startsOn:renoStart,endsOn:renoEnd||null}),"Renovation/NOC request submitted.")}><HardHat size={14}/> Request approval</button></div></section></div>
 {isAdmin&&<><div className="hs2-admin-grid"><section className="card"><h3>Domestic staff register</h3><div className="stack-form"><input className="text-input" value={staffName} onChange={e=>setStaffName(e.target.value)} placeholder="Staff name"/><select className="select" value={staffType} onChange={e=>setStaffType(e.target.value)}><option>maid</option><option>driver</option><option>cook</option><option>nanny</option><option>caregiver</option><option>cleaner</option><option>other</option></select><input className="text-input" value={staffPhone} onChange={e=>setStaffPhone(e.target.value)} placeholder="Phone"/><button className="btn" disabled={busy||staffName.trim().length<2} onClick={()=>run(()=>upsertHsStaff({name:staffName,staffType,phone:staffPhone}),"Staff record saved.")}>Save staff</button><select className="select" value={selectedStaff} onChange={e=>setSelectedStaff(e.target.value)}><option value="">Select staff</option>{data.staff.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><select className="select" value={staffUnit} onChange={e=>setStaffUnit(e.target.value)}><option value="">Authorize flat</option>{units.map(u=><option key={u.entity.id} value={u.entity.id}>{u.entity.label}</option>)}</select><button className="btn" disabled={busy||!selectedStaff||!staffUnit} onClick={()=>run(()=>authorizeHsStaffUnit(selectedStaff,staffUnit),"Staff-flat permission recorded.")}>Authorize flat</button></div></section>
 <section className="card"><h3>Approval queue</h3><div className="hs2-list">{data.moveRequests.filter(r=>r.status==="requested").map(r=><div key={r.id}><Building2/><span><b>{r.unitLabel} · {r.moveType.replace("_"," ")}</b><small>{r.scheduledOn}</small></span><button className="btn small" onClick={()=>run(()=>reviewHsOperationalRequest("move",r.id,"approved","Approved by committee"),"Move request approved.")}>Approve</button></div>)}{data.renovations.filter(r=>r.status==="requested").map(r=><div key={r.id}><HardHat/><span><b>{r.unitLabel} · {r.title}</b><small>{r.startsOn||"Date TBD"}</small></span><button className="btn small" onClick={()=>run(()=>reviewHsOperationalRequest("renovation",r.id,"approved","Follow society work-hour/safety rules",`NOC-${new Date().getFullYear()}-${String(Date.now()).slice(-4)}`),"Renovation/NOC approved.")}>Approve + NOC</button></div>)}</div></section></div>
 <div className="hs2-admin-grid"><section className="card"><h3>Asset & AMC/service register</h3><div className="stack-form"><input className="text-input" value={assetCode} onChange={e=>setAssetCode(e.target.value)} placeholder="Asset code"/><input className="text-input" value={assetName} onChange={e=>setAssetName(e.target.value)} placeholder="Asset name"/><input className="text-input" value={assetCategory} onChange={e=>setAssetCategory(e.target.value)} placeholder="Lift / Pump / DG / Fire"/><input className="text-input" value={assetLocation} onChange={e=>setAssetLocation(e.target.value)} placeholder="Location"/><button className="btn" disabled={busy||!assetCode||!assetName} onClick={()=>run(()=>upsertHsAsset({assetCode,name:assetName,category:assetCategory,location:assetLocation}),"Asset saved.")}><Plus size={14}/> Save asset</button><select className="select" value={selectedAsset} onChange={e=>setSelectedAsset(e.target.value)}><option value="">Select asset for service</option>{data.assets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><input className="text-input" type="date" value={nextService} onChange={e=>setNextService(e.target.value)}/><button className="btn" disabled={busy||!selectedAsset} onClick={()=>run(()=>addHsAssetService({assetId:selectedAsset,serviceType:"Preventive service",servicedOn:today(),nextDueOn:nextService||null}),"Asset service history recorded.")}><Wrench size={14}/> Record service</button></div><div className="hs2-list">{data.assets.map(a=><div key={a.id}><Wrench/><span><b>{a.assetCode} · {a.name}</b><small>{a.category} · {a.location||"—"}{a.nextServiceOn?` · next ${a.nextServiceOn}`:""}</small></span></div>)}</div></section>
 <section className="card"><h3>Compliance calendar</h3><div className="stack-form"><input className="text-input" value={compCategory} onChange={e=>setCompCategory(e.target.value)}/><input className="text-input" value={compTitle} onChange={e=>setCompTitle(e.target.value)}/><input className="text-input" type="date" value={compDue} onChange={e=>setCompDue(e.target.value)}/><button className="btn" disabled={busy||!compCategory||!compTitle} onClick={()=>run(()=>upsertHsCompliance({category:compCategory,title:compTitle,dueOn:compDue||null}),"Compliance item saved.")}><CalendarClock size={14}/> Save compliance</button></div>{expiring.length>0&&<p className="warning"><AlertTriangle size={14}/> {expiring.length} item(s) due within 30 days.</p>}<div className="hs2-list">{data.compliance.map(c=><div key={c.id}><CalendarClock/><span><b>{c.title}</b><small>{c.category} · {c.dueOn||"No due date"} · {c.status}</small></span></div>)}</div></section></div>
 <section className="card"><h3>Emergency contact publishing</h3><div className="inline-form"><input className="text-input" value={ecCategory} onChange={e=>setEcCategory(e.target.value)} placeholder="Category"/><input className="text-input" value={ecLabel} onChange={e=>setEcLabel(e.target.value)} placeholder="Label"/><input className="text-input" value={ecPhone} onChange={e=>setEcPhone(e.target.value)} placeholder="Phone"/><button className="btn" disabled={busy||!ecLabel||!ecPhone} onClick={()=>run(()=>upsertHsEmergencyContact({category:ecCategory,label:ecLabel,phone:ecPhone}),"Emergency contact published.")}>Publish</button></div></section></>}
 </div>
}
