"use client";
import {useEffect,useMemo,useState} from "react";
import {BadgeIndianRupee,CalendarDays,CheckCircle2,Landmark,Plus,ReceiptIndianRupee,WalletCards} from "lucide-react";
import {addHsBillAdjustment,createHsBillingCycle,fetchHsFinanceSnapshot,generateHsCycleBills,recordHsExpense,recordHsPayment,upsertHsBudgetLine,upsertHsChargeHead,upsertHsFund,type HsFinanceSnapshot} from "../verticals/housing-society/runtime/finance-remote";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";

const EMPTY:HsFinanceSnapshot={chargeHeads:[],cycles:[],bills:[],funds:[],budget:[],summary:{totalBilled:0,totalCollected:0,totalOutstanding:0,overdueBills:0}};
const money=(n?:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`};
const monthEnd=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10)};
export default function HousingSocietyFinancePanel({isAdmin,demo=false,onNotify}:{isAdmin:boolean;demo?:boolean;onNotify:(s:string)=>void}){
 const [data,setData]=useState<HsFinanceSnapshot>(EMPTY),[busy,setBusy]=useState(false);
 const [code,setCode]=useState("MAINT"),[headLabel,setHeadLabel]=useState("Monthly Maintenance"),[category,setCategory]=useState("maintenance"),[amount,setAmount]=useState("2500");
 const [cycleLabel,setCycleLabel]=useState("Monthly Maintenance"),[periodStart,setPeriodStart]=useState(monthStart()),[periodEnd,setPeriodEnd]=useState(monthEnd()),[dueOn,setDueOn]=useState(monthEnd()),[graceDays,setGraceDays]=useState("5"),[penaltyRate,setPenaltyRate]=useState("0");
 const [selectedBill,setSelectedBill]=useState(""),[paymentAmount,setPaymentAmount]=useState(""),[paymentRef,setPaymentRef]=useState(""),[receiptNo,setReceiptNo]=useState("");
 const [adjustType,setAdjustType]=useState<"credit"|"debit"|"waiver"|"penalty">("credit"),[adjustAmount,setAdjustAmount]=useState(""),[adjustReason,setAdjustReason]=useState("");
 const [fundCode,setFundCode]=useState("SINKING"),[fundLabel,setFundLabel]=useState("Sinking Fund"),[fundOpening,setFundOpening]=useState("0");
 const [fy,setFy]=useState(`${new Date().getFullYear()}-${String((new Date().getFullYear()+1)%100).padStart(2,"0")}`),[budgetCategory,setBudgetCategory]=useState("Repairs"),[budgetLabel,setBudgetLabel]=useState("Annual repairs"),[budgetAmount,setBudgetAmount]=useState("");
 const [expenseDesc,setExpenseDesc]=useState(""),[expenseAmount,setExpenseAmount]=useState("");
 const load=async()=>{if(demo){setData({...EMPTY,cycles:[{id:"demo-cycle",label:"September 2026",periodStart:"2026-09-01",periodEnd:"2026-09-30",dueOn:"2026-09-10",status:"issued",graceDays:5,penaltyRateMonthly:0}],bills:[{id:"demo-bill",cycleId:"demo-cycle",cycleLabel:"September 2026",unitEntityId:"u1",unitLabel:"A-101",dueOn:"2026-09-10",subtotal:3000,adjustmentAmount:0,totalAmount:3000,paidAmount:3000,balanceAmount:0,status:"paid",lineItems:[{id:"l1",label:"Monthly Maintenance",amount:2500},{id:"l2",label:"Sinking Fund",amount:500}],payments:[{id:"p1",amount:3000,paidOn:"2026-09-05",paymentMode:"upi",paymentReference:"UTR-DEMO",receiptNumber:"R-0901",status:"recorded"}]}],funds:[{id:"f1",code:"SINKING",label:"Sinking Fund",openingBalance:250000,currentBalance:248000,visibility:"members"}],summary:{totalBilled:150000,totalCollected:138000,totalOutstanding:12000,overdueBills:3}});return}try{setData(await fetchHsFinanceSnapshot())}catch(e:any){onNotify(e.message||"Could not load society finance.")}};
 useEffect(()=>{load()},[]);
 const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);try{await fn();onNotify(ok);await load()}catch(e:any){onNotify(e.message||"Could not save finance change.")}finally{setBusy(false)}};
 const overdue=useMemo(()=>data.bills.filter(b=>b.balanceAmount>0&&new Date(b.dueOn)<new Date()),[data.bills]);
 const selected=data.bills.find(b=>b.id===selectedBill);
 return <div className="hs3-finance"><NetworkSectionHead kicker={<><BadgeIndianRupee size={12}/> HS-3 maintenance & finance</>} title="Maintenance, dues & society finance" description="Represent one complete billing cycle without replacing accounting software. Residents see only their current flat ledger; committee operators control official billing and receipts."/>
 <section className="network-metric-grid"><NetworkMetric value={money(data.summary.totalBilled)} label="Billed"/><NetworkMetric value={money(data.summary.totalCollected)} label="Collected"/><NetworkMetric value={money(data.summary.totalOutstanding)} label="Outstanding"/><NetworkMetric value={data.summary.overdueBills} label="Overdue bills"/></section>
 {!isAdmin&&<><section className="card"><NetworkSectionHead kicker={<><ReceiptIndianRupee size={12}/> My flat ledger</>} title="Maintenance bills & receipts" description="Payment gateway is not enabled yet; committee-recorded payment references and receipts appear here."/>{data.bills.length?<div className="table-wrap"><table><thead><tr><th>Cycle</th><th>Flat</th><th>Due</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{data.bills.map(b=><tr key={b.id}><td>{b.cycleLabel}</td><td>{b.unitLabel}</td><td>{b.dueOn}</td><td>{money(b.totalAmount)}</td><td>{money(b.paidAmount)}</td><td>{money(b.balanceAmount)}</td><td>{b.status}</td></tr>)}</tbody></table></div>:<NetworkEmpty icon={<ReceiptIndianRupee/>} title="No maintenance bill yet" description="Your issued flat bills will appear here."/>}</section><section className="card"><h3>Receipts & payment references</h3>{data.bills.flatMap(b=>b.payments.map(p=>({...p,unitLabel:b.unitLabel,cycleLabel:b.cycleLabel}))).length?<div className="hs2-list">{data.bills.flatMap(b=>b.payments.map(p=><div key={p.id}><CheckCircle2/><span><b>{money(p.amount)} · {b.unitLabel}</b><small>{p.paidOn} · {p.receiptNumber||p.paymentReference||p.paymentMode}</small></span></div>))}</div>:<p className="muted">No recorded receipts.</p>}</section></>}
 {isAdmin&&<><div className="hs2-admin-grid"><section className="card"><h3>Charge catalog</h3><div className="stack-form"><input className="text-input" placeholder="Code" value={code} onChange={e=>setCode(e.target.value)}/><input className="text-input" placeholder="Charge head" value={headLabel} onChange={e=>setHeadLabel(e.target.value)}/><select className="select" value={category} onChange={e=>setCategory(e.target.value)}><option value="maintenance">Maintenance</option><option value="sinking_fund">Sinking fund</option><option value="repair_fund">Repair fund</option><option value="parking">Parking</option><option value="water">Water</option><option value="common_electricity">Common electricity</option><option value="non_occupancy">Non-occupancy</option><option value="special_assessment">Special assessment</option><option value="other">Other</option></select><input className="text-input" type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="btn primary" disabled={busy||!code||!headLabel||Number(amount)<0} onClick={()=>run(()=>upsertHsChargeHead({code,label:headLabel,category,amount:Number(amount)}),"Charge head saved.")}><Plus size={14}/> Save charge</button></div><div className="hs2-list">{data.chargeHeads.map(h=><div key={h.id}><WalletCards/><span><b>{h.label}</b><small>{h.code} · {money(h.amount)} · {h.category}</small></span></div>)}</div></section>
 <section className="card"><h3>Billing cycle</h3><div className="stack-form"><input className="text-input" value={cycleLabel} onChange={e=>setCycleLabel(e.target.value)} placeholder="September 2026"/><label className="field"><span>Period start</span><input className="text-input" type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)}/></label><label className="field"><span>Period end</span><input className="text-input" type="date" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)}/></label><label className="field"><span>Due date</span><input className="text-input" type="date" value={dueOn} onChange={e=>setDueOn(e.target.value)}/></label><input className="text-input" type="number" min="0" placeholder="Grace days" value={graceDays} onChange={e=>setGraceDays(e.target.value)}/><input className="text-input" type="number" min="0" step="0.01" placeholder="Monthly penalty %" value={penaltyRate} onChange={e=>setPenaltyRate(e.target.value)}/><button className="btn" disabled={busy||!cycleLabel||!periodStart||!periodEnd||!dueOn} onClick={()=>run(()=>createHsBillingCycle({label:cycleLabel,periodStart,periodEnd,dueOn,graceDays:Number(graceDays||0),penaltyRateMonthly:Number(penaltyRate||0)}),"Billing cycle saved.")}><CalendarDays size={14}/> Create cycle</button></div><div className="hs2-list">{data.cycles.map(c=><div key={c.id}><CalendarDays/><span><b>{c.label}</b><small>{c.periodStart} → {c.periodEnd} · due {c.dueOn} · {c.status}</small></span>{c.status==="draft"&&<button className="btn small" disabled={busy} onClick={()=>run(async()=>{const r=await generateHsCycleBills(c.id);onNotify(`Issued ${r.unitCount} flat bills with ${r.chargeHeadCount} charge heads.`)},"Bills generated.")}>Generate bills</button>}</div>)}</div></section></div>
 <section className="card"><NetworkSectionHead title="Flat ledger" description="Official bills are generated from active charge heads. Paid, partial, unpaid and waived states are recalculated from immutable line items, adjustments and payment records."/><div className="table-wrap"><table><thead><tr><th>Cycle</th><th>Flat</th><th>Total</th><th>Paid</th><th>Balance</th><th>Due</th><th>Status</th></tr></thead><tbody>{data.bills.map(b=><tr key={b.id} onClick={()=>setSelectedBill(b.id)} style={{cursor:"pointer"}}><td>{b.cycleLabel}</td><td>{b.unitLabel}</td><td>{money(b.totalAmount)}</td><td>{money(b.paidAmount)}</td><td>{money(b.balanceAmount)}</td><td>{b.dueOn}</td><td>{b.status}</td></tr>)}</tbody></table></div>{!data.bills.length&&<p className="muted">Create a cycle and generate flat bills.</p>}</section>
 {selected&&<div className="hs2-admin-grid"><section className="card"><h3>Record payment · {selected.unitLabel}</h3><p>{selected.cycleLabel} · balance {money(selected.balanceAmount)}</p><div className="stack-form"><input className="text-input" type="number" min="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} placeholder="Amount received"/><input className="text-input" value={paymentRef} onChange={e=>setPaymentRef(e.target.value)} placeholder="UPI / cheque / bank reference"/><input className="text-input" value={receiptNo} onChange={e=>setReceiptNo(e.target.value)} placeholder="Receipt number"/><button className="btn primary" disabled={busy||Number(paymentAmount)<=0} onClick={()=>run(()=>recordHsPayment({billId:selected.id,amount:Number(paymentAmount),paidOn:today(),paymentMode:"manual",paymentReference:paymentRef,receiptNumber:receiptNo}),"Payment and receipt recorded.")}><ReceiptIndianRupee size={14}/> Record payment</button></div></section><section className="card"><h3>Adjustment / waiver</h3><div className="stack-form"><select className="select" value={adjustType} onChange={e=>setAdjustType(e.target.value as any)}><option value="credit">Credit</option><option value="debit">Debit</option><option value="waiver">Waiver</option><option value="penalty">Penalty</option></select><input className="text-input" type="number" min="0" value={adjustAmount} onChange={e=>setAdjustAmount(e.target.value)} placeholder="Amount"/><input className="text-input" value={adjustReason} onChange={e=>setAdjustReason(e.target.value)} placeholder="Reason / approval note"/><button className="btn" disabled={busy||Number(adjustAmount)<0||adjustReason.trim().length<2} onClick={()=>run(()=>addHsBillAdjustment({billId:selected.id,type:adjustType,amount:Number(adjustAmount),reason:adjustReason}),"Bill adjustment recorded with history.")}>Apply adjustment</button></div></section></div>}
 <div className="hs2-admin-grid"><section className="card"><h3>Society funds</h3><div className="stack-form"><input className="text-input" value={fundCode} onChange={e=>setFundCode(e.target.value)} placeholder="Fund code"/><input className="text-input" value={fundLabel} onChange={e=>setFundLabel(e.target.value)} placeholder="Fund name"/><input className="text-input" type="number" value={fundOpening} onChange={e=>setFundOpening(e.target.value)} placeholder="Opening balance"/><button className="btn" disabled={busy||!fundCode||!fundLabel} onClick={()=>run(()=>upsertHsFund({code:fundCode,label:fundLabel,openingBalance:Number(fundOpening||0)}),"Fund saved.")}><Landmark size={14}/> Save fund</button></div>{data.funds.map(f=><p key={f.id}><b>{f.label}</b> · {money(f.currentBalance)}</p>)}</section>
 <section className="card"><h3>Budget vs actual</h3><div className="stack-form"><input className="text-input" value={fy} onChange={e=>setFy(e.target.value)} placeholder="2026-27"/><input className="text-input" value={budgetCategory} onChange={e=>setBudgetCategory(e.target.value)} placeholder="Category"/><input className="text-input" value={budgetLabel} onChange={e=>setBudgetLabel(e.target.value)} placeholder="Budget line"/><input className="text-input" type="number" value={budgetAmount} onChange={e=>setBudgetAmount(e.target.value)} placeholder="Budget amount"/><button className="btn" disabled={busy||!fy||!budgetCategory||!budgetLabel||Number(budgetAmount)<0} onClick={()=>run(()=>upsertHsBudgetLine({financialYear:fy,category:budgetCategory,label:budgetLabel,budgetAmount:Number(budgetAmount||0)}),"Budget line saved.")}>Save budget</button><input className="text-input" value={expenseDesc} onChange={e=>setExpenseDesc(e.target.value)} placeholder="Expense description"/><input className="text-input" type="number" value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)} placeholder="Actual expense"/><button className="btn" disabled={busy||expenseDesc.trim().length<2||Number(expenseAmount)<=0} onClick={()=>run(()=>recordHsExpense({category:budgetCategory,description:expenseDesc,amount:Number(expenseAmount),incurredOn:today()}),"Expense recorded.")}>Record actual</button></div>{data.budget.map(b=><div key={b.id} className="hs2-row"><span><b>{b.label}</b><small>{b.financialYear} · {b.category}</small></span><span>{money(b.actualAmount)} / {money(b.budgetAmount)}</span></div>)}</section></div>
 <section className="card"><h3>Arrears / aging watch</h3>{overdue.length?<div className="hs2-list">{overdue.map(b=><div key={b.id}><ReceiptIndianRupee/><span><b>{b.unitLabel} · {money(b.balanceAmount)}</b><small>{b.cycleLabel} · due {b.dueOn}</small></span></div>)}</div>:<p className="muted">No overdue flat bills.</p>}</section></>}
 </div>
}
