"use client";
import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,ClipboardList,FileText,Gavel,Plus,UsersRound,Vote} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../core/network-os/contracts";
import {addHsAgendaItem,assignHsCommitteeRole,castHsResolutionVote,closeHsResolution,createHsCommitteeTerm,createHsGovernanceAction,createHsGovernanceMeeting,createHsResolution,fetchHsGovernanceSnapshot,publishHsMinutes,updateHsGovernanceAction,type HsGovernanceSnapshot} from "../verticals/housing-society/runtime/governance-remote";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";
const EMPTY:HsGovernanceSnapshot={terms:[],meetings:[],actions:[],resolutions:[],documents:[]};
const today=()=>new Date().toISOString().slice(0,10),nextWeek=()=>new Date(Date.now()+7*86400000).toISOString().slice(0,16);
export default function HousingSocietyGovernancePanel({isAdmin,demo=false,entities,onNotify}:{isAdmin:boolean;demo?:boolean;entities:NetworkAffiliatedEntity[];onNotify:(s:string)=>void}){
 const people=useMemo(()=>entities.filter(e=>e.entity.kind==="person"),[entities]);const [data,setData]=useState(EMPTY),[busy,setBusy]=useState(false);
 const [termLabel,setTermLabel]=useState("Committee 2026-27"),[termStart,setTermStart]=useState(today()),[termEnd,setTermEnd]=useState("");
 const [termId,setTermId]=useState(""),[personId,setPersonId]=useState(""),[role,setRole]=useState("committee_member");
 const [meetingType,setMeetingType]=useState("committee"),[meetingTitle,setMeetingTitle]=useState("Monthly Committee Meeting"),[meetingAt,setMeetingAt]=useState(nextWeek()),[location,setLocation]=useState("Society Office");
 const [meetingId,setMeetingId]=useState(""),[agendaTitle,setAgendaTitle]=useState(""),[minutes,setMinutes]=useState(""),[attendees,setAttendees]=useState("");
 const [actionTitle,setActionTitle]=useState(""),[actionOwner,setActionOwner]=useState(""),[actionDue,setActionDue]=useState("");
 const [resolutionNo,setResolutionNo]=useState("RES-001"),[resolutionTitle,setResolutionTitle]=useState(""),[resolutionBody,setResolutionBody]=useState(""),[voteMode,setVoteMode]=useState<"approval"|"advisory">("approval");
 const load=async()=>{if(demo){setData({terms:[{id:"t1",label:"Committee 2026-27",startsOn:"2026-04-01",status:"active",assignments:[{id:"a1",personEntityId:"p1",personLabel:"Aarav Mehta",roleKey:"chairperson",startsOn:"2026-04-01"},{id:"a2",personEntityId:"p2",personLabel:"Neha Shah",roleKey:"secretary",startsOn:"2026-04-01"}]}],meetings:[{id:"m1",meetingType:"committee",title:"September Committee Meeting",scheduledAt:"2026-09-12T19:30:00+05:30",location:"Clubhouse",status:"scheduled",agenda:[{id:"ag1",itemOrder:1,title:"Lift AMC renewal"},{id:"ag2",itemOrder:2,title:"Navratri event budget"}]}],actions:[{id:"ac1",meetingId:"m0",title:"Collect lift AMC quotations",ownerLabel:"Secretary",dueOn:"2026-09-10",status:"in_progress"}],resolutions:[{id:"r1",resolutionNumber:"RES-014",title:"Approve lift AMC vendor renewal",body:"Approve annual lift AMC renewal within the sanctioned budget.",voteMode:"approval",status:"open",quorumPercent:0,yesCount:18,noCount:2,abstainCount:1,myVote:null}],documents:[]});return}try{setData(await fetchHsGovernanceSnapshot())}catch(e:any){onNotify(e.message||"Could not load society governance.")}};
 useEffect(()=>{load()},[]);const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);try{await fn();onNotify(ok);await load()}catch(e:any){onNotify(e.message||"Could not save governance change.")}finally{setBusy(false)}};
 const openActions=data.actions.filter(a=>a.status!=="done"&&a.status!=="cancelled");
 return <div className="hs4-governance"><NetworkSectionHead kicker={<><Gavel size={12}/> HS-4 governance</>} title="Committee, meetings & decisions" description="Preserve office-bearer history, meeting records, action items and controlled member decisions. This is not an election-grade secret ballot engine."/>
 <section className="network-metric-grid"><NetworkMetric value={data.terms[0]?.assignments.length||0} label="Current committee"/><NetworkMetric value={data.meetings.length} label="Meetings"/><NetworkMetric value={openActions.length} label="Open actions"/><NetworkMetric value={data.resolutions.filter(r=>r.status==="open").length} label="Open decisions"/></section>
 {!isAdmin&&<><section className="card"><NetworkSectionHead kicker={<><UsersRound size={12}/> Committee</>} title="Current office bearers" description="Roles are time-bounded so prior committee history remains visible."/>{data.terms.length?<div className="hs2-list">{data.terms[0].assignments.map(a=><div key={a.id}><UsersRound/><span><b>{a.personLabel}</b><small>{a.roleLabel||a.roleKey.replaceAll("_"," ")} · since {a.startsOn}</small></span></div>)}</div>:<NetworkEmpty icon={<UsersRound/>} title="No committee term published" description="Committee history will appear here."/>}</section>
 <section className="card"><h3>Meetings & minutes</h3><div className="hs2-list">{data.meetings.map(m=><div key={m.id}><ClipboardList/><span><b>{m.title}</b><small>{new Date(m.scheduledAt).toLocaleString()} · {m.location||"Location TBD"} · {m.status}</small>{m.minutesText&&<p>{m.minutesText}</p>}</span></div>)}</div></section>
 <section className="card"><h3>Resolutions & controlled votes</h3>{data.resolutions.length?<div className="hs2-list">{data.resolutions.map(r=><div key={r.id}><Vote/><span><b>{r.resolutionNumber?`${r.resolutionNumber} · `:""}{r.title}</b><small>{r.voteMode} · {r.status} · Yes {r.yesCount} / No {r.noCount} / Abstain {r.abstainCount}</small><p>{r.body}</p>{r.status==="open"&&<div className="card-actions"><button className="btn small" disabled={busy||demo} onClick={()=>run(()=>castHsResolutionVote(r.id,"yes"),"Vote recorded.")}>Yes</button><button className="btn small" disabled={busy||demo} onClick={()=>run(()=>castHsResolutionVote(r.id,"no"),"Vote recorded.")}>No</button><button className="btn small" disabled={busy||demo} onClick={()=>run(()=>castHsResolutionVote(r.id,"abstain"),"Vote recorded.")}>Abstain</button>{r.myVote&&<small>Your vote: {r.myVote}</small>}</div>}</span></div>)}</div>:<p className="muted">No published resolutions.</p>}</section></>}
 {isAdmin&&<><div className="hs2-admin-grid"><section className="card"><h3>Committee term & role history</h3><div className="stack-form"><input className="text-input" value={termLabel} onChange={e=>setTermLabel(e.target.value)}/><input className="text-input" type="date" value={termStart} onChange={e=>setTermStart(e.target.value)}/><input className="text-input" type="date" value={termEnd} onChange={e=>setTermEnd(e.target.value)}/><button className="btn primary" disabled={busy||!termLabel||!termStart} onClick={()=>run(()=>createHsCommitteeTerm({label:termLabel,startsOn:termStart,endsOn:termEnd||null}),"Committee term saved.")}><Plus size={14}/> Save term</button><select className="select" value={termId} onChange={e=>setTermId(e.target.value)}><option value="">Select term</option>{data.terms.map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</select><select className="select" value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Select resident</option>{people.map(p=><option value={p.entity.id} key={p.entity.id}>{p.entity.label}</option>)}</select><select className="select" value={role} onChange={e=>setRole(e.target.value)}><option value="chairperson">Chairperson</option><option value="secretary">Secretary</option><option value="treasurer">Treasurer</option><option value="committee_member">Committee member</option><option value="manager">Manager</option><option value="auditor">Auditor</option><option value="other">Other</option></select><button className="btn" disabled={busy||!termId||!personId} onClick={()=>run(()=>assignHsCommitteeRole({termId,personEntityId:personId,roleKey:role,startsOn:termStart}),"Committee role assigned with history.")}>Assign role</button></div></section>
 <section className="card"><h3>Schedule meeting</h3><div className="stack-form"><select className="select" value={meetingType} onChange={e=>setMeetingType(e.target.value)}><option value="committee">Committee</option><option value="agm">AGM</option><option value="sgm">SGM</option><option value="general">General body</option><option value="other">Other</option></select><input className="text-input" value={meetingTitle} onChange={e=>setMeetingTitle(e.target.value)}/><input className="text-input" type="datetime-local" value={meetingAt} onChange={e=>setMeetingAt(e.target.value)}/><input className="text-input" value={location} onChange={e=>setLocation(e.target.value)}/><button className="btn primary" disabled={busy||!meetingTitle||!meetingAt} onClick={()=>run(()=>createHsGovernanceMeeting({meetingType,title:meetingTitle,scheduledAt:meetingAt,location}),"Meeting scheduled.")}><Plus size={14}/> Schedule</button></div></section></div>
 <div className="hs2-admin-grid"><section className="card"><h3>Agenda, minutes & action items</h3><div className="stack-form"><select className="select" value={meetingId} onChange={e=>setMeetingId(e.target.value)}><option value="">Select meeting</option>{data.meetings.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select><input className="text-input" value={agendaTitle} onChange={e=>setAgendaTitle(e.target.value)} placeholder="Agenda item"/><button className="btn" disabled={busy||!meetingId||!agendaTitle} onClick={()=>run(()=>addHsAgendaItem(meetingId,agendaTitle),"Agenda item added.")}>Add agenda</button><textarea className="text-input" rows={4} value={minutes} onChange={e=>setMinutes(e.target.value)} placeholder="Published minutes"/><input className="text-input" type="number" min="0" value={attendees} onChange={e=>setAttendees(e.target.value)} placeholder="Attendee count"/><button className="btn" disabled={busy||!meetingId||minutes.trim().length<3} onClick={()=>run(()=>publishHsMinutes(meetingId,minutes,attendees?Number(attendees):null),"Meeting minutes published.")}><FileText size={14}/> Publish minutes</button><input className="text-input" value={actionTitle} onChange={e=>setActionTitle(e.target.value)} placeholder="Action item"/><input className="text-input" value={actionOwner} onChange={e=>setActionOwner(e.target.value)} placeholder="Owner / committee role"/><input className="text-input" type="date" value={actionDue} onChange={e=>setActionDue(e.target.value)}/><button className="btn" disabled={busy||!actionTitle} onClick={()=>run(()=>createHsGovernanceAction({meetingId:meetingId||null,title:actionTitle,ownerLabel:actionOwner,dueOn:actionDue||null}),"Action item created.")}>Create action</button></div></section>
 <section className="card"><h3>Resolution / poll</h3><div className="stack-form"><input className="text-input" value={resolutionNo} onChange={e=>setResolutionNo(e.target.value)} placeholder="Resolution no."/><input className="text-input" value={resolutionTitle} onChange={e=>setResolutionTitle(e.target.value)} placeholder="Decision title"/><textarea className="text-input" rows={4} value={resolutionBody} onChange={e=>setResolutionBody(e.target.value)} placeholder="Resolution text"/><select className="select" value={voteMode} onChange={e=>setVoteMode(e.target.value as any)}><option value="approval">Approval vote</option><option value="advisory">Advisory poll</option></select><button className="btn primary" disabled={busy||resolutionTitle.trim().length<3||resolutionBody.trim().length<3} onClick={()=>run(()=>createHsResolution({meetingId:meetingId||null,resolutionNumber:resolutionNo,title:resolutionTitle,body:resolutionBody,voteMode}),"Resolution opened for controlled member voting.")}><Vote size={14}/> Open decision</button></div></section></div>
 <section className="card"><h3>Governance action register</h3><div className="hs2-list">{data.actions.map(a=><div key={a.id}><CheckCircle2/><span><b>{a.title}</b><small>{a.ownerLabel||"Unassigned"}{a.dueOn?` · due ${a.dueOn}`:""} · {a.status}</small></span>{a.status!=="done"&&<button className="btn small" disabled={busy} onClick={()=>run(()=>updateHsGovernanceAction(a.id,"done","Completed by committee"),"Action item closed.")}>Mark done</button>}</div>)}</div></section>
 <section className="card"><h3>Decision register</h3><div className="hs2-list">{data.resolutions.map(r=><div key={r.id}><Gavel/><span><b>{r.resolutionNumber||"Decision"} · {r.title}</b><small>{r.status} · Yes {r.yesCount} / No {r.noCount} / Abstain {r.abstainCount}</small></span>{r.status==="open"&&<div className="card-actions"><button className="btn small" onClick={()=>run(()=>closeHsResolution(r.id,"approved","Closed by committee after reviewing recorded votes/quorum."),"Resolution approved and closed.")}>Approve & close</button><button className="btn small" onClick={()=>run(()=>closeHsResolution(r.id,"rejected","Closed by committee after reviewing recorded votes/quorum."),"Resolution rejected and closed.")}>Reject & close</button></div>}</div>)}</div></section></>}
 </div>
}
