"use client";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,CheckCircle2,ClipboardCheck,Download,FlaskConical,RefreshCw,Rocket,Save,UsersRound,XCircle} from "lucide-react";
import {fetchHsPilotSnapshot,recordHsPilotCheckpoint,recordHsPilotUsageEvent,recordHsPricingExperiment,startHsPilot,updateHsPilotStatus,type HsPilotSnapshot} from "../verticals/housing-society/runtime/pilot-remote";
import {NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";

const EMPTY:HsPilotSnapshot={run:null,readiness:0,signals:[],metrics:{totalUnits:0,occupiedUnits:0,claimedUnits:0,claimRate:0,weeklyActiveUnits:0,activeMembers:0,notices30d:0,noticeReaders30d:0,noticeReadReach:0,complaints30d:0,resolvedComplaints30d:0,medianResolutionHours:0,maintenanceViews30d:0,billingCycles:0,paymentsRecorded:0,completedMeetings:0,securityComplianceCycles:0,committedImports:0},checkpoints:[],pricingExperiments:[]};
const phaseCopy={A:"Internal demo",B:"20–50 real units",C:"Full society",D:"Second society"} as const;
export default function HousingSocietyPilotPanel({demo=false,onNotify}:{demo?:boolean;onNotify:(s:string)=>void}){
 const [data,setData]=useState<HsPilotSnapshot>(EMPTY),[busy,setBusy]=useState(false);
 const [phase,setPhase]=useState<"A"|"B"|"C"|"D">("B"),[target,setTarget]=useState("30"),[cohort,setCohort]=useState("Pilot wing / tower"),[pilotNotes,setPilotNotes]=useState("");
 const [hours,setHours]=useState(""),[offline,setOffline]=useState(""),[wtp,setWtp]=useState("unknown"),[renewal,setRenewal]=useState("unknown"),[repeatable,setRepeatable]=useState(false),[founderCode,setFounderCode]=useState(false),[checkpointNote,setCheckpointNote]=useState("");
 const [pricingModel,setPricingModel]=useState("undecided"),[amount,setAmount]=useState(""),[priceResponse,setPriceResponse]=useState("untested"),[priceNote,setPriceNote]=useState("");
 const load=async()=>{if(demo){setData({...EMPTY,run:{id:"demo",phase:"B",status:"active",cohortLabel:"Tower A · 30 units",targetUnits:30},readiness:70,signals:[{key:"mapped_import",label:"Mapped import completed",passed:true},{key:"target_units",label:"Pilot unit target represented",passed:true},{key:"claimed_units",label:"Residents claimed real unit profiles",passed:true},{key:"weekly_usage",label:"Weekly active occupied units observed",passed:true},{key:"notice_reach",label:"Resident notice readership observed",passed:true},{key:"complaint_loop",label:"Complaint resolved end-to-end",passed:true},{key:"maintenance_cycle",label:"Maintenance bill cycle represented",passed:true},{key:"governance_cycle",label:"Committee/AGM meeting completed",passed:false},{key:"operations_cycle",label:"Security/compliance/asset operation completed",passed:false},{key:"repeatable_onboarding",label:"Second-society onboarding confirmed without founder-specific code",passed:false}],metrics:{...EMPTY.metrics,totalUnits:30,occupiedUnits:27,claimedUnits:18,claimRate:60,weeklyActiveUnits:14,activeMembers:34,notices30d:5,noticeReaders30d:22,noticeReadReach:65,complaints30d:11,resolvedComplaints30d:8,medianResolutionHours:19,maintenanceViews30d:24,billingCycles:1,paymentsRecorded:16,committedImports:1}});return;}try{setData(await fetchHsPilotSnapshot())}catch(e:any){onNotify(e.message||"Could not load HS-6 pilot evidence.")}};
 useEffect(()=>{void load()},[]);
 const run=async(fn:()=>Promise<unknown>,msg:string)=>{if(demo){onNotify("Playground is read-only.");return;}setBusy(true);try{await fn();onNotify(msg);await load()}catch(e:any){onNotify(e.message||"Pilot operation failed.")}finally{setBusy(false)}};
 const m=data.metrics,latest=data.latestCheckpoint;
 const proofLabel=useMemo(()=>data.readiness>=90?"Commercial proof candidate":data.readiness>=70?"Pilot progressing":data.readiness>=40?"Evidence building":"Foundation still incomplete",[data.readiness]);
 const exportEvidence=()=>{const payload={exportedAt:new Date().toISOString(),mission:"HS-6 Founder Society Pilot & Commercialization",...data};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`housing-society-pilot-evidence-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);if(!demo)void recordHsPilotUsageEvent("pilot_export").catch(()=>{});};
 return <div className="hs6-pilot"><NetworkSectionHead kicker={<><Rocket size={12}/> HS-6 founder pilot</>} title="Pilot readiness & commercialization evidence" description="Run one society as a measured product pilot, then prove the same onboarding works for a second society without founder-specific code."/>
  <section className="card"><div className="hs2-row"><div><span className="warm-kicker">{data.run?`Pilot ${data.run.phase} · ${phaseCopy[data.run.phase]}`:"No pilot run started"}</span><h3>{proofLabel}</h3><p>{data.run?.cohortLabel||"Start with a synthetic demo or a 20–50 unit real cohort."}</p></div><div><b>{data.readiness}%</b><small> evidence readiness</small></div></div><div className="network-metric-grid"><NetworkMetric value={m.totalUnits} label="Units represented"/><NetworkMetric value={`${m.claimRate}%`} label="Unit claim rate"/><NetworkMetric value={m.weeklyActiveUnits} label="Weekly active units"/><NetworkMetric value={`${m.noticeReadReach}%`} label="Notice reach"/><NetworkMetric value={m.resolvedComplaints30d} label="Resolved complaints · 30d"/><NetworkMetric value={`${m.medianResolutionHours}h`} label="Median resolution"/></div><div className="hs2-list">{data.signals.map(s=><div key={s.key}>{s.passed?<CheckCircle2/>:<XCircle/>}<span><b>{s.label}</b><small>{s.passed?"Evidence observed":"Still needs pilot evidence"}</small></span></div>)}</div><div className="card-actions"><button className="btn" disabled={busy} onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button><button className="btn" onClick={exportEvidence}><Download size={14}/> Export evidence JSON</button><a className="btn" href="/housing-society-pilot-import-template.csv" download>Download import template</a></div></section>
  {!data.run?<section className="card"><h3>Start a pilot run</h3><div className="stack-form"><div className="inline-form"><select className="select" value={phase} onChange={e=>setPhase(e.target.value as any)}>{Object.entries(phaseCopy).map(([k,v])=><option key={k} value={k}>Pilot {k} · {v}</option>)}</select><input className="text-input" type="number" min="1" max="5000" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Target units"/></div><input className="text-input" value={cohort} onChange={e=>setCohort(e.target.value)} placeholder="Cohort label, e.g. Tower A"/><textarea className="text-input" rows={3} value={pilotNotes} onChange={e=>setPilotNotes(e.target.value)} placeholder="Pilot assumptions / scope"/><button className="btn primary" disabled={busy||Number(target)<1} onClick={()=>run(()=>startHsPilot({phase,targetUnits:Number(target),cohortLabel:cohort,notes:pilotNotes}),"Pilot started.")}><Rocket size={14}/> Start pilot</button></div></section>:<section className="card"><h3>Current pilot controls</h3><p>Target: {data.run.targetUnits} units · status: {data.run.status}</p><div className="card-actions">{(["active","paused","completed","stopped"] as const).map(s=><button key={s} className="btn small" disabled={busy||data.run?.status===s} onClick={()=>run(()=>updateHsPilotStatus(data.run!.id,s),`Pilot marked ${s}.`)}>{s}</button>)}</div></section>}
  {data.run&&<div className="hs2-admin-grid"><section className="card"><div className="hs2-row"><div><span className="warm-kicker">Weekly operator checkpoint</span><h3>Measure value, not feature count</h3></div><ClipboardCheck/></div><div className="stack-form"><div className="inline-form"><input className="text-input" type="number" min="0" step="0.5" value={hours} onChange={e=>setHours(e.target.value)} placeholder="Admin hours saved / week"/><input className="text-input" type="number" min="0" value={offline} onChange={e=>setOffline(e.target.value)} placeholder="Ops still only on WhatsApp/Excel"/></div><div className="inline-form"><select className="select" value={wtp} onChange={e=>setWtp(e.target.value)}><option value="unknown">Willingness to pay: unknown</option><option value="no">No</option><option value="maybe">Maybe</option><option value="yes">Yes</option></select><select className="select" value={renewal} onChange={e=>setRenewal(e.target.value)}><option value="unknown">Renewal intent: unknown</option><option value="no">No</option><option value="maybe">Maybe</option><option value="yes">Yes</option></select></div><label><input type="checkbox" checked={repeatable} onChange={e=>setRepeatable(e.target.checked)}/> Second-society onboarding reproduced</label><label><input type="checkbox" checked={founderCode} onChange={e=>setFounderCode(e.target.checked)}/> Founder-specific code/manual patch was required</label><textarea className="text-input" rows={3} value={checkpointNote} onChange={e=>setCheckpointNote(e.target.value)} placeholder="Committee feedback / friction / next action"/><button className="btn primary" disabled={busy} onClick={()=>run(()=>recordHsPilotCheckpoint({runId:data.run!.id,adminHoursSaved:hours?Number(hours):null,offlineOperationsRemaining:offline?Number(offline):null,willingnessToPay:wtp,renewalIntent:renewal,repeatableOnboardingConfirmed:repeatable,founderSpecificCodeRequired:founderCode,committeeNote:checkpointNote}),"Pilot checkpoint recorded.")}><Save size={14}/> Save checkpoint</button></div>{latest&&<p className="muted">Latest: {latest.admin_hours_saved??"—"} admin hours saved · {latest.offline_operations_remaining??"—"} offline operations · pay {latest.willingness_to_pay} · renew {latest.renewal_intent}</p>}</section>
  <section className="card"><div className="hs2-row"><div><span className="warm-kicker">Pricing experiment</span><h3>Test hypotheses; do not freeze pricing</h3></div><FlaskConical/></div><div className="stack-form"><select className="select" value={pricingModel} onChange={e=>setPricingModel(e.target.value)}><option value="undecided">Undecided / discovery</option><option value="per_unit_month">Per unit / month</option><option value="society_annual">Flat annual society fee</option><option value="base_plus_modules">Base + paid modules</option><option value="setup_fee">Setup / migration fee</option></select><div className="inline-form"><input className="text-input" type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Hypothesis amount (INR)"/><select className="select" value={priceResponse} onChange={e=>setPriceResponse(e.target.value)}><option value="untested">Untested</option><option value="rejected">Rejected</option><option value="neutral">Neutral</option><option value="interested">Interested</option><option value="accepted">Accepted</option></select></div><textarea className="text-input" rows={3} value={priceNote} onChange={e=>setPriceNote(e.target.value)} placeholder="What was presented and why the committee reacted this way"/><button className="btn" disabled={busy} onClick={()=>run(()=>recordHsPricingExperiment({runId:data.run!.id,pricingModel,amount:amount?Number(amount):null,response:priceResponse,notes:priceNote}),"Pricing evidence recorded.")}><BarChart3 size={14}/> Record pricing signal</button></div></section></div>}
  <section className="card"><span className="warm-kicker">Second-society proof rule</span><h3>Commercialization starts only when onboarding is repeatable</h3><p>Pilot D is the real commercialization test: import another society using the same mapper, guides, permissions, workflows and migrations. If a founder-only data patch or code branch is needed, record that explicitly instead of calling the vertical commercial-ready.</p><div className="network-metric-grid"><NetworkMetric value={m.committedImports} label="Committed mapped imports"/><NetworkMetric value={m.billingCycles} label="Billing cycles"/><NetworkMetric value={m.completedMeetings} label="Completed meetings"/><NetworkMetric value={m.securityComplianceCycles} label="Security/compliance cycles"/></div></section>
 </div>;
}
