"use client";
import {useEffect,useMemo,useState} from "react";
import {Building2,Car,FileSpreadsheet,Home,KeyRound,ParkingCircle,Plus,UsersRound} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../core/network-os/contracts";
import {allocateHsParking,createHsResidentInvitation,fetchHsMyFlat,fetchHsPropertySnapshot,setHsOccupancy,upsertHsParkingSlot,upsertHsVehicle,type HsMyFlat,type HsPropertySnapshot} from "../verticals/housing-society/runtime/remote";
import {InitialsAvatar,NetworkEmpty,NetworkSectionHead} from "./shared/NetworkUi";
import GuidedWorkbookImport from "./shared/GuidedWorkbookImport";
import {commitHousingWorkbook} from "../capabilities/import/housing-workbook";

type Mode="my-flat"|"admin";
const today=()=>new Date().toISOString().slice(0,10);
export default function HousingSocietyCorePanel({mode,entities,isAdmin,onNotify,onReload}:{mode:Mode;entities:NetworkAffiliatedEntity[];isAdmin:boolean;onNotify:(s:string)=>void;onReload?:()=>Promise<void>|void}){
 const units=useMemo(()=>entities.filter(e=>e.entity.kind==="unit"),[entities]),people=useMemo(()=>entities.filter(e=>e.entity.kind==="person"),[entities]);
 const [snap,setSnap]=useState<HsPropertySnapshot>({occupancy:[],vehicles:[],parkingSlots:[],parkingAllocations:[],invitations:[]}),[mine,setMine]=useState<HsMyFlat>({claimed:false}),[busy,setBusy]=useState(false);
 const [unitId,setUnitId]=useState(""),[subjectId,setSubjectId]=useState(""),[role,setRole]=useState("occupant"),[start,setStart]=useState(today());
 const [slot,setSlot]=useState(""),[zone,setZone]=useState(""),[vehicleReg,setVehicleReg]=useState(""),[vehicleUnit,setVehicleUnit]=useState(""),[vehicleType,setVehicleType]=useState("car"),[allocationSlot,setAllocationSlot]=useState(""),[allocationUnit,setAllocationUnit]=useState(""),[allocationVehicle,setAllocationVehicle]=useState("");
 const [invitePerson,setInvitePerson]=useState(""),[inviteUnit,setInviteUnit]=useState(""),[inviteEmail,setInviteEmail]=useState("");
 const load=async()=>{try{setSnap(await fetchHsPropertySnapshot());setMine(await fetchHsMyFlat())}catch(e:any){onNotify(e.message||"Could not load Housing Society core.")}};
 useEffect(()=>{load()},[]);
 const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);try{await fn();onNotify(ok);await load();await onReload?.()}catch(e:any){onNotify(e.message||"Could not save change.")}finally{setBusy(false)}};
 if(mode==="my-flat")return <div className="hs1-core"><NetworkSectionHead kicker={<><Home size={12}/> My Flat</>} title={mine.claimed?`${mine.personLabel||"My residence"}`:"Claim your resident profile"} description="Your current flat, household role and vehicles are derived from claimed identity plus time-bounded occupancy records."/>{!mine.claimed?<NetworkEmpty icon={<KeyRound/>} title="No claimed resident profile yet" description="Use the verified-email claim shown on Home. Once claimed, your current flat and household context appear here."/>:<><div className="hs1-unit-grid">{(mine.units||[]).map(u=><section className="card" key={`${u.unitId}-${u.role}`}><span className="warm-kicker">{u.role}</span><h2>{u.unitLabel}</h2><p>{u.startsOn?`Since ${u.startsOn}`:"Current residence"}</p><div className="entity-detail-profile-grid">{Object.entries(u.metadata||{}).filter(([k,v])=>Boolean(v)&&["area","unit_type","building","wing","floor"].includes(k)).slice(0,4).map(([k,v])=><div key={k}><small>{k.replaceAll("_"," ")}</small><b>{String(v)}</b></div>)}</div></section>)}</div><section className="card"><NetworkSectionHead kicker={<><Car size={12}/> Vehicles</>} title="Vehicles linked to my flat" description="Residents can register vehicles only against a flat they currently occupy."/>{(mine.vehicles||[]).length?<div className="hs1-list">{mine.vehicles!.map(v=><div key={v.id}><Car size={17}/><span><b>{v.registrationNo}</b><small>{v.vehicleType}{v.makeModel?` · ${v.makeModel}`:""}{v.isEv?" · EV":""}</small></span></div>)}</div>:<p className="muted">No vehicles registered.</p>}{(mine.units||[])[0]&&<div className="inline-form"><input className="text-input" placeholder="MH12AB1234" value={vehicleReg} onChange={e=>setVehicleReg(e.target.value)}/><select className="select" value={vehicleType} onChange={e=>setVehicleType(e.target.value)}><option value="car">Car</option><option value="two-wheeler">Two-wheeler</option><option value="cycle">Cycle</option></select><button className="btn primary" disabled={busy||vehicleReg.length<4} onClick={()=>run(()=>upsertHsVehicle({unitId:mine.units![0].unitId,ownerEntityId:mine.personId,registrationNo:vehicleReg,vehicleType}),"Vehicle registered.")}><Plus size={14}/> Add vehicle</button></div>}</section></>}</div>;
 return <div className="hs1-core"><NetworkSectionHead kicker={<><Building2 size={12}/> HS-1 property core</>} title="Units, occupancy, claiming & parking" description="Committee-governed property facts preserve history. Bulk onboarding can establish a 20–50 unit pilot without database work."/>
 <div className="hs1-admin-grid"><section className="card"><h3>Record owner / tenant / occupant</h3><div className="stack-form"><select className="select" value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Select flat</option>{units.map(x=><option key={x.entity.id} value={x.entity.id}>{x.entity.label}</option>)}</select><select className="select" value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Select resident</option>{people.map(x=><option key={x.entity.id} value={x.entity.id}>{x.entity.label}</option>)}</select><select className="select" value={role} onChange={e=>setRole(e.target.value)}><option>owner</option><option>co-owner</option><option>tenant</option><option>occupant</option></select><input className="text-input" type="date" value={start} onChange={e=>setStart(e.target.value)}/><button className="btn primary" disabled={busy||!unitId||!subjectId} onClick={()=>run(()=>setHsOccupancy({unitId,subjectId,role,startsOn:start,isPrimary:role==="owner"||role==="tenant"}),"Occupancy history updated.")}>Save lifecycle record</button></div></section>
 <section className="card"><h3>Resident invitation / claiming</h3><p>Invitation records reuse verified-email claiming; ownership facts remain admin-only.</p><div className="stack-form"><select className="select" value={invitePerson} onChange={e=>{setInvitePerson(e.target.value);const p=people.find(x=>x.entity.id===e.target.value);setInviteEmail(String(p?.entity.metadata?.email||""))}}><option value="">Select resident</option>{people.map(x=><option key={x.entity.id} value={x.entity.id}>{x.entity.label}</option>)}</select><select className="select" value={inviteUnit} onChange={e=>setInviteUnit(e.target.value)}><option value="">Optional flat</option>{units.map(x=><option key={x.entity.id} value={x.entity.id}>{x.entity.label}</option>)}</select><input className="text-input" type="email" placeholder="resident@example.com" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/><button className="btn primary" disabled={busy||!invitePerson||!inviteEmail} onClick={()=>run(()=>createHsResidentInvitation(invitePerson,inviteUnit||null,inviteEmail),"Invitation prepared for verified-email claiming.")}>Prepare invite</button></div><div className="hs1-list compact">{snap.invitations.slice(0,6).map(i=><div key={i.id}><InitialsAvatar name={i.personLabel}/><span><b>{i.personLabel}</b><small>{i.email} · {i.status}</small>{i.token&&i.status==="pending"&&<button className="link-button" onClick={()=>navigator.clipboard?.writeText(`${window.location.origin}/society-invite/${i.token}`).then(()=>onNotify("Invitation link copied."))}>Copy invitation link</button>}</span></div>)}</div></section>
 <section className="card"><h3>Parking & vehicles</h3><div className="inline-form"><input className="text-input" placeholder="Slot P-12" value={slot} onChange={e=>setSlot(e.target.value)}/><input className="text-input" placeholder="Zone / basement" value={zone} onChange={e=>setZone(e.target.value)}/><button className="btn" disabled={busy||!slot} onClick={()=>run(()=>upsertHsParkingSlot({slotCode:slot,zone}),"Parking slot saved.")}><ParkingCircle size={14}/> Add slot</button></div><div className="hs1-list compact">{snap.parkingSlots.slice(0,8).map(p=><div key={p.id}><ParkingCircle size={17}/><span><b>{p.slotCode}</b><small>{p.zone||"Unzoned"} · {p.status}</small></span></div>)}</div><div className="stack-form"><select className="select" value={allocationSlot} onChange={e=>setAllocationSlot(e.target.value)}><option value="">Allocate a slot…</option>{snap.parkingSlots.map(p=><option key={p.id} value={p.id}>{p.slotCode}</option>)}</select><select className="select" value={allocationUnit} onChange={e=>setAllocationUnit(e.target.value)}><option value="">Select flat</option>{units.map(u=><option key={u.entity.id} value={u.entity.id}>{u.entity.label}</option>)}</select><select className="select" value={allocationVehicle} onChange={e=>setAllocationVehicle(e.target.value)}><option value="">No vehicle / unit allocation</option>{snap.vehicles.map(v=><option key={v.id} value={v.id}>{v.registrationNo}</option>)}</select><button className="btn" disabled={busy||!allocationSlot||!allocationUnit} onClick={()=>run(()=>allocateHsParking({slotId:allocationSlot,unitId:allocationUnit,vehicleId:allocationVehicle||null}),"Parking allocation saved with history.")}>Allocate parking</button></div></section></div>
 <section className="card hs1-history"><NetworkSectionHead title="Owner / tenant history" description="Past records are retained instead of overwritten when a resident moves, sells, or a tenancy changes."/><div className="table-wrap"><table><thead><tr><th>Flat</th><th>Resident / household</th><th>Role</th><th>From</th><th>To</th></tr></thead><tbody>{snap.occupancy.slice(0,50).map(h=><tr key={h.id}><td>{h.unitLabel}</td><td>{h.subjectLabel}</td><td>{h.role}</td><td>{h.startsOn}</td><td>{h.endsOn||"Current"}</td></tr>)}</tbody></table></div></section>
 <GuidedWorkbookImport kind="housing-society" onCommit={commitHousingWorkbook} onCommitted={async result=>{onNotify(result.message);await load();await onReload?.()}} title="Housing Society guided bulk onboarding"/></div>
}
