import type {NetworkAffiliatedEntity,NetworkActivity} from "../../core/network-os/contracts";
import type {NetworkGroup} from "../../capabilities/activity/remote";
import type {VerticalTemplateDefinition} from "../../core/templates/contracts";
import {ORGANIZATION_TEMPLATE} from "../organization/definition";
import {BUSINESS_TRUST_TEMPLATE} from "../business-trust/definition";
import {FRANCHISE_TEMPLATE} from "../franchise/definition";

export type ProductizedVerticalKind="organization"|"business-trust"|"franchise";
export type ProductizedNetworkConfig={
 kind:ProductizedVerticalKind; template:VerticalTemplateDefinition; label:string; shortLabel:string; iconToken:string; themeClass:string;
 primaryEntityLabel:string; primaryEntityPlural:string; locationDimension:string; subtitleDimensions:string[];
 heroTitle:string; heroDescription:string; directoryTitle:string; explorerTitle:string; communityTitle:string; placesTitle:string; connectionsTitle:string; contributionTitle:string; adminTitle:string;
 createTitle:string; createDescription:string; namePlaceholder:string; contextLabel:string; contextPlaceholder:string;
 groupLabel:string; eventLabel:string; memoryLabel:string; milestoneLabel:string;
 relationshipHelp:string; guideSteps:[string,string,string][]; sampleName:string; sampleDescription:string;
 sampleEntities:NetworkAffiliatedEntity[]; sampleActivities:NetworkActivity[]; sampleGroups:NetworkGroup[]; sampleRelationships:{id:string;fromEntityId:string;toEntityId:string;relationshipType:string;label:string}[];
};
const entity=(id:string,label:string,kind:string,affiliations:Record<string,string[]>,metadata:Record<string,unknown>={}):NetworkAffiliatedEntity=>({entity:{id,networkId:"sample",kind,label,metadata},affiliations});
const orgEntities=[
 entity("o1","Aditi Deshmukh","person",{region:["India"],business_unit:["Technology"],department:["Engineering"],team:["Platform"],project:["Identity Platform"],skill:["Architecture","React"]},{role:"Principal Engineer",email:"aditi@example.com",city:"Pune"}),
 entity("o2","Rahul Mehta","person",{region:["India"],business_unit:["Technology"],department:["Engineering"],team:["Data Platform"],project:["Customer 360"],skill:["Data","Distributed Systems"]},{role:"Staff Engineer",city:"Bengaluru"}),
 entity("o3","Neha Kulkarni","person",{region:["India"],business_unit:["Product"],department:["Product Management"],team:["Core Product"],project:["Customer 360"],skill:["Product Strategy"]},{role:"Director Product",city:"Mumbai"}),
 entity("o4","Sameer Shah","person",{region:["Europe"],business_unit:["Technology"],department:["Security"],team:["AppSec"],project:["Identity Platform"],skill:["Security","IAM"]},{role:"Security Architect",city:"London"}),
 entity("o5","Meera Joshi","person",{region:["India"],business_unit:["Customer"],department:["Solutions"],team:["Enterprise Architecture"],project:["Strategic Accounts"],skill:["Architecture","Customer Success"]},{role:"Solutions Director",city:"Pune"}),
] as NetworkAffiliatedEntity[];
const trustEntities=[
 entity("b1","Precision Packaging Pvt Ltd","organization",{region:["Pune"],category:["Packaging"],service:["Industrial Packaging"]},{contact:"Anita Shah",website:"precision.example",confidence:"verified"}),
 entity("b2","Western Logistics","organization",{region:["Maharashtra"],category:["Logistics"],service:["Freight","Warehousing"]},{contact:"Vikram Patil",confidence:"trusted"}),
 entity("b3","Nova Components","organization",{region:["Pune"],category:["Manufacturing"],service:["Machined Components"]},{contact:"Rohit Mehta",confidence:"verified"}),
 entity("b4","SecureIT Services","organization",{region:["Mumbai"],category:["Technology"],service:["Cybersecurity"]},{contact:"Priya Nair",confidence:"trusted"}),
 entity("b5","Green Office Solutions","organization",{region:["Pune"],category:["Facilities"],service:["Office Infrastructure"]},{contact:"Kunal Joshi",confidence:"community"}),
] as NetworkAffiliatedEntity[];
const franchiseEntities=[
 entity("f1","Kharadi Central","branch",{country:["India"],state:["Maharashtra"],city:["Pune"],store_type:["Flagship"],owner:["Naval Foods"]},{manager:"Aarav Kulkarni",code:"PUN-KHD-01",lat:18.551,lon:73.947}),
 entity("f2","Viman Nagar","branch",{country:["India"],state:["Maharashtra"],city:["Pune"],store_type:["Mall"],owner:["Naval Foods"]},{manager:"Riya Shah",code:"PUN-VIM-02",lat:18.5679,lon:73.9143}),
 entity("f3","Baner High Street","branch",{country:["India"],state:["Maharashtra"],city:["Pune"],store_type:["High Street"],owner:["West Retail Partners"]},{manager:"Nikhil Patil",code:"PUN-BAN-03",lat:18.559,lon:73.7868}),
 entity("f4","Andheri West","branch",{country:["India"],state:["Maharashtra"],city:["Mumbai"],store_type:["High Street"],owner:["West Retail Partners"]},{manager:"Sara Mehta",code:"MUM-AND-01",lat:19.136,lon:72.827}),
 entity("f5","Whitefield","branch",{country:["India"],state:["Karnataka"],city:["Bengaluru"],store_type:["Mall"],owner:["South Retail Group"]},{manager:"Dev Rao",code:"BLR-WHT-01",lat:12.9698,lon:77.75}),
] as NetworkAffiliatedEntity[];
export const PRODUCTIZED_NETWORK_CONFIGS:Record<ProductizedVerticalKind,ProductizedNetworkConfig>={
 organization:{kind:"organization",template:ORGANIZATION_TEMPLATE,label:"Organizational Intelligence",shortLabel:"Organization",iconToken:"building",themeClass:"org-network",primaryEntityLabel:"Person",primaryEntityPlural:"People",locationDimension:"region",subtitleDimensions:["team","project","skill"],heroTitle:"Understand how your organization really works.",heroDescription:"Explore formal structure, matrix teams, expertise, projects and connection paths in one living organizational network.",directoryTitle:"People & expertise",explorerTitle:"Organization explorer",communityTitle:"Teams, guilds & shared work",placesTitle:"Where the organization operates",connectionsTitle:"Collaboration & ownership graph",contributionTitle:"Keep organizational knowledge current",adminTitle:"Organization Admin",createTitle:"Create an Organizational Intelligence network",createDescription:"Start with your organization, then import people, teams, projects and expertise. The same person can belong to multiple structures.",namePlaceholder:"e.g. Acme India Organization Network",contextLabel:"Organization / company",contextPlaceholder:"e.g. Acme Technologies",groupLabel:"Guild / community",eventLabel:"Workshop / town hall",memoryLabel:"Project history",milestoneLabel:"Achievement",relationshipHelp:"Connect people and entities with reports-to, works-with, owns or depends-on relationships.",guideSteps:[["1","Import people & structure","Start with names plus region, business unit, department and team."],["2","Add matrix context","Projects and skills let people appear in more than one useful view."],["3","Map collaboration","Use relationships for reporting, ownership, dependencies and trusted paths."],["4","Keep it alive","Guilds, workshops, history and contributions keep the org graph current."]],sampleName:"Northstar Organizational Intelligence",sampleDescription:"Read-only sample matrix organization",sampleEntities:orgEntities,sampleActivities:[{id:"oe1",type:"event",title:"Architecture Guild Workshop",body:"Identity Platform and Data Platform share design patterns.",startsAt:"2026-09-04T15:00:00",place:"Pune + Online",goingCount:24},{id:"om1",type:"memory",title:"Customer 360 architecture decision",body:"Why the platform adopted event-driven ingestion."},{id:"om2",type:"milestone",title:"Identity Platform rollout",body:"First three products migrated successfully."}],sampleGroups:[{id:"og1",name:"Architecture Guild",groupType:"guild",memberCount:18},{id:"og2",name:"Security Champions",groupType:"community",memberCount:11}],sampleRelationships:[{id:"or1",fromEntityId:"o1",toEntityId:"o2",relationshipType:"works_with",label:"Works with"},{id:"or2",fromEntityId:"o4",toEntityId:"o1",relationshipType:"works_with",label:"Works with"},{id:"or3",fromEntityId:"o3",toEntityId:"o2",relationshipType:"depends_on",label:"Depends on"}]},
 "business-trust":{kind:"business-trust",template:BUSINESS_TRUST_TEMPLATE,label:"Business Trust Network",shortLabel:"Business Trust",iconToken:"handshake",themeClass:"trust-network",primaryEntityLabel:"Business",primaryEntityPlural:"Businesses",locationDimension:"region",subtitleDimensions:["category","service"],heroTitle:"Discover businesses through trust, not just search.",heroDescription:"Build a private ecosystem of businesses, providers and partners with recommendations, relationship provenance and warm connection paths.",directoryTitle:"Trusted business directory",explorerTitle:"Trust network explorer",communityTitle:"Partner community & opportunities",placesTitle:"Business coverage",connectionsTitle:"Trust & partner relationships",contributionTitle:"Strengthen the trusted network",adminTitle:"Business Trust Admin",createTitle:"Create a Business Trust Network",createDescription:"Start a private business ecosystem and add suppliers, service providers, partners and trusted relationships.",namePlaceholder:"e.g. Pune Manufacturing Trust Network",contextLabel:"Network purpose / ecosystem",contextPlaceholder:"e.g. Trusted suppliers and service partners",groupLabel:"Business circle",eventLabel:"Partner meetup",memoryLabel:"Relationship note",milestoneLabel:"Verified achievement",relationshipHelp:"Record recommends, verified-by, supplies-to and worked-with relationships with clear provenance.",guideSteps:[["1","Add trusted businesses","Import companies, categories, services and regions."],["2","Record why you trust them","Use typed relationships instead of anonymous ratings."],["3","Discover by context","Explore Region → Category or Category → Region."],["4","Activate the ecosystem","Use circles, meetups and contribution requests to keep it useful."]],sampleName:"Pune Business Trust Network",sampleDescription:"Read-only sample trusted business ecosystem",sampleEntities:trustEntities,sampleActivities:[{id:"be1",type:"event",title:"Trusted Supplier Roundtable",body:"Small-group sourcing and introductions.",startsAt:"2026-09-12T18:00:00",place:"Pune",goingCount:14},{id:"bm1",type:"memory",title:"Packaging partner recommendation",body:"Precision Packaging delivered a difficult short-run order on time."},{id:"ba1",type:"announcement",title:"Cybersecurity partner verified",body:"SecureIT completed references with two network businesses."}],sampleGroups:[{id:"bg1",name:"Manufacturing Circle",groupType:"business-circle",memberCount:12},{id:"bg2",name:"Pune Service Partners",groupType:"regional-circle",memberCount:16}],sampleRelationships:[{id:"br1",fromEntityId:"b3",toEntityId:"b1",relationshipType:"recommends",label:"Recommends"},{id:"br2",fromEntityId:"b1",toEntityId:"b2",relationshipType:"worked_with",label:"Worked with"},{id:"br3",fromEntityId:"b2",toEntityId:"b4",relationshipType:"verified_by",label:"Verified by"}]},
 franchise:{kind:"franchise",template:FRANCHISE_TEMPLATE,label:"Franchise Network",shortLabel:"Franchise",iconToken:"store",themeClass:"franchise-network",primaryEntityLabel:"Location",primaryEntityPlural:"Locations",locationDimension:"city",subtitleDimensions:["state","store_type","owner"],heroTitle:"Operate a distributed franchise as one connected network.",heroDescription:"Explore regions, locations, owners and managers; share training, launches and operational knowledge across every city.",directoryTitle:"Locations & operators",explorerTitle:"Franchise network explorer",communityTitle:"Operations community",placesTitle:"Location network",connectionsTitle:"Ownership & support relationships",contributionTitle:"Keep every location operationally current",adminTitle:"Franchise Admin",createTitle:"Create a Franchise Network",createDescription:"Create the brand network, then add/import locations, owners and operational structure across regions and cities.",namePlaceholder:"e.g. Brand India Franchise Network",contextLabel:"Brand / franchise system",contextPlaceholder:"e.g. Northstar Foods India",groupLabel:"Regional council",eventLabel:"Training / franchise meetup",memoryLabel:"Launch / operations history",milestoneLabel:"Store milestone",relationshipHelp:"Connect owners, locations and support relationships while geography remains independently explorable.",guideSteps:[["1","Add locations","Import country, state, city, store type and owner."],["2","Explore two ways","Navigate geography or ownership without duplicating stores."],["3","Connect operators","Model ownership, management and support relationships."],["4","Share operational learning","Training, launch history and regional groups keep the network aligned."]],sampleName:"Northstar India Franchise Network",sampleDescription:"Read-only sample multi-city franchise network",sampleEntities:franchiseEntities,sampleActivities:[{id:"fe1",type:"event",title:"New Menu Operations Training",body:"Managers and franchise owners align before the national launch.",startsAt:"2026-09-08T11:00:00",place:"Online",goingCount:32},{id:"fm1",type:"memory",title:"Kharadi flagship opening",body:"Launch checklist and lessons from opening week."},{id:"fm2",type:"milestone",title:"50th India location",body:"The network crosses fifty operating locations."}],sampleGroups:[{id:"fg1",name:"Pune Operators Council",groupType:"regional-council",memberCount:8},{id:"fg2",name:"New Store Launch Circle",groupType:"operations",memberCount:13}],sampleRelationships:[{id:"fr1",fromEntityId:"f1",toEntityId:"f2",relationshipType:"supports",label:"Supports"},{id:"fr2",fromEntityId:"f3",toEntityId:"f4",relationshipType:"supports",label:"Supports"}]}
};
export const PRODUCTIZED_VERTICAL_KINDS=Object.keys(PRODUCTIZED_NETWORK_CONFIGS) as ProductizedVerticalKind[];
export function isProductizedVerticalKind(value:string):value is ProductizedVerticalKind{return value in PRODUCTIZED_NETWORK_CONFIGS}
