import {test,expect} from '@playwright/test';import {assertMutationAllowed} from '../lib/safety';import {authenticatedClient} from '../lib/role-client';
test('institutional bootstrap certifies 100-row volume, pagination/search and idempotency',async({request})=>{
 test.skip(process.env.QA_MODE!=='staging'||process.env.QA_ALLOW_MUTATION!=='true','staging mutation suite');assertMutationAllowed();const a=await authenticatedClient('owner'),suffix=Date.now(),name=`QA Volume ${suffix}`,createKey=crypto.randomUUID();
 const c=await request.post('/api/v1/networks/create',{headers:{authorization:`Bearer ${a.token}`,'idempotency-key':createKey},data:{kind:'organization',name,contextValue:'Volume QA'}});expect(c.status()).toBe(201);const cj=await c.json(),id=cj.data?.networkId||cj.data?.id||cj.networkId;expect((await a.client.rpc('set_active_network',{p_network_id:id})).error).toBeNull();
 try{
  const rows=Array.from({length:100},(_,i)=>({kind:'person',label:`Volume Person ${suffix}-${String(i).padStart(3,'0')}`,metadata:{qa:true,index:i,city:i%2?'Pune':'Mumbai'}})),key=crypto.randomUUID(),h={authorization:`Bearer ${a.token}`,'idempotency-key':key};
  const one=await request.post('/api/v1/institutional/bootstrap',{headers:h,data:{rows}}),two=await request.post('/api/v1/institutional/bootstrap',{headers:h,data:{rows}});expect([200,201]).toContain(one.status());expect(two.status()).toBe(one.status());
  const count=await a.client.from('network_entities').select('id',{count:'exact',head:true}).eq('network_id',id).eq('kind','person');expect(count.error).toBeNull();expect(count.count||0).toBe(100);
  const page1=await a.client.from('network_entities').select('id,label').eq('network_id',id).eq('kind','person').order('label').range(0,24),page2=await a.client.from('network_entities').select('id,label').eq('network_id',id).eq('kind','person').order('label').range(25,49);expect(page1.error).toBeNull();expect(page2.error).toBeNull();expect(page1.data?.length).toBe(25);expect(page2.data?.length).toBe(25);expect(new Set([...(page1.data||[]),...(page2.data||[])].map(x=>x.id)).size).toBe(50);
  const search=await a.client.from('network_entities').select('id,label').eq('network_id',id).ilike('label',`%${suffix}-09%`);expect(search.error).toBeNull();expect((search.data||[]).length).toBeGreaterThan(0);
  if(process.env.QA_RUN_LARGE_VOLUME==='true'){for(let batch=0;batch<2;batch++){const large=Array.from({length:500},(_,i)=>({kind:'person',label:`Large ${suffix}-${batch}-${i}`,metadata:{batch,i}}));const r=await request.post('/api/v1/institutional/bootstrap',{headers:{authorization:`Bearer ${a.token}`,'idempotency-key':crypto.randomUUID()},data:{rows:large}});expect([200,201]).toContain(r.status())}}
 }finally{await request.post(`/api/v1/networks/${id}/purge`,{headers:{authorization:`Bearer ${a.token}`},data:{confirmName:name}})}
});
