import {supabase} from "../../lib/supabase";
import {postCommand} from "../../lib/api-client";
import type {BootstrapInstitutionResult,ClaimIdentityResult,CreateGraphRelationshipResult,CreateNetworkResult,JoinNetworkResult} from "../../core/api/contracts";
import type {ProductizedVerticalKind} from "../../templates/productized/config";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
export type TemplateNetworkSettings={templateId:string;contextLabel:string;contextValue:string;description?:string|null};
export type NetworkEntityRelationship={id:string;fromEntityId:string;toEntityId:string;fromLabel:string;toLabel:string;relationshipType:string;label:string;metadata?:Record<string,unknown>};
export type GenericContribution={id:string;entityId?:string|null;entityLabel?:string|null;message:string;payload:Record<string,unknown>;status:"open"|"accepted"|"rejected";createdAt:string;createdBy?:string|null};
export async function createTemplateNetwork(kind:ProductizedVerticalKind,name:string,contextValue:string,description=""){const data=await postCommand<CreateNetworkResult>("/api/v1/networks/create",{kind,name,contextValue,description},{idempotent:true});return data.networkId}
export async function fetchTemplateNetworkSettings(){const s=required();const {data,error}=await s.rpc("get_productized_network_settings");if(error)throw error;const r=(data||[])[0];return r?{templateId:String(r.template_id),contextLabel:String(r.context_label||"Network"),contextValue:String(r.context_value||""),description:r.description} as TemplateNetworkSettings:null}
export async function upsertNetworkEntity(input:{id?:string;kind:string;label:string;metadata?:Record<string,unknown>;affiliations?:Record<string,string|string[]>;visibility?:"members"|"private"}){const s=required();const {data,error}=await s.rpc("upsert_productized_network_entity",{p_entity_id:input.id||null,p_kind:input.kind,p_label:input.label,p_metadata:input.metadata||{},p_affiliations:input.affiliations||{},p_visibility:input.visibility||"members"});if(error)throw error;return String(data)}
export async function deleteNetworkEntity(id:string){const s=required();const {error}=await s.rpc("delete_productized_network_entity",{p_entity_id:id});if(error)throw error}
export async function importNetworkEntities(rows:{kind?:string;label:string;metadata?:Record<string,unknown>;affiliations?:Record<string,string|string[]>}[]){return postCommand<BootstrapInstitutionResult>("/api/v1/institutional/bootstrap",{rows},{idempotent:true})}
export async function fetchNetworkEntityRelationships(){const s=required();const {data,error}=await s.rpc("get_productized_network_relationships");if(error)throw error;return (data||[]).map((r:any)=>({id:String(r.id),fromEntityId:String(r.from_entity_id),toEntityId:String(r.to_entity_id),fromLabel:String(r.from_label),toLabel:String(r.to_label),relationshipType:String(r.relationship_type),label:String(r.relationship_label||r.relationship_type),metadata:r.metadata||{}})) as NetworkEntityRelationship[]}
export async function createNetworkEntityRelationship(fromEntityId:string,toEntityId:string,relationshipType:string,metadata:Record<string,unknown>={}){const data=await postCommand<CreateGraphRelationshipResult>("/api/v1/graph/relationships",{fromEntityId,toEntityId,relationshipType,metadata});return data.relationshipId}
export async function deleteNetworkEntityRelationship(id:string){const s=required();const {error}=await s.rpc("delete_productized_network_relationship",{p_relationship_id:id});if(error)throw error}
export async function getOrCreateNetworkJoinCode(){const s=required();const {data,error}=await s.rpc("get_or_create_network_join_code");if(error)throw error;return String(data||"")}
export async function regenerateNetworkJoinCode(){const s=required();const {data,error}=await s.rpc("regenerate_network_join_code");if(error)throw error;return String(data||"")}
export async function joinProductizedNetworkByCode(code:string){const data=await postCommand<JoinNetworkResult>("/api/v1/networks/join",{kind:"productized",code});return data.networkId}
export async function submitNetworkContribution(entityId:string|null,message:string,payload:Record<string,unknown>={}){const s=required();const {data,error}=await s.rpc("submit_productized_network_contribution",{p_entity_id:entityId,p_message:message,p_payload:payload});if(error)throw error;return String(data)}
export async function fetchNetworkContributions(){const s=required();const {data,error}=await s.rpc("get_productized_network_contributions");if(error)throw error;return (data||[]).map((r:any)=>({id:String(r.id),entityId:r.entity_id?String(r.entity_id):null,entityLabel:r.entity_label||null,message:String(r.message),payload:r.payload||{},status:r.status,createdAt:r.created_at,createdBy:r.created_by})) as GenericContribution[]}
export async function reviewNetworkContribution(id:string,action:"accepted"|"rejected"){const s=required();const {error}=await s.rpc("review_productized_network_contribution",{p_contribution_id:id,p_action:action});if(error)throw error}

export type ClaimableProductizedEntity={entityId:string;entityKind:string;entityLabel:string;networkId:string;networkName:string};
export async function fetchClaimableProductizedEntities(){const s=required();const {data,error}=await s.rpc("get_my_claimable_productized_entities");if(error)throw error;return (data||[]).map((r:any)=>({entityId:String(r.entity_id),entityKind:String(r.entity_kind),entityLabel:String(r.entity_label),networkId:String(r.network_id),networkName:String(r.network_name)})) as ClaimableProductizedEntity[]}
export async function claimProductizedEntity(entityId:string){const data=await postCommand<ClaimIdentityResult>("/api/v1/identities/claim",{kind:"productized",subjectId:entityId});return data.networkId}

export type ProductizedNetworkMember={userId:string;email?:string|null;role:"owner"|"admin"|"member";status:string;entityLabel?:string|null;joinedAt?:string};
export async function fetchProductizedNetworkMembers(){const s=required();const {data,error}=await s.rpc("get_productized_network_memberships");if(error)throw error;return (data||[]).map((r:any)=>({userId:String(r.user_id),email:r.email||null,role:r.role,status:r.status,entityLabel:r.entity_label||null,joinedAt:r.joined_at})) as ProductizedNetworkMember[]}
export async function setProductizedNetworkMemberRole(userId:string,role:"admin"|"member"){const s=required();const {error}=await s.rpc("set_productized_network_member_role",{p_user_id:userId,p_role:role});if(error)throw error}
export async function removeProductizedNetworkMember(userId:string){const s=required();const {error}=await s.rpc("remove_productized_network_member",{p_user_id:userId});if(error)throw error}
